### ISSUE TITLE
Help users to understand when it's appropriate to use input type="number"

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-design-system#1127]
## What

Help users to understand when it's appropriate to use `input type="number"`.

## Why

We have [a lot of research that shows that `input type="number"` can be problematic](https://github.com/alphagov/govuk-frontend/issues/1449#issuecomment-503186819) and we believe that it should only be used in very specific contexts.

## Stories

- [x] Add guidance to the text input component to help users understand when to use input type="number" #1128
- [x] Consider renaming the 'text input' component to just 'input' in the Design System #1129
- [x] Write a blog post that covers the changes to the date input component, some of the detail about strange behaviour seen in research (usability and accessibility), bugs we've reported #1130 

## Related

- Improve the date input component https://github.com/alphagov/govuk-frontend/issues/1695
