### ISSUE TITLE
Support updated 'Tag' component contribution

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#1142]
## What
Prepare updated 'Tags' component for review by the working group.

## Why
To ensure contribution is ready for review.

## Who needs to know about this
Adam (contributor), Tim, Stephen, team (working group support)

## Done when
- [x] Contribution is ready for review by working group
- [x] Contribution has been sent to working group (30 Jan)
- [x] Decision and feedback have been received from all working group members (13 Feb)
- [x] Review feedback
- [x] Communicate decisions with working group
- [x] Publish

**Comment by kellylee-gds** [comment]
Blocked until 13 Feb when we will receive full working group feedback.
