### ISSUE TITLE
Develop high level service vision and roadmap

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#1157]
# What

Develop a high level roadmap that details which outcomes and needs must be met before the Design System can move in to live, and which can be met once the service is live.

# Why

Doing this will enable us to plan our work for Q1 and will help the programme understand how long it will be before we're ready to go live, and what size and shape team will be required before and after live.

# Who

Tim leading, working closely with Ollie and Kelly, with at least one whole-team session.

# Done when

- [x] we've agreed on a high level vision for the future of the Design System
- [x] we've consolidated existing data on high level users needs, strategic alignment and performance against relevant standards
- [x] we've had a team session to discuss, size and prioritise the outcomes and needs for pre and post live

**Comment by timpaul** [comment]
[The work for this card will be captured here initially](https://docs.google.com/spreadsheets/d/12dIae75aAiGy28ZLVAK8Z58ZouZx1f5OV0N-y6kSe0M/edit#gid=0)

**Comment by kellylee-gds** [comment]
Closing this for now.
