### ISSUE TITLE
Make it clearer which steps in task list pattern have not been completed

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#1183]
## What
Review [backlog entry for task list pattern](https://github.com/alphagov/govuk-design-system-backlog/issues/72) and decide on best approach to make steps clearer.

## Why
Evidence on backlog entry for task list suggests users are struggling with this.

## Who needs to know about this
Stephen/Mark, Chris, Tim

## Further detail
Changes can be made following publishing of #1143 

## Done when
- [x] We are sure there is evidence supports this
- [x] Make relevant changes to task list guidance
- [x] Update screen shot(s) on task list guidance where relevant
- [x] Update [task list code](https://govuk-prototype-kit.herokuapp.com/docs/templates/task-list) on Prototype Kit 
- [x] Review by team
- [ ] Publish changes

## Next steps
[#276](https://github.com/alphagov/design-system-team-internal/issues/276)
