### ISSUE TITLE
Define and capture KPIs for Design System

### ISSUE THREAD

**Issue by trang-erskine** [alphagov/govuk-design-system#1385]
## What 

The team is working with a performance analyst to build a performance framework for the Design System. This framework will help us define what key performance indicators we need measure to meet our users' need and us make more data driven decisions about our priorities. 

## Stories

- [x] Setting up a performance framework https://github.com/alphagov/govuk-design-system/issues/1340
- [x] Decide which KPIs to measure and data source
- [ ] https://github.com/alphagov/design-system-team-internal/issues/353
- [ ] https://github.com/alphagov/design-system-team-internal/issues/354
- [ ] https://github.com/alphagov/design-system-team-internal/issues/355
- [ ] https://github.com/alphagov/design-system-team-internal/issues/356
- [ ] https://github.com/alphagov/design-system-team-internal/issues/357
- [x] https://github.com/alphagov/design-system-team-internal/issues/358
- [ ] https://github.com/alphagov/design-system-team-internal/issues/359
- [x] https://github.com/alphagov/design-system-team-internal/issues/361
- [ ] https://github.com/alphagov/design-system-team-internal/issues/363
- [ ] https://github.com/alphagov/design-system-team-internal/issues/367
- [x] https://github.com/alphagov/design-system-team-internal/issues/368
- [ ] https://github.com/alphagov/design-system-team-internal/issues/369
- [ ] https://github.com/alphagov/design-system-team-internal/issues/370
- [ ] https://github.com/alphagov/design-system-team-internal/issues/371
- [ ] https://github.com/alphagov/design-system-team-internal/issues/372
- [ ] https://github.com/alphagov/design-system-team-internal/issues/373

**Comment by trang-erskine** [comment]
Reviewing Design System KPI now that we have a PA on the team. Will be replaced with a number of other epics.
