### ISSUE TITLE
Users can find out what we are working on

### ISSUE THREAD

**Issue by trang-erskine** [alphagov/govuk-design-system#1410]
## What
We want to make it clearer to our users what the team is working on, the purpose of the community backlog, progress of items in the community backlog and the roadmap.

## Why
Users have told us that they don't know what we are working on. Some users know about our sprint board and roadmap board on Github, but don't frequency visit and many don't know it exist at all.

Users (and the team) have also told us that the community backlog is particularly difficult to see progress and it looks very stagnant. The board view isn't easy to find. 

## Who needs to know about this
Team and the community

## Done when:
- [x] https://github.com/alphagov/govuk-design-system/issues/1818
- [x] https://github.com/alphagov/govuk-design-system/issues/1883
- [x] https://github.com/alphagov/govuk-design-system/issues/1824
- [x] https://github.com/alphagov/govuk-design-system/issues/1821
- [x] https://github.com/alphagov/govuk-design-system/issues/1833
- [x] https://github.com/alphagov/govuk-design-system/issues/1834
- [x] #1876 
- [x] #1878
- [x] #1954 
- [x] #1970 
- [x] #1958

## Next steps
- Review contribution guidance and internal team processes
- https://github.com/alphagov/govuk-design-system/issues/1845
- Prioritise the community backlog
- Build a feedback loop between the community backlog and the Design System team
- Review the structure of discussions on the community backlog (includes investigating use of GitHub Discussions, publishing a code of conduct, how we deliver comms on iterations to existing components and patterns)

**Comment by kellylee-gds** [comment]
Previous body of issue:

## What
We want to make it clearer to our users what the team is working on, the purpose of the community backlog, progress of items in the community backlog and the roadmap.

## Why
Users have told us that they don't know what we are working on. Some users know about our sprint board and roadmap board on Github, but don't frequency visit and many don't know it exist at all. 

Users (and the team) have also told us that the community backlog is particularly difficult to see progress and it looks very stagnant. The board view isn't easy to find. 

## Who needs to know about this
Team and the community
