### ISSUE TITLE
Improve our internal documentation

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#1431]
Body of epic to be completed after a kick off session

**Comment by kellylee-gds** [comment]
## What
A recent tech and ops health check identified areas in which we can improve our internal technical documentation particularly regarding knowledge management and findability

## Why
- To document any knowledge which currently exists in individual's heads
- To make existing documentation visible to users where it is useful to do so

## Who needs to know about this
Tech Writer, Developers

## Further detail
GOV.UK Pay have externally documented processes such as [support](https://docs.payments.service.gov.uk/support_contact_and_more_information/#support) and [contribution](https://docs.payments.service.gov.uk/contribute/#contribute)

## Done when
- [x] Review existing internal technical documentation and identify documentation which should be external #1432 
- [ ] Identify user groups, for example the team, new users, experienced users.
- [ ] Agree where to host external technical documentation #1433 
- [ ] Identify missing internal and external technical documentation [#1434](https://github.com/alphagov/govuk-design-system/issues/1434)

**Comment by trang-erskine** [comment]
Going to be covered in https://github.com/alphagov/govuk-design-system/issues/2352
