### ISSUE TITLE
Help users discover what's new in the GOV.UK Design System

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#1469]
## What
Help users of the Design System website discover what has recently been added or changed in the Design System.

## Why

There's no way for users of the Design System website to find out about changes to guidance or about the addition of new components or patterns.

This is important because some changes may be relevant to the work that a user is doing or is planning to do.

## Who needs to know about this

Content Designer, Designer, Community Manager

## Further detail

We do use our support channels (and our personal Twitter accounts) to tell users about changes, but these messages are ephemeral and there's a high chance they'll be missed by some users.

GOV.UK Frontend uses release notes to capture information about changes, but there's no equivalent for the Design System itself.

The NHS Service Manual home page has one example of how this feature can be implemented: https://service-manual.nhs.uk/

## Done when

Scoping
- [x] Decide which kinds of change should be documented, how and where

Prototyping
- [x] Prototype, test and iterate what a 'What's new' feature for the Design System might be like

Channels
- [x] Scope options for mailing list #1593

**Comment by kellylee-gds** [comment]
Moving back to sprint 3

**Comment by joelanman** [comment]
related: https://github.com/alphagov/govuk-design-system/issues/729

**Comment by mgladdish** [comment]
Somewhat related, but I don't know where else to add this, could a link to the roadmap (https://github.com/orgs/alphagov/projects/5) also be included in the docs? Maybe somewhere in https://design-system.service.gov.uk/community/ ?

Also I can't find where the git repo is listed, either, for people to find open issues.

And the community backlog that is included is somehow different to the roadmap I've linked above? As an outsider it's really not clear the difference between these two, and so which things we can expect to see 'new' soon.

**Comment by vanitabarrett** [comment]
See suggestion below from Ed on Slack. This came out of a conversation with someone in the prototype kit channel who was trying to use the new 'none of the above' checkboxes feature in their prototype, but hadn't realised that it was a new thing and they needed to update the version of GOV.UK Frontend that their prototype was using.

> Has the design system team considered marking new things as they're added? Something like how Eleventy marks new features in its docs.

![screenshot_2021-06-30_at_13 53 37](https://user-images.githubusercontent.com/29889908/123975207-13d58380-d9b5-11eb-8ac3-678897dc222c.png)

We might need to consider how to make this usable for kit users as I assume not everyone will need to know how to check the version of Frontend that their prototype is using. But that’s something we could work out. The other interesting thing is the versioning of specific features of components that aren’t called out in the guidance, like the improvements we’re making to the accordion right now. (comment from @hannalaakso on Slack)
