### ISSUE TITLE
Publish pattern for security code contribution

### ISSUE THREAD

**Issue by calvin-lau-sig7** [alphagov/govuk-design-system#1524]
## What

Create pattern for security code, based on contribution and conversations. Will need to find a way to publish this information to stand on its own without relying on guidance around authentication which we don't have yet.

[Backlog entry](https://github.com/alphagov/govuk-design-system-backlog/issues/239)

## Why

There's probably a bigger piece of work to be done around this, however design lead agreed it's useful information to publish.

## Who needs to know about this

Contributor, design resource, wider GDS teams working on this topic (such as Verify) to ensure alignment

## Done when

- [x] 'Lead' contributor (Frankie helping us) resolves conversations in pull request
- [x] Relevant takeaways from contributor conversations added into draft content, probably Research
- [x] Entry created on [community backlog](https://github.com/alphagov/govuk-design-system-backlog/projects/1)
- [x] Reviewed by working group as a proposal
- [x] Content designer makes draft edit of page
- [x] Reviewed by working group in development
- [x] Check-in ensure alignment with similar work in GDS Digital Identity — GOV.UK Sign In
- [x] Working group recommendations are implemented
- [ ] Consider adding [a modifier for text inputs to increase letter spacing and use tabular numbers](https://github.com/alphagov/govuk-frontend/pull/2230) – and getting the working group to review it if necessary
- [ ] Review within team and contributors
- [ ] 2nd working group review (to be usable, consistent and versatile)
- [ ] Finalise content and merge

### Working group recommendations

Consider:
- [x] how this pattern would work for different circumstances, such as people with limited internet access or no access to a phone
- [x] how the time limit (currently 15 minutes) would affect people with poor reception — could it delay delivery of  the text message or otherwise cause panic?
- [x] if the journey should be slightly different ‘when creating an account’ compared to ‘when signing in’ (currently they’re nearly the same design) — users usually expect more verification to set up security processes
- [x] if the code should be more than 4 digits — 5 or 6 would be more secure, and 2 groups of 3 digits (123 456) might be easier to remember
- [x] grouping this page with related design standards for other authentication methods

**Comment by hannalaakso** [comment]
Related: Card for the pattern to help users to authenticate: https://github.com/alphagov/govuk-design-system/issues/1280

**Comment by kellylee-gds** [comment]
Hey @calvin-lau-sig7 following our convo, I did some digging and this hasn't been reviewed by the working group at the [proposal stage](https://design-system.service.gov.uk/community/propose-a-component-or-pattern/) so we would need to do that first. I've updated the 'Done whens' to reflect that.

**Comment by kellylee-gds** [comment]
I've also made this an epic card so we can break it down into smaller stories to work on

**Comment by CharlotteDowns** [comment]
A new GOV.UK Design System backlog entry has been created for [Prove who they are with a text message](https://github.com/alphagov/govuk-design-system-backlog/issues/239)

**Comment by CharlotteDowns** [comment]
Hoping to share [this slide deck on the pattern](https://docs.google.com/presentation/d/14nf6l51ax1rXh2-EqeLmn1RxqtCqbHWDtpHg_WS2T40/edit#slide=id.gfc3080fe16_0_0) at the next team show and tell.

Caught up with the Digital Identity team at GDS who are working on an over the phone password solution for GOV.UK Accounts and the Brexit checker. [Notes from the meeting with the Digital Identity team](https://docs.google.com/document/d/1Znl5Kme61RLUmbIfdv04xyMcalEsm-Xm1nOgkdGEjIQ/edit#).

**Comment by calvin-lau-sig7** [comment]
## Summary of working group review

### Wider themes raised in feedback

#### Title: pattern does not prove identity, just who has the phone
- Suggestion to rename proposed pattern around ‘confirm phone number’  CJ, SW, JB
- _Note from Calvin: Would this still be findable to service teams?_

#### Can we add better examples of use case JB, TF
- ...or say more about when not to use guidance — types of data, journeys, etc.

#### When the user has none or limited mobile access
- Need for alternative or backup when user has no signal CJ, TF
- ... like email? TF
- Is 15 minutes long enough for rural areas? JB
- Tell user how long message should take to arrive VT, TF

#### Add guidance on text messages
- Include wording of the text message in pattern — RR
- Add text message best practice — TF

#### Security concerns
- Length of code, minimum 4, 6 is better — SW, RR, 
- Should we avoid stating code length in error message — JB
- New code should be requested by user (make this clearer?) — JB, SW
- Better security against brute force attacks — SW
- Exponential backoff / lockout time after repeated incorrect entry — SW
- Security alert to team? — SW
- what happens to different codes with 15 mins? — RR

### Recommendations that will need investigation
- (Lots of concern) Clarify that phone number can only be changed in first instance — RR, TF, MH
- Is this 'cognitively disruptive' to the user by sending them to another a screen? —JB
- Better match with guidance in ‘confirm email address’ info — JB
- Update and link together with related components and patterns, like passwords — JB, RR, TF
- Improve UX copy in the form input — MH
- Revisit copy for ’Not received a link?' screen — VT 

### Recommendations that can be quickly actioned without investigation
- clarify code is numeric — SW
- page title match URL
- add info about automated voice options
- “After saving user’s password” — missing “the” (In section "When creating an account”) — JB
- Inconsistency in code about non-numeric characters — JB
- negative contractions — VT
- plain English generally —VT

**Comment by calvin-lau-sig7** [comment]
I've added the summary of working group recommendations to the "Done whens" in the card, which unblocks this issue.

**Comment by christopherthomasdesign** [comment]
Summary of decisions made with Frankie to address the points raised by the working group: https://docs.google.com/document/d/1Mk_Kpltxpnj4iaxaqB0LpF1_Ja1WcHWyy0ZPxPQFMqg/edit
