### ISSUE TITLE
Standardise process for building new components

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#1536]
## What
Run a workshop to:
- visualise and document all steps of the journey when building a new component
- estimate how long each step takes
- identify which disciplines are involved in each step

## Why
The move to fully remote working and subsequent expansion of the team has shifted the way we build new components. Reflecting on the process to scope, build and publish recent components (notification banner, cookie banner), we agreed to run a workshop to standardise the process.

This will help us with multiple things:
- getting the right roles involved at the right time
- help us plan for our own capacity
- setting expectations with external stakeholders
- provide us with a template to plan future contributions with
- outcome can be translated into documentation or blog post to make our internal processes more visible

## Who needs to know about this
Delivery Manager (facilitator), whole team (input)

## Done when
- [ ] Workshop planned and agenda shared with the team
- [ ] Workshop run
- [ ] Outcomes documented
- [ ] Agreed next steps

**Comment by kellylee-gds** [comment]
## What
Run a series of workshops to:
- visualise and document all steps of the journey when building a new component
- estimate how long each step takes
- identify which disciplines are involved in each step

## Why
The move to fully remote working and subsequent expansion of the team has shifted the way we build new components. Reflecting on the process to scope, build and publish recent components (notification banner, cookie banner), we agreed to run a workshop to standardise the process.

This will help us with multiple things:
- getting the right roles involved at the right time
- help us plan for our own capacity
- setting expectations with external stakeholders
- provide us with a template to plan future contributions with
- outcome can be translated into documentation or blog post to make our internal processes more visible

## Who needs to know about this
Delivery Manager (facilitator), whole team (input)

## Done when
- [x] [Define acceptance criteria](https://github.com/alphagov/govuk-design-system/issues/1558)
- [ ] [Establish how we will meet acceptance criteria](https://github.com/alphagov/govuk-design-system/issues/1559)
- [ ] [Publish this information externally](https://github.com/alphagov/govuk-design-system/issues/1434)
