### ISSUE TITLE
Update backlog entries for ethnic group and protected characteristics

### ISSUE THREAD

**Issue by trang-erskine** [alphagov/govuk-design-system#1545]
## What
Update our backlog entries for ethnic group and protected characteristics patterns.

## Why
To help users understand our decision making

## Who needs to know about this
Content Designer

## Done when
- [x] Drafted rationale behind decisions and approach to building the equality information pattern on community backlog entries
- [x] Reviewed
- [ ] Removed protected characteristics from [backlog page on Design System website](https://design-system.service.gov.uk/community/backlog/)
- [ ] Updated [equality info community backlog entry](https://github.com/alphagov/govuk-design-system-backlog/issues/180) and moved to published column
- [ ] Updated [ethnic group pattern community backlog entry](https://github.com/alphagov/govuk-design-system-backlog/issues/83)
- [ ] [Ethnic group backlog entry closed and decision documented on community backlog](https://github.com/alphagov/govuk-design-system-backlog/issues/83)

**Comment by vanitabarrett** [comment]
Do we want to rename the 'Protected Characteristics' backlog item to match what we call 'Equality Information' in the design system pattern?

**Comment by trang-erskine** [comment]
That sounds sensible. We changed alerts to notification banner. I will do it.
