### ISSUE TITLE
Add MVP Google Analytics to the design system

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-design-system#1610]
## What
This work looks at reinstating Google Tag Manager and Google Analytics on [design-system.service.gov.uk](https://design-system.service.gov.uk/). These used to be used, but were [removed as a temporary solution](https://github.com/alphagov/govuk-design-system/pull/1106) when the ICO guidance on cookie consent was published.

## Why
We want to include GA on tracking back on Design System so that we can better understand how our users are engaging with the website. We can then use this data to learn and improve more about Design System.

## Who needs to know about this
Developers, Performance Analyst, Content Designer

### Design System
- [x] [Review Google Tag Manager set up](https://github.com/alphagov/govuk-design-system/issues/1605)
- [x] [Explore moving to GA4](https://github.com/alphagov/govuk-design-system/issues/1607)
- [x] [Draft an IA plan for Google Analytics and Google Tag Manager](https://github.com/alphagov/govuk-design-system/issues/1608)
- [x] [Draft cookie banner and cookie page content](https://github.com/alphagov/govuk-design-system/issues/1609)
- [x] [Build cookie consent functions in the design system](https://github.com/alphagov/govuk-design-system/issues/1614)
- [x] [Enhance cookie consent functions with versioning system](https://github.com/alphagov/govuk-design-system/issues/1615)
- [x] [Add Google Tag Manager code to the design system](https://github.com/alphagov/govuk-design-system/issues/1616)
- [x] [Create cookies feature branch](https://github.com/alphagov/govuk-design-system/issues/1617)
- [x] [Add cookie banner to the design system](https://github.com/alphagov/govuk-design-system/issues/1618)
- [x] [Add a cookie page](https://github.com/alphagov/govuk-design-system/issues/1620)
- [x] Add a link to the cookies page in the footer
- [x] https://github.com/alphagov/govuk-design-system/pull/1791
- [x] [Review privacy policy and make any additions](https://github.com/alphagov/design-system-team-internal/issues/496)
- [x] https://github.com/alphagov/govuk-design-system/pull/1815
- [x] [Test and deploy Google Tag Manager and cookies on the design system](https://github.com/alphagov/govuk-design-system/issues/1786)
- [x] [Create a manual for Google Tag Manager](https://github.com/alphagov/govuk-design-system/issues/1699)
- [x] Demo of tracking and Google Tag Manager to the team
- [x] We can see analytics in Google Analytics
