### ISSUE TITLE
Implement search analytics tracking

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-design-system#1623]
## What
Add back search analytics tracking which was previously removed as part of https://github.com/alphagov/govuk-design-system/pull/1106

Track any inputs into the top right internal search box on design system website. It should pull the following information into Google Analytics:

Event Category: Site Search
Event Action: dynamically pull through the word entered // have this write when "no result found" is shown to them as well.
Event Label: dynamically pull through the result they select // be blank (or write "no click") if they didn't click anything - this part may not actually be possible. 

Please track the word someone uses - this may well be an abbreviation of the thing they end up clicking on - e.g. "patt" instead of "pattern" as they stop typing mid way through. 

## Why
Search analytics will give us an insight into the search terms users are using and the results they are getting back. This will help us identify gaps.

## Who needs to know about this
Performance Analyst; Developers

## Done when

- [x] Tracking added to Google Tag Manager track what users are searching for on design system website
- [x] Tracking added to track what results users are getting for a given search term https://github.com/alphagov/govuk-design-system/pull/1827
- [x] Test the Personally Identifiable Information (PII) redaction variable is doing it's job and that no PII is coming through into Google Analytics from this 
- [x] Performance Analyst has confirmed events are visible in GA/GTM
- [x] Tracking is live

**Comment by SaraC19** [comment]
PaaS team have this set up (not in GTM but they have the solution for tracking similar site search, if that's helpful).

**Comment by lfdebrux** [comment]
I have a draft PR to add the tracking code to the website, and I can see the events in Google Tag Manager (in preview mode):

<img width="845" alt="Screenshot of event in Google Tag Manager where user has searched for 'He' and clicked 'Headings'" src="https://user-images.githubusercontent.com/503614/129746565-9f52c4aa-c831-4e4f-aee7-a7cd8ab0bae0.png">

<img width="683" alt="Screenshot of event in Google Tag Manager where user has searched for 'Hello' and received no results" src="https://user-images.githubusercontent.com/503614/129746744-e178f1ac-8179-4143-a586-2d8122d001b6.png">

**Comment by lfdebrux** [comment]
@SaraC19 and I looked at hooking up Google Analytics to the data layer events, it turns out the necessary custom events and things were already set up in Google Tag Manager, just paused. By resuming the event we were able to see search events in the preview analytics workspace 🙌

**Comment by lfdebrux** [comment]
I've published [version 35 of the Google Tag Manager workspace](https://tagmanager.google.com/#/versions/accounts/341497290/containers/8094879/versions/35), which un-pauses the tag 'GA - Event - Site Search', so now any `site-search` events will appear in Google Analytics.

**Comment by lfdebrux** [comment]
@SaraC19 confirms search analytics are working, this is done.
