### ISSUE TITLE
Plans comms for 2021 Frontend survey

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-design-system#1657]
## What
We need to decide on the comms related questions for the 2021 Frontend survey - see ## Done when.

## Why
We want to make sure that we're reaching out in the appropriate channels and with the appropriate messaging. 

## Depends on
We might not want to start this work before we've finalised the questions in https://github.com/alphagov/govuk-design-system/issues/1195

## Who needs to know about this
Content writer, user researcher, developer

## Done when

- [x] We’ve done a content review of the survey questions we decided in https://github.com/alphagov/govuk-design-system/issues/1195 
- [x] We’ve agreed and documented what channels to post a link to the survey in, how many times we post it and how long we keep the survey open
- [x] We’ve drafted an introductory blurb for the survey page itself eg. why we’re asking the questions, who are the target participants of the survey, what we’ll do with the data and where we will share will results (https://github.com/alphagov/govuk-design-system/issues/1659), anything else - see 2018 blurb below
- [x] We’ve drafted comms messages for the different channels - [see messages we used in 2018](https://docs.google.com/document/d/1LhlFZiaOs3OU1Wr80-BcQUBZIPm9gvpoBwPHPn10voc/edit)  
- [x] We’ve drafted a thank you message for participants who don’t qualify to fill in the survey
- [ ] We’ve estimated how long it takes to complete the survey and included this information in the comms
- [x] We’ve considered how we will close the survey - do we announce it’s closing, give a final notice before closing it, say what happens next 
- [ ] We've agreed where we will publish the findings (in 2018 we published a blog post and also captured the data on GitHub) and amended https://github.com/alphagov/govuk-design-system/issues/1659 with this information

## Further details
Blurb of the 2018 survey, published on the survey page itself, was 

> We're looking to find out more about which frontend technologies and resources you use to support your project.
> 
> This survey is a re-run of a 2016 survey, we plan to publish an anonymised comparison between this year's results and 2016's results.

**Comment by hannalaakso** [comment]
Comms plan here: https://docs.google.com/document/d/1DiKycAgLAjeab8ThjIlhZkUISQ2qZ8w1tcZ6jVCyIzE/edit?ts=60c35c5f#heading=h.85wz5jtozgbc
