### ISSUE TITLE
Run 2021 Frontend survey

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-design-system#1658]
## What
We've published the survey following the decisions agreed in https://github.com/alphagov/govuk-design-system/issues/1657.

## Why
We're publishing the 2021 Frontend survey to understand what tools, architecture and frameworks are being used across government

## Who needs to know about this
User researcher, developer

## Done when

- [x] We've added the finalised questions into Smart Survey
- [x] We’ve sent out the survey in the channels and using the comms agreed in https://github.com/alphagov/govuk-design-system/issues/1657
- [x] We’ve kept the survey open for the number of days agreed in https://github.com/alphagov/govuk-design-system/issues/1657
- [x] If relevant, we’ve announced the closure of the survey in the relevant channels using the comms agreed in https://github.com/alphagov/govuk-design-system/issues/1657
