### ISSUE TITLE
Prepare the iterated accordion component for release

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-design-system#1706]
## What
The GOV.UK Accessibility team are contributing an iteration to the accordion component which is going to be published in the Design System.

The iterated component  was assessed by the Working Group: [feedback](https://github.com/alphagov/govuk-design-system-backlog/issues/1#issuecomment-839802842)

## Why
The iterated version of the accordion fixes a [current reported accessibility issue](https://design-system.service.gov.uk/accessibility/#non-compliance-with-the-accessibility-regulations).

## Who needs to know about this
- GOV.UK Accessibility team
- From our team: designer, developer, tech writer for release notes, content writer to iterate the guidance 

## Further detail
We will split some of this work with the GOV.UK Accessibility team. However, we’re capturing all the work that needs to be done in this card to maintain visibility of it.

## Acceptance Criteria (GOV.UK Accessibility team)
- [x] Has been reviewed by the working group
- [x] Size of visual touch target meets usability needs (increase size)
- [x] Size of the focus state is consistent with design of other focus states on Design System
- [x] Other small design fixes 
- [x] NVDA issue flagged by accessibility clinic has been resolved - [doc](https://docs.google.com/document/d/1PWDLG_JK4y3Y2XtcCWULYFsD-LfKByRGC1vC6YAwnx8/edit)
- [x] We've considered the behaviour when there is an additional sub heading inside the accordion button ([example](https://design-system.service.gov.uk/components/accordion/with-summary-section/index.html), [Design System guidance for the example](https://design-system.service.gov.uk/components/accordion/#use-clear-labels))
- [x] We've considered the behaviour when there is an interactive element inside the accordion ([example])(http://govuk-frontend-review.herokuapp.com/components/accordion/with-focusable-elements-inside/preview)
- [x] Component taken to GDS Accessibility clinic and findings captured in backlog draft doc
- [x] A PR to add the component to the GOV.UK Frontend code base has been raised
- [x] Behaves as expected with [assistive technologies listed in the Service Manual](https://www.gov.uk/service-manual/technology/testing-with-assistive-technologies)*
- [x] Behaves as expected in [all browsers listed in the Service Manual](https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices) - [plus IE8](https://frontend.design-system.service.gov.uk/supporting-ie8/#support-internet-explorer-8)
- [x] Behaves as expected on [all devices listed in the Service Manual](https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices)
- [x] Works with JavaScript disabled
- [x] Works with CSS disabled
- [x] Works and looks as expected at different breakpoints
- [x] Axe and SiteImprove do not flag any errors/warnings
- [x] Any variants [summary option for accordion] work as expected
- [x] Long/wrapping content in the component works as expected
- [x] Macro options are consistent with other Design System components
- [x] Has a macro which the user can pass data into the component
- [x] Has unit tests which test each macro option, and these tests all pass
- [x] Includes macro documentation
- [x] Common Nunjucks options are available
- [x] Follows GOV.UK Frontend coding conventions
- [x] Follows [code style guide](https://github.com/alphagov/govuk-frontend/tree/main/docs/contributing) (the Design System team can help with this)
- [x] Passes linter and test
- [x] Pull Request (PR) has a well structured commit history including adding [information about the change introduced](https://github.com/alphagov/design-system-team-docs/blob/main/development/commit-messages.md)

## Acceptance Criteria (GOV.UK Design System team)
- [x] [We've completed the developer code review of the PR and raised/discussed any issues with GOV.UK Accessibility team](https://github.com/alphagov/govuk-frontend/issues/2288)
- [x] Cross browser testing completed
- [x] [Accessibility testing completed](https://github.com/alphagov/govuk-frontend/issues/2287)
- [x] [We've done a design review of govuk-frontend PR](https://github.com/alphagov/govuk-frontend/issues/2289)
- [x] We've reviewed the component when text is resized
- [x] [Research any use cases for non phrasing content inside accordion summary line ](https://github.com/alphagov/govuk-frontend/issues/2309)
- [x] [Update docs to explain that accordion summary line can only contain phrasing content](https://github.com/alphagov/govuk-frontend/issues/2310)
- [x] We've reviewed whether we want to make a breaking change in markup by moving the summary inside `govuk-accordion__section-button` and making it a `<span>` 
- [x] https://github.com/alphagov/govuk-frontend/issues/2321
- [x] https://github.com/alphagov/govuk-frontend/issues/2324
- [x] We've asked our team for a quick team review of govuk-frontend PR
- [x] https://github.com/alphagov/govuk-frontend/issues/2322
- [x] https://github.com/alphagov/govuk-frontend/issues/2327
- [x] https://github.com/alphagov/govuk-frontend/issues/2336
- [x] https://github.com/alphagov/govuk-frontend/issues/2354
- [x] https://github.com/alphagov/govuk-frontend/issues/2371
- [x] https://github.com/alphagov/govuk-frontend/issues/2373
- [x] https://github.com/alphagov/govuk-frontend/issues/2287
- [x] [We've taken the component to the accessibility clinic](https://github.com/alphagov/govuk-frontend/issues/2295) (7th Oct) - done, we just need to discuss the feedback with the devs
- [x] We've done a final design review
- [x] We've added automated tests covering any recent changes and done one last review of the the component test coverage (lots of moving parts here so it'd be good to make sure we have decent coverage)
- [x] We've approved govuk-frontend PR
- [x] We've considered whether to document https://github.com/alphagov/govuk-frontend/pull/2257/commits/8d076eebf8f4380a0c8267b876d248881c6b4e39 as a breaking change for HTML users of the accordion
- [x] https://github.com/alphagov/govuk-frontend/issues/2407
- [x] We've agreed how to handle the merging of the PR until 4.0 is ready to go out
- [x] Preview of component in the Design System created
- [x] Guidance updated https://github.com/alphagov/govuk-design-system/issues/1684 
- [x] Release note entry drafted (part of 4.0.0)
- [x] We've prepared for questions that might be raised on support
- [x] Community Backlog entry drafted https://github.com/alphagov/govuk-design-system/issues/1796
- [x] We've made sure that the component PR has a comprehensive description of changes (or links to other places that do) as we'll be linking to it from the release notes
- [x] Iterated component is published in the Design System
- [x] Interviews with contributors https://github.com/alphagov/govuk-design-system/issues/1799
- [x] Run a reflection exercise for the team
- [x] We know how the contributors want to be acknowledged

## Action
- format for cards; acceptance criteria for contributors, acceptance criteria for Design System team
- anything that would take over an hour to resolve should be represented in a story
- every component and pattern we build should have an active decision log during the whole process (we will use this for questions on support and to help us write backlog summary)
- shift conversations from GitHub PR to in person (videos)
- regular playback of decision log / progress of component

**Comment by nnagewad** [comment]
I've attached a link to the Figma file for reference.

https://www.figma.com/file/3yTE9s4EOkvjcqRnqaIzgG/Accordion-Redesign?node-id=166%3A168

**Comment by hannalaakso** [comment]
[Doc to capture accessibility testing and findings](https://docs.google.com/document/d/1aFz6VzaPeCc3u7EkAFkeaMZ34FjdUpFnEZOAE1Tyhb8/edit) for the [Design System backlog](https://github.com/alphagov/govuk-design-system-backlog/issues/1).

**Comment by owenatgov** [comment]
# First pass NVDA/screen reader issue testing results
See below tables for a summary of initial rough testing of how screen readers announce the title of an accordion and the show/hide button.

## With hidden "this section" text and punctuation on show/hide controls (currently version)
| Screen reader | Video | Summary |
| --- | --- | --- |
| VoiceOver | https://user-images.githubusercontent.com/64783893/122055431-86a10500-cde0-11eb-82dc-b54b5c5f21c7.mov | Announces sections as "Writing well for the web, show/hide this section, collapsed/expanded, button". There is a distinct pause between punctuation in the announcement. |
| NVDA | https://user-images.githubusercontent.com/64783893/122055683-c962dd00-cde0-11eb-82bb-37701cb740d1.mov | Announcement of heading/button is split into 3 separate announcements that users must navigate between to hear. All begin with "Clickable heading level 2 button collapsed/expanded" and individually in order read "Writing well for the web", "show/hide" and "this section". |
| JAWS | https://user-images.githubusercontent.com/64783893/122056424-7b020e00-cde1-11eb-83ee-0f492b99a7a2.mov | Announces sections as "Writing well for the web, show/hide this section button collapsed/expanded". There is a distinct pause between punctuation in the announcement. |

## Without hidden "this section" text and punctuation on show/hide controls
| Screen reader | Video | Summary |
| --- | --- | --- |
| VoiceOver | https://user-images.githubusercontent.com/64783893/122057066-20b57d00-cde2-11eb-9152-787d17e3a13c.mov | Announces "Writing well for the web show/hide, collapsed, button". The title alongside the show/hide furniture text sounds like a single title. |
| NVDA | https://user-images.githubusercontent.com/64783893/122057545-aafde100-cde2-11eb-9826-c467e28861e7.mov | Announcement of heading/button is split into 2 separate announcements that users must navigate between to hear. All begin with "Clickable heading level 2 button collapsed/expanded" and individually in order read "Writing well for the web" and "show/hide". |
| JAWS | https://user-images.githubusercontent.com/64783893/122057951-0b8d1e00-cde3-11eb-8a09-1737455a86d2.mov | Announces sections as "Writing well for the web show/hide this section button collapsed/expanded". |

## Initial thoughts
Whilst both instances above don't feel like major barriers to users, I also don't feel that either are acceptable to ship:

- The NVDA issue that prompted this investigation is present in both instances
- Not including a pause creates risk as the context of the accordion title could change with the addition of "show/hide" at the end
- The current hidden text solution breaks the govuk component standard of ensuring our components are translatable by locking the hidden content into a latin-specific punctuation flow

One minor observation on the above is that both JAWS examples, to me, felt the least jarring across all the tests. This may be because the cadence at which JAWS announces already feels unnatural so a lack of punctuation feels less impactful.

The instance without the hidden text feels like the lesser of 2 evils as the hidden text instance seems to be adding a lot of upkeep and markup with little value in return but it still introduces problems. The next step for me will be to interrogate the markup and come up with some alternative proposals.

**Comment by owenatgov** [comment]
# Update on NVDA investigation
I think I've found a solution 🎉

After playing around with the markup I made the discovery that NVDA treats any form of line break as a separate announceable landmark and will therefore announce it separately. This line break can come from both the semantics via `br` tags or 2 block-level tags, or via CSS using `display: block` or ` display: table`. In this case it was the span containing the show/hide button being styled using `display: block`.

The solution in this case was to replace `block` with `inline` and add a pseudo element set to `display: block`. This forces a line break but bypasses NVDA's line break interpreter, thus causing the accordion title and the show/hide to be read as a single sentence. I've created a [draft PR](https://github.com/alphagov/govuk_publishing_components/pull/2142) in the govuk components gem to show my work. This is failing tests because it includes a change to how the translation functionality is expected to work so I'm not gonna worry about this right now.

Going forward, following input from @hannalaakso on my previous investigation, I've removed the punctuation from the hidden text to see how it plays out on screen readers. Results of investigation in table below:

| Screen reader | Video | Summary |
| --- | --- | --- |
| VoiceOver | https://user-images.githubusercontent.com/64783893/122241016-21214700-ceba-11eb-99e4-45af982b2d31.mov | Announces "Accordion title show this section" as a single flowing sentence. Text box looks a little weird as there is no space between the title and the button text: "Accordion titleShow this section" |
| NVDA | https://user-images.githubusercontent.com/64783893/122241317-5ded3e00-ceba-11eb-9660-313c735551b2.mov | Announces "Accordion title show this section" as a single flowing sentence. Text box includes unusual spacing and capitalisation: "Accordion title  Show This section" |
| JAWS | https://user-images.githubusercontent.com/64783893/122241773-b7556d00-ceba-11eb-806e-8704ead2021e.mov | Announces "Accordion title show this section" as a single flowing sentence |

I feel a little apprehensive about the lack of a pause/space between the title and the button text, especially how it manifests on VO, however I think as a broad solution this solves our problem. Considering we can't aria-hide the show button to account for voice control users, this may be the best we can do with the given UI.

Keen to hear what the team thinks.

**Comment by owenatgov** [comment]
## Some further findings on screen reader accordion behaviour

- The only way to apply a space for the VoiceOver text tooltip is to explicitly declare a span with a space in with a class of `govuk-visually-hidden`. Just setting a space in the content and playing around with markup doesn't have an impact.
- Punctuation behaves very sporadically across screen readers. NVDA 2020 for example will produce a very long (approx 2 seconds) pause when it reads a period. This, along with [research on the subject from Deque](https://www.deque.com/blog/dont-screen-readers-read-whats-screen-part-1-punctuation-typographic-symbols/) suggest to me that punctuation isn't a viable solution for this instance.

Following the above discoveries and a discussion with @chris-gds earlier today, I've agreed with him the following next steps:

1. We take the accordion in its current state to the accessibility clinic and get Anika's view on the lack of punctuation. Notably, she didn't take issue with when NVDA split the button into separate blocks. It'll be good regardless to get some detailed rationale as to why this could be acceptable and how theoretically impactful the lack of pausing is.
2. We treat accordion title and the "show/hide this section" phrase as separate phrases for translation purposes. The title followed by "show/hide this section" doesn't need to be one sentence. This is backed up by the accordion version with subtitles where screen readers will read: "[Accordion title] [accordion subtitle] Show/Hide this section". There are likely languages that wouldn't read these phrases in this order but we don't need to be a localisation team at this stage.

Chris, I'll leave it to you to report back on the accessibility clinic as I'll be otherwise occupied tomorrow with GOV.UK 2nd line responsibilities.

**Comment by chris-gds** [comment]
## Update on attending the a11y clinic 

The Draft link used can be found here:
https://govuk-frontend-pr-2257.herokuapp.com/components/accordion

My takeaways are below:

- We need to test with users (ideally).
- A question that is difficult to answer is “does the user’s expectation marry up with the behaviour of this pattern.”   
It's difficult to tell if a user would clearly understand that the element is a button, despite having the additional affordance of the icon.  

It's worth noting that there was some feedback on from a user asked to extract content from the covid landing page. It's not clear if an accordion, as as concept, is clear to users or if additional work is needed to explain what this element is in some way.

--- 

@owenatgov 
> We take the accordion in its current state to the accessibility clinic and get Anika’s view on the lack of punctuation.

- The group didn’t think lack of punctuation was an issue.  Similar comments were made about how different screen readers and the different combinations of user settings + browsers alter speed and pauses.

> Notably, she didn’t take issue with when NVDA split the button into separate blocks. It’ll be good regardless to get some detailed rationale as to why this could be acceptable and how theoretically impactful the lack of pausing is.

- The rationale was NVDA has been seen to treat headings / buttons in a similar fashion elsewhere on the web.  There would be a degree of expectation that the user might be used to this.

---

### Other questions: 
- Firefox >  Zoom text only > 300% > the icon doesn't scale relatively

Within the [GOV.UK / Gem iteration of the Accordion](https://components.publishing.service.gov.uk/component-guide/accordion) relative values are used so this scales proportionally.  This has currently been removed for this contribution as this relative values are not present (to align for consistency).

It was queried if this was an issue.  This was noted as _not_ a WCAG fail as this mentions text and falls under the realm of best practice.

- There was positive feedback in consistency - for the most part navigating with various screen readers in different ways (eg via keyboard tab, keyboard navigating and via headings) resulted in a consistent experience.

- There was an issue noted with Search (Google) indexing picking up the “show this section” copy within results.  It would be good to understand this issue further so a fix can be included.

- When highlighting IE8 the suggested solution of hiding the icon - it was noted this was not ideal.  Action to include a fallback for IE8, multiple solutions exist.  This is because without this icon the same WCAG failure is present, it’s not clear this is a button that can be interacted with.  Will present different solutions to Design to confirm.

- Testing with different combinations of Firefox + User updated colour schemes  - the experience was worse. The user can’t see the focus states, this needs to be reviewed.

Deeper testing on-going.

**Comment by chris-gds** [comment]
> Firefox > Zoom text only > 300% > the icon doesn't scale relatively

After consideration, [relative values have been used in this context to resolve this issue](https://github.com/alphagov/govuk-frontend/pull/2257/commits/e03d9959ded243446dcb135f446e830d267e554c)

**Comment by calvin-lau-sig7** [comment]
@hannalaakso  I had a go at spotting some themes in the epic, feel free to use these or add more. I was going to use these to organise my thoughts documenting all this work, but it might be useful to break down the list of acceptance criteria the top.

**Themes**
- Context of UI elements for screen reader users (e.g. what the ‘show all sections’ button does, overall awareness of how accordions open and close)
- Relationship between buttons and accordion contents
- Consistency of focus state across browsers and devices (e.g. Android NVDA looks incorrect, Firefox high contrast mode, content has no padding)
- Possibility too much content will go into the summary and buttons
