### ISSUE TITLE
Host Design System Day

### ISSUE THREAD

**Issue by trang-erskine** [alphagov/govuk-design-system#1751]
## What

As part of our birthday celebration, the Design System is hosting a Design System Day. 

## Why

- Collaborate and share knowledge about Design Systems with other like minded people
- Gain insight into what's top of mind from our users. 
- Increase visibility of what the Design System team is doing
- Create interest in contribution and co-creation of components & patterns
- Increase diversity and inclusiveness of the people we tend to interact with
- Get people to sign up to our mailing list
- Celebrate the Design System team’s work - announced on our birthday
- Create a focal point in the year that re-energises people around design systems

## Who needs to know about this
Community,  Design System team 

## Done when

- [x] Arrange volunteer https://github.com/alphagov/govuk-design-system/issues/1765
- [x] Arrange keynote speaker https://github.com/alphagov/govuk-design-system/issues/1764
- [x] Plan and run workshop https://github.com/alphagov/govuk-design-system/issues/1763
- [x] Plan facilitation and organise facilitators for the event https://github.com/alphagov/govuk-design-system/issues/1762
- [x] Create grid, docs and meeting invites https://github.com/alphagov/govuk-design-system/issues/1761
- [x] Create Code of Conduct https://github.com/alphagov/govuk-design-system/issues/1760 
- [x] Create attendee pack https://github.com/alphagov/govuk-design-system/issues/1759
- [x] Manage pitching channel https://github.com/alphagov/govuk-design-system/issues/1758
- [x] Agreed pitches for breakout sessions [update card] https://github.com/alphagov/govuk-design-system/issues/1757
- [x] User research on workshops https://github.com/alphagov/govuk-design-system/issues/1756
- [x] Create comms plan https://github.com/alphagov/govuk-design-system/issues/1754
- [x] Practice run booked
- [x] [Run a retro](https://github.com/alphagov/govuk-design-system/issues/1782)
- [ ] [Blog about it](https://github.com/alphagov/govuk-design-system/issues/1783)
