### ISSUE TITLE
Understand what Frontend technology and tools users are using

### ISSUE THREAD

**Issue by trang-erskine** [alphagov/govuk-design-system#1752]
Body of epic to be completed after a kick off session

**Comment by kellylee-gds** [comment]
Previous body of issue:

## What

We want to know what Frontend technology and tools users are using. We run an annual Frontend Survey to find out about this information. 

## Why

## Who needs to know about this
Developers, Rosie

## Done when

- [x] Plan 2021 Frontend survey https://github.com/alphagov/govuk-design-system/issues/1195
- [x] Plans comms for 2021 Frontend survey https://github.com/alphagov/govuk-design-system/issues/1657
- [x] Run 2021 Frontend survey https://github.com/alphagov/govuk-design-system/issues/1658
- [ ] Analysis responses from Frontend survey
- [ ] Publish findings from 2021 Frontend survey https://github.com/alphagov/govuk-design-system/issues/1659
