### ISSUE TITLE
Enough analytics to pass live assessment

### ISSUE THREAD

**Issue by trang-erskine** [alphagov/govuk-design-system#1767]
## What

Do enough analytics to pass the live assessment

## Why
There's a backlog of analytics we need to do on the team. We plan to narrow the scope to doing enough analytics to pass the live assessment before we tackle some of the other areas. 

Part of this work will also be looking at some of the analytics work we already started with the implementation of GA, reviewing support data. 

## Who needs to know about this
PA, PM, CD, UR

## Done when
- [x] https://github.com/alphagov/govuk-design-system/issues/1820
- [x] [Get GA live on the site](https://github.com/alphagov/govuk-design-system/issues/1610) - Epic
- [x] [Set a date for live assessment](https://github.com/alphagov/govuk-design-system/issues/1837)
- [x] [Set up search tracking on the design system website](https://github.com/alphagov/govuk-design-system/issues/1623)
- [x] [Refine the performance framework ](https://github.com/alphagov/govuk-design-system/issues/1839)
- [x] [Set up dashboard to monitor internal site search ](https://github.com/alphagov/govuk-design-system/issues/1838)
- [x] [Set up dashboard to monitor email performance](https://github.com/alphagov/govuk-design-system/issues/1840)
- [x] [Set up heatmap dashboard for the design system website homepage ](https://github.com/alphagov/govuk-design-system/issues/1841)
- [x] [Analyse performance of the website and identity some key journeys](https://github.com/alphagov/govuk-design-system/issues/1842)
- [x] [Create a slide deck for live assessment](https://github.com/alphagov/govuk-design-system/issues/1844)
- [x] Do the live assessment

**Comment by EoinShaughnessy** [comment]
Should we document how we measure the email signup journey?
