### ISSUE TITLE
Review and draft a new external roadmap

### ISSUE THREAD

**Issue by calvin-lau-sig7** [alphagov/govuk-design-system#1824]
## What

The current [Github project board version](https://github.com/orgs/alphagov/projects/5?fullscreen=true) of the Design System roadmap is underused.

We've decided to stop showing it in its current form and find a way to show it as a page on the Design System website. We'd also like to find and show the level of detail that's useful to users.

## Why

The current form is unclear and we do not think anyone looks at it.

## Who needs to know about this

Product, delivery, tech lead, designer, content designer, PA, dev

## Done when

- [x] Level of detail decided
- [x] Prototype a few different version
- [x] Test with a few people
- [x] New template agreed
- [x] Content drafted
- [x] Reviewed with team

**Comment by trang-erskine** [comment]
Here's something I wrote back in June when I was thinking about this. 

--- 

## Roadmap 

The GOV.UK Design System roadmap shows the things we’re working on and when we hope to have them ready for you to use.

The roadmap is a guide to what we have planned, but some things might change. You can go to our Github repository for more details on our plans and day to day activities. 

You can contact us if you have any questions about the roadmap or suggestions for new features.

### July to December 2021

- Host Design System Day 2021 - 22 July 2021
- Publish revised accordion design contributed by GOV.UK to address an accessibility issue 
- Publish the proposal for future changes to browser support and Javascript configuration. This will enable the us to build and support more complex components
- Implement Google Analytics on Design System website to help us understand how users are using the website. 
- Publish ‘Hide this page’ component
- Implement accessibility improvements introduced in WCAG 2.2
- Collaborate with the community to work on patterns and components

### January to June 2022

- Evaluate usage of ‘experimental’ label
- Implementing the changes for browser and Javascript configuration
- Reprioritise patterns and component with the community
- Collaborate with the community to work on patterns and components

**Comment by trang-erskine** [comment]
Other GaaP product roadmaps
https://www.payments.service.gov.uk/roadmap/ 
https://github.com/alphagov/paas-roadmap/projects/1?fullscreen=true 
https://www.notifications.service.gov.uk/features/roadmap 
https://www.gov.uk/roadmap

**Comment by trang-erskine** [comment]
Drafted a few different versions https://docs.google.com/document/d/1G8Jn7iv7nDeshbKwc1DVD_qpimzU6ynoufeGSd2i0m0/edit?pli=1#
