### ISSUE TITLE
Update GTM tracking to make heatmap dashboard useful

### ISSUE THREAD

**Issue by SaraC19** [alphagov/govuk-design-system#1852]
## What
In order to create a heatmap on the home page, some tracking would be useful to get live:

- Top navigation bar clicks
- 'Get Started' button clicks
- 404 hits (adding this in because it's a quick win)

## Why
So we can know for sure which part of the page users are clicking. There are multiple links of the same nature on the home page, currently it's not possible to tell exactly which version of the link someone has clicked without this tracking. 

## Who needs to know about this
Dev, PA

## Done when

- [x] Tags have been created / updated within Google Tag Manager
- [x] Dev has reviewed them
- [x] Dev has published

**Comment by SaraC19** [comment]
Ready for dev review / publish whenever they have time. 

- Fixed "GA - Event - 404 trigger". Added "DOM - h1" variable which just creates a variable that listens for the h1 tag. Then added this to the trigger to listen for "Page not found" in the h1. 
- Fixed "GA - Event - Get Started Click". Changed the trigger to fire when someone clicks the relevant CSS class & Click Text. 
- Fixed "Top Navigation Bar" trigger to fire when the relevant CSS class & Click Text is clicked.

**Comment by vanitabarrett** [comment]
Reviewed the changes in Google Tag Manager.

✅ 404
❓ Get Started link click. Would we be able to tweak the trigger to make the Click Classes less specific so that the tracking continues to work even if we change the styling of the link? We could also add an additional check that the Click URL matches `/get-started`.
❓ Top Navigation Bar link click. This tracking won't track any events on mobile, as the navigation works differently on mobile devices. Do we want to expand the tracking or add a new event for mobile navigation links? Also, the current trigger has a regex which looks at the link text - this will mean that if we add a new link to the top navigation bar, it won't be automatically tracked until we update the regex. Do we feel the regex is needed?

**Comment by SaraC19** [comment]
For both Get Started link click and top nav bar: It didn't look like there's another thing it could be hooked onto, but I'd definitely like them both to be more generic so we don't have to keep updating them. Do you have any suggestions on what they could be, I'm not sure what part might change when we change styling. Happy to have a chat and point at the website with you if that helps in preview mode.
