### ISSUE TITLE
Iterate the community backlog IA

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#1878]
## What
Iterate the IA (Information Architecture) of the [community backlog](https://github.com/alphagov/govuk-design-system-backlog/projects/1) to be clearer about what stage a contribution is at.

## Why
We know from speaking users that the community backlog is difficult to use, and it's unclear where in the contribution process a component or pattern is.

## Who needs to know about this
Designers, Delivery Manager, Content Designer, Community Manager

## Done when
- [ ] Prototyped different IAs
- [ ] Reviewed
- [ ] Understood how it impacts current processes such as contribution and daily support
- [ ] Updated any relevant documentation
- [ ] Communicate changes to the community

**Comment by christopherthomasdesign** [comment]
Been prototyping some ideas here: https://github.com/alphagov/govuk-design-system/tree/backlog-iteration

**Comment by christopherthomasdesign** [comment]
Not 100% sure this is the right place to put this, BUT

I had a chat with Jon Rowe, an interaction designer who works on the [HMRC Design Patterns](https://design.tax.service.gov.uk/hmrc-design-patterns/) team. We talked about how the HMRC community backlog works, how they've iterated it over time, and how it relates to the backlog on the GOV.UK Design System.

Highlights:
* the team started off by copying exactly what's in the GOV.UK Design System (the backlog, the contribution process etc).
* their 'real' process for contributing is less formal than the guidance on their website suggests – it usually starts with someone sending a Slack message or email to Jon
* this was to try and reduce the initial barrier to entry on making a contribution
* they produce a slide deck with the contributor which gathers evidence that the proposal is useful and unique, meets user needs etc.
* then there's a meeting to decide whether something should be in the backlog
* the team's biggest bottlenecks tend to be a lack of resource (especially content designers) and the stage where something has been approved in concept but there's lots of developer time needed to finish it off
* there's a stage in their backlog called 'upstreamed', where possible contributions to the GOV.UK Design System are highlighted – this hasn't been done in a while though

**Comment by trang-erskine** [comment]
I also had a think about what we want to show on the community backlog project board, but more in terms of what's still needed to get to the next stage 

**Stage 1:  Needs evidence (useful and unique)** (unprioritised)
It still needs evidence that at least 3 services have used it and it was successful. 
It needs evidence that it’s unique

**Stage 2: Needs development** (prioritised by xxxxxxx)
It needs contributors to help develop it further. 
It needs contribution of the code, guidance, examples, research, different use cases and scenarios
(If contributors drop it, it goes back here) 
 
**Stage 3: Contributors are working on it.** 
Contributor(s) are actively working on it. 
(Probably need to share that someone on the DS team is working with them)

**Stage 4: Needs publication**
Waiting for Design System team prioritisation and capacity to review, modify to fit in Frontend framework (something to indicate it isn't just code review), make sure it's consistent etc. 
Check the roadmap to see what the team is actively working on and has prioritised

**Comment by christopherthomasdesign** [comment]
Working in this doc: https://docs.google.com/document/d/1eS7fx9BhpFAptUPRizWz81g4lU31EQZ0QAwBlrKET_g/edit#

**Comment by hazalarpalikli** [comment]
We conducted quick reviews with 4 designers on the search box. Notes are here if you'd like to review.:https://docs.google.com/document/d/1xtFHv4wAkKtnz5dL1cQAerhOwiMt0KqqnFGwWNe83Xc/edit?tab=t.0.

Feedback revealed concerns about the information architecture (IA) not aligning with their mental models. While they adapted to the Design System's IA, it doesn't reflect how they would naturally categorize content.
