### ISSUE TITLE
Add analytics tracking for v4.0.0 comms and documentation

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-design-system#1890]
## What
We want to add analytics tracking to some of our v4.0.0 comms and documentation so we understand where users are reading about the release, how much traffic the documentation is getting and how people are getting there.

## Who needs to know about this
Performance Analyst; Developers

## Done when

- [x] Performance Analyst has identified tracking opportunities (working with developer and tech writer)
- [x] Tracking added within Google Tag Manager
- [x] Any code changes made to support the new tracking, where applicable
- [x] Tracking has been published and events are showing up in Google Analytics

**Comment by SaraC19** [comment]
Had a chat with @vanitabarrett  and outlined what the touch points are when a release is made:
- Email list 
- Slack announcement in various channels
- Points to this (but V4) - release notes on GitHub
https://github.com/alphagov/govuk-frontend/releases/tag/v3.14.0
- Change log file - https://github.com/alphagov/govuk-frontend - other version of release notes
- Post a summary in the backlog for the accordion on the updates made 
- Update "What's New" on the website home page
- Installing instructions:
https://frontend.design-system.service.gov.uk/install-using-precompiled-files/#what-you-cannot-do-after-installing

Next steps are for me to figure out what I can get data for in GitHub and also to keep a note of baseline metrics on the Frontend website in Logit so we can get a feel for any change in traffic on the day. 

Nothing new needs to be set up, so we can close the ticket. 

Thank you @vanitabarrett !
