### ISSUE TITLE
Restructure 'Community' section of the website to better tell users how they can contribute, join in and get help

### ISSUE THREAD

**Issue by trang-erskine** [alphagov/govuk-design-system#1935]
## What 
The content feels like a mish-mash of lots of different things. 
Divide the pages under /community/ into 3 subsection 'themes' (which is the term used in GitHub)

Might involve renaming existing pages to reduce repetition and fit with subsections names.

## Why
It's difficult for users to know how the join the community or find the other information that's sitting in the community section.

## Who needs to know about this
Community Manager, Content Designer, Designer, UR, PA, 

## Done when
- [ ] Decide on structure — subsection 'theme' names, and pages that fall within each
- [ ] Propose any new page titles needed
- [ ] Review with team (show and tell)
- [ ] Implement themes into /community/ section and rename page titles

**Comment by trang-erskine** [comment]
The October GA analysis recommends, look into including more signposting to the community section within the site. Potentially on components, patterns or styles hub pages.

- 10% of users visit the community section
- Most users get here via utilising internal navigation (ie top nav bar) 
- Popularity - community hub (41%), backlog (27%) and resources and tools (13%)

**Comment by calvin-lau-sig7** [comment]
Update on this and a few related works:
- new top-level page for /community/ to be created as part of https://github.com/alphagov/govuk-design-system/issues/2132, which should give this section a clearer purpose
- we'll sort subpages in this section into 3 'themes' as part of https://github.com/alphagov/govuk-design-system/issues/1935
- backlog page will be improved to be more community and contributor-focused as part of https://github.com/alphagov/govuk-design-system/issues/2310 
- leftover pages (resources & tools, roadmap, blog posts) can be examined later, perhaps in a future tech docs/resources reorg

**Comment by calvin-lau-sig7** [comment]
Possible way to split it (actual titles need to be written):

### What we’re working on
Backlog (to be renamed in #2310)
Roadmap

### Ways to get involved
Propose a content change using GitHub
Propose a component or pattern
Develop a component or pattern

### How we work
Contribution criteria
Design System working group

### Resources
Resources and tools
Blog posts, videos and podcasts
