### ISSUE TITLE
Evaluate Github metrics and what insights we could gather

### ISSUE THREAD

**Issue by trang-erskine** [alphagov/govuk-design-system#1936]
TBC when we kickoff the epic

We need to define what we mean by this epic. It could be

- metrics on contributions and contributors through comments and pull requests
- usage of components and patterns, analysing Github repo for 'markers' 
- internal team usage of labels, tickets
- internal team workflow

Done when: 

- [x] https://github.com/alphagov/govuk-design-system/issues/1845
- [x] https://github.com/alphagov/govuk-design-system/issues/2027
- [x] https://github.com/alphagov/design-system-team-internal/issues/571
- [x] https://github.com/alphagov/design-system-team-internal/issues/570

**Comment by stevenjmesser** [comment]
I've come across [Augur](https://chaoss.github.io/augur/). It looks at organisations and repos on Github to try and calculate some community health metrics for open-source software projects. There's some useful thinking around those metrics here: https://chaoss.community/kb-metrics-and-metrics-models/

**Comment by trang-erskine** [comment]
Close for now. Reopen if we still want to do this.
