### ISSUE TITLE
Finalise Exit this Page component guidance

### ISSUE THREAD

**Issue by christopherthomasdesign** [alphagov/govuk-design-system#2067]
## What

Write guidance for the Hide this page component before it is published. Part of https://github.com/alphagov/govuk-design-system/issues/1755.

There is an existing branch we can use when ready to publish: https://github.com/alphagov/govuk-design-system/tree/hide-this-page-component

## Why

To explain how to use the component appropriately, safely and effectively.

## Who needs to work on this

Content designer with input from designer, accessibility specialist, user researcher, developer

## Who needs to review this

Designer, accessibility specialist, user researcher, developer

## Done when

**First draft**
```[tasklist]
- [x] First draft written
- [x] Decision made on structure (i.e. component vs component + pattern)
- [x] Decision made on component features guidance to include
- [x] Decision made on other online safety guidance to include
- [x] Added research, known issues and next steps
- [x] Gathered feedback from team
- [x] [Reviewed as part of community consultation](https://github.com/alphagov/govuk-design-system/issues/2679)
```
**Final iterations for mvp**
```[tasklist]
- [x] Add information about how the component is published as experimental, which aspects are not tested, and where teams will need to do research
- [x] Add content to explain this implementation has been researched and tested with users with lived experience of domestic abuse and built in response to the needs identified with this user group, and not other use cases
- [x] Add encouragement for teams to share feedback on how they have implemented on static pages that aren't part of a transactional service to 'Known issues and gaps' section
- [x] Add details of feedback routes to the guidance so it's easy for teams to share with us
- [ ] https://github.com/alphagov/govuk-design-system/issues/2677
- [x] Add information for "Accessibility features and considerations" heading
```

**Comment by calvin-lau-sig7** [comment]
Added proposed edits as comments in https://github.com/alphagov/govuk-design-system/pull/2721/files to cover all the final iterations needed. Though there's a couple of questions in there.
