### ISSUE TITLE
Improve how the team reviews issues and pull requests

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#2094]
## Background
We currently use an asynchronous method to review pull requests (PRs) and issues raised on the following repos;

[gov uk-design-system](https://github.com/alphagov/govuk-design-system)
[govuk-frontend](https://github.com/alphagov/govuk-frontend)
[govuk-prototype-kit](https://github.com/alphagov/govuk-prototype-kit)
[govuk-design-system-backlog](https://github.com/alphagov/govuk-design-system-backlog) (new comments also reviewed)

We actively encourage users to raise issues and pull requests (PRs) to improve our products. Design System team members also raise issues and PRs in these repositories to improve the products. 

All new PRs are added to the Kanban board by the team member on support that day. In the next stand up, we ask who can review the PR then track progress like we do with all other pieces of work on the Kanban board. More than one person can review a PR if we feel the review needs multiple disciplines.

The team member who is on support each day also triages new issues that are raised by users. Any issues that are raised by team members should be triaged by the person who raised it. The issue is firstly checked to see if it meets the high priority criteria (if so, should be circulated with the team and added to the current backlog). 

We also estimate the effort required to work on the issue (will it take hours, days or weeks to resolve).

Once all appropriate labels are added, we remove the "awaiting triage" label.

## What
We think this process can be improved.

## Why
- issues are being missed resulting in a backlog of issues waiting to be triaged
- comments on the community backlog are easily missed (and we do not have a process for what to do next with comments)
- we pull issues into the sprint board that do not meet high priority criteria
- it's difficult to estimate the time effort involved in something if you don't fully understand the context / isn't your area of expertise

## Who needs to work on this
Kelly (leading)

## Who needs to review this
Those on support rota

## Done when
- [ ] We understand the user need for triaging issues and pull requests
- [ ] We have understood all pain points with the current process
- [ ] We have journey mapped how to contribute a minor improvement to the Design System or Frontend
- [ ] We have generated ideas of how it can be improved
- [ ] We have created a new process
- [ ] We have agreed measurements of success
