### ISSUE TITLE
Encourage users to take part in the community

### ISSUE THREAD

**Issue by calvin-lau-sig7** [alphagov/govuk-design-system#2132]
## What

Create a landing page to tell users about our community activities, which could include:
- co-design workshops for Maps and Task list
- Friday catch-up call
- cross-gov Slack channels

## Why

We do not have a place to direct people who are interested in taking part. At the moment we rely on 'push' messaging over emails and Slack.

## Epic Lead
Calvin

## Who needs to work on this

Community Designer, Content Designer, Interaction Designer

## Who needs to review this

Contribution squad

## Done when

- [x] https://github.com/alphagov/govuk-design-system/issues/2349 will create a new top-level page for /community/, which should give this section a clearer purpose
- [x] https://github.com/alphagov/govuk-design-system/issues/1935 will divide subpages under /community/ into 3 'themes'

## Related work
- [x] https://github.com/alphagov/govuk-design-system/issues/2310 will improve the 'Backlog' subpage to be more community and contributor-focused as part of
- [x] leftover pages (resources & tools, roadmap, blog posts) can be examined later, perhaps in a future tech docs/resources reorg

**Comment by kellylee-gds** [comment]
Hey @calvin-lau-sig7 and @ImranH-GDS. I know you're having conversations about this work. When you've agreed scope, could you update this epic card and write stories for the subsequent work. Can you also check this epic against this #1935 as they look quite similar. Thanks!

**Comment by calvin-lau-sig7** [comment]
Some relevant decisions from 16 August workshop ([Mural board](https://app.mural.co/invitation/mural/gaap0347/1659023424168?sender=u0b59bf53328f6bc22ae10431&key=74effb79-3421-48f8-8016-24ad1854e7f6):
- new page should be new top-level page in [/community/](https://design-system.service.gov.uk/community/)
- will involve sorting subpages into new 'themes', which will be part of https://github.com/alphagov/govuk-design-system/issues/1935
- there will be some relatively 'orphaned' pages in the section, particularly around resource-related pages, which we can look at separately

**Comment by calvin-lau-sig7** [comment]
Picking up again for this sprint.

I'll work on new content outline/draft [based on the Mural](https://app.mural.co/invitation/mural/gaap0347/1659023424168?sender=u0b59bf53328f6bc22ae10431&key=74effb79-3421-48f8-8016-24ad1854e7f6), updating the [existing content doc](https://docs.google.com/document/d/1ACuV3jtGhfxkTaRtjdAQuPLYO1wiv0CCWYjiyPp6-p8/edit?usp=sharing).

Will then loop in designers to find best way to present this information.

**Comment by calvin-lau-sig7** [comment]
Hi @Musashi6246, not entirely clear on your question but I'll do my best to give an answer.

This page is for anyone that's interested in working with us to improve the [GOV.UK Design System](https://design-system.service.gov.uk/). This could mean things like sharing their user research, helping design a component/pattern or contributing code.

The Design System is a resource to help teams follow the [Service Manual](https://www.gov.uk/service-manual) to meet the [Service Standard](https://www.gov.uk/service-manual/service-standard). I would not expect any of these pages to be linked on any public-facing services, as it's not usually relevant to their user need.

Hope this helps fill you in on things.
