### ISSUE TITLE
Design System Day 2022

### ISSUE THREAD

**Issue by trang-erskine** [alphagov/govuk-design-system#2151]
## What

As part of our birthday celebration, the Design System is hosting a Design System Day

## Why

- Collaborate and share knowledge about Design Systems with other like minded people
- Gain insight into what's top of mind from our users. 
- Increase visibility of what the Design System team is doing
- Create interest in contribution and co-creation of components & patterns
- Increase diversity and inclusiveness of the people we tend to interact with
- Get people to sign up to our mailing list
- Celebrate the Design System team’s work - announced on our birthday
- Create a focal point in the year that re-energises people around design systems

[trello board with decisions](https://trello.com/b/GQEPg1bP/design-system-day-2022-planning)

## Who needs to know about this
Community,  Design System team 

```[tasklist]
## Done when
- [x] #2164
- [x] #2165 
- [x] #2166 
- [x] #2167 
- [x] #2168 
- [x] https://github.com/alphagov/govuk-design-system/issues/2293
- [x] https://github.com/alphagov/govuk-design-system/issues/2292
- [x] https://github.com/alphagov/govuk-design-system/issues/2217
- [x] https://github.com/alphagov/govuk-design-system/issues/2218
- [x] https://github.com/alphagov/govuk-design-system/issues/2334
- [x] #2169 
- [x] https://github.com/alphagov/govuk-design-system/issues/2215
- [x] #2170
- [x] #2297
- [x] https://github.com/alphagov/design-system-team-internal/issues/615
- [x] https://github.com/alphagov/design-system-team-internal/issues/625
- [x] https://github.com/alphagov/design-system-team-internal/issues/626
- [x] https://github.com/alphagov/design-system-team-internal/issues/635
- [x] https://github.com/alphagov/design-system-team-internal/issues/636
- [x] https://github.com/alphagov/govuk-design-system/issues/2216
- [x] https://github.com/alphagov/design-system-team-internal/issues/621
- [x] https://github.com/alphagov/design-system-team-internal/issues/624
- [x] https://github.com/alphagov/design-system-team-internal/issues/620
- [x] https://github.com/alphagov/design-system-team-internal/issues/622
- [x] https://github.com/alphagov/design-system-team-internal/issues/623
- [ ] https://github.com/alphagov/design-system-team-internal/issues/643
- [ ] https://github.com/alphagov/design-system-team-internal/issues/644
- [ ] https://github.com/alphagov/design-system-team-internal/issues/645
- [ ] https://github.com/alphagov/design-system-team-internal/issues/646
- [ ] https://github.com/alphagov/design-system-team-internal/issues/647
- [ ] https://github.com/alphagov/design-system-team-internal/issues/648

**Comment by trang-erskine** [comment]
@ImranH-GDS I've copied over the [epic](https://github.com/alphagov/govuk-design-system/issues/1751) from last year, you can edit as necessary.

**Comment by 36degrees** [comment]
This is done!
