### ISSUE TITLE
Make changes for WCAG 2.2 

### ISSUE THREAD

**Issue by trang-erskine** [alphagov/govuk-design-system#2163]
## Epic lead
David

## Done when

- [ ] Mapping our components to WCAG 2.2 criteria
- [ ] Identify gaps where our components don't meet the updated WCAG 2.2 criteria
- [ ] Consider whether we want to publish a new accessibility statement about the gaps (after publication)
- [ ] Scope and plan the investigation / implementation
- [ ] ...(list the gaps)
- [ ] Blog about the changes

**Comment by kellylee-gds** [comment]
Closing this as David has created multiple epics for the WCAG 2.2 work
