### ISSUE TITLE
Get summary card ready for 2nd working group review

### ISSUE THREAD

**Issue by christopherthomasdesign** [alphagov/govuk-design-system#2214]
## What

After an [initial exploration](https://github.com/alphagov/design-system-team-internal/issues/596) we've decided to pick up summary card. This means taking on the working group's feedback from the first review, and making a more developed proposal.
 
## Why

It's the last outstanding major contribution in the pipeline before we start picking up some new things.

## Who needs to work on this

Most roles in the team

## Who needs to review this

N/A

## Further detail

Useful links:
* [The original proposal](https://github.com/alphagov/govuk-design-system-backlog/issues/210#issue-583652749)
* [Tim's summary of the working group feedback](https://github.com/alphagov/govuk-design-system-backlog/issues/210#issuecomment-716691624)
* [The new summary card branch in Frontend](https://github.com/alphagov/govuk-frontend/tree/summary-card)

## Done when

- [x] Decide how to address working group feedback
- [x] [Draft guidance for summary card as part of existing summary list component](https://github.com/alphagov/govuk-design-system/issues/2224)
- [x] https://github.com/alphagov/govuk-design-system/issues/2221
- [x] Make prototype Design System page to share with working group
- [x] Make proposal to share with working group
