### ISSUE TITLE
Review design system components following finalised update to font scale

### ISSUE THREAD

**Issue by owenatgov** [alphagov/govuk-design-system#2299]
## What
Review all govuk-frontend components against the updated font scale, done as part of https://github.com/alphagov/govuk-design-system/issues/2289. Requires https://github.com/alphagov/govuk-design-system/issues/2298 to be done before this can start.

## Why
To ensure that our components are still usable with the updated font scale.

## Who needs to work on this
Designers, developers, accessibility specialists

## Components to review

- [x] Accordion
- [x] Back link
- [x] Breadcrumbs
- [x] Button
- [x] Character count
- [x] Checkboxes
- [x] Cookie banner
- [x] Date input
- [x] Details
- [x] Error message
- [x] Error summary
- [ ] Exit This Page
- [x] Fieldset
- [x] File upload
- [x] Footer
- [x] Header
- [x] Insert text
- [x] Notification banner
- [x] Pagination
- [x] Panel
- [x] Phase banner
- [x] Radios
- [x] Select
- [x] Skip link
- [x] Summary list
- [x] Table
- [x] Tabs
- [x] Tag
- [ ] Task list
- [x] Text input
- [x] Textarea
- [x] Warning text

```[tasklist]
### Tasks following component audit
- [x] Propose actions to take forward from audit
- [x] Collect action review from team
- [ ] Write up issues in response to actions and update typography epic
```

**Comment by owenatgov** [comment]
Testing spreadsheet (internal only): https://docs.google.com/spreadsheets/d/1-HSfNaTLIUinVQKnto5zdfYPPohta9ITSO0gz5YSAE0/edit#gid=0
