### ISSUE TITLE
Address design and guidance issues in 'Summary card' contribution

### ISSUE THREAD

**Issue by calvin-lau-sig7** [alphagov/govuk-design-system#2326]
## What

Decide how to address the design issues raised by the working group in their review of the summary card (following https://github.com/alphagov/govuk-design-system/issues/2214).

Related issues:
https://github.com/alphagov/design-system-team-internal/issues/596
https://github.com/alphagov/govuk-design-system/issues/2221
https://github.com/alphagov/govuk-design-system/issues/2224

## Why

So we know what we're building and can publish the component.

## Who needs to work on this

Designer, Content designer, developer

## Who needs to review this

Share with the whole team before finalising decisions

## Done when

Comms
- [x] Summarise recommendations from working group feedback meeting ([Notes](https://docs.google.com/document/d/1fZeCNReGQXOI4cfejggYXb_UlwnuWExiytdMOOKV2a4/edit?usp=sharing))
- [x] Made decisions on how to address (add to [decisions doc](https://docs.google.com/document/d/1PQMwjL5g36_aauXvFfsQC38AVFRt0ZpYgXZ7UJv4KEI/edit?usp=sharing)?)
- [x] Post update on backlog issue https://github.com/alphagov/govuk-design-system-backlog/issues/210

**Comment by calvin-lau-sig7** [comment]
[Draft summary in this doc](https://docs.google.com/document/d/1fZeCNReGQXOI4cfejggYXb_UlwnuWExiytdMOOKV2a4/edit?usp=sharing).

Will check with 1-2 of the folks who were at the meeting when they're in to make sure it's accurate.

**Comment by kellylee-gds** [comment]
@calvin-lau-sig7 I'm going to separate this card into two - the latter part about iterating the component I'll pop into the backlog for a later sprint
