### ISSUE TITLE
Audit Design System content and understand how users navigate content

### ISSUE THREAD

**Issue by claireashworth** [alphagov/govuk-design-system#2352]
## What
This work is to investigate, analyse and improve all Design System and Front End content/documentation that is published or publicly available.

## Why

- To make sure all our users can find the information they need.
- To make sure content is as clear and accurate as possible.
- To identify any gaps in our content/documentation.
- To identify any content/documentation that needs updating/archiving
- To make sure our team can find and use internal documentation.
- To reduce the amount of required support calls.

## Epic lead
Claire

## Who needs to work on this
Technical Writer, User Researcher

## Who needs to review this
Lead Developers, Delivery Manager, Product Manager

## Done when
We have a record of what content and documentation we have and where it is.
When we've done analysis to discover better ways of structuring our content/documentation for users.
When we've identified content/documentation that needs adding/removing/updating.

```[tasklist]
## Associated issues
- [ ] https://github.com/alphagov/govuk-design-system/issues/2391
- [ ] https://github.com/alphagov/govuk-design-system/issues/2361
- [ ] https://github.com/alphagov/govuk-design-system/issues/2353
- [ ] https://github.com/alphagov/govuk-design-system/issues/2335
- [ ] https://github.com/alphagov/govuk-design-system/issues/2381
- [ ] https://github.com/alphagov/govuk-design-system/issues/2470
- [ ] https://github.com/alphagov/govuk-design-system/issues/2357
- [ ] https://github.com/alphagov/govuk-design-system/issues/2490
```
