### ISSUE TITLE
Send Task List component guidance to the working group for review

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#2489]
## What
Send the Task List component guidance to the working group in early 2023.

## Why
To review the guidance.

## Who needs to work on this
Imran

## Done when
- [x] we have advised the working group we will be sending a review in the new year
- [x] prepared spreadsheets and documents for the review
- [x] sent to working group
- [x] responses collected
