### ISSUE TITLE
Plan a cross gov crit of Exit this Page

### ISSUE THREAD

**Issue by Katrina-Birch** [alphagov/govuk-design-system#2501]
## What
Organise online cross gov crit to examine ETP component (and pattern?) prior to publishing

## Why
EtP is a component which will impact people in risky situations. We would rather seek feedback from people who will be implementing the component prior to publication than do so and have to make changes following publication.

## Who needs to work on this
User Researcher, Interaction Designer, Community Manager, Delivery Manager

## Who needs to review this
No-one

## Preliminary tasks
- [x] We've invited cross-government colleagues
- [x] We've defined the questions we want answering
- [x] We have agreed the format of the crit
- [x] We've organised a date

```[tasklist]
## Done when
- [ ] https://github.com/alphagov/govuk-design-system/issues/2650
- [ ] https://github.com/alphagov/govuk-design-system/issues/2673
- [ ] https://github.com/alphagov/govuk-design-system/issues/2675
- [ ] https://github.com/alphagov/govuk-design-system/issues/2676
- [ ] https://github.com/alphagov/govuk-design-system/issues/2677
- [ ] https://github.com/alphagov/govuk-design-system/issues/2678
- [ ] https://github.com/alphagov/govuk-design-system/issues/2679
- [ ] https://github.com/alphagov/govuk-design-system/issues/2679
- [ ] https://github.com/alphagov/govuk-design-system/issues/2674

**Comment by kellylee-gds** [comment]
@kellylee-gds & @Ciandelle [provisional planning of the crit and consultation](https://docs.google.com/document/d/1auY96eqyh6MK20teBK8aL0jOSX6CwFuUkhX2QdfKGvk/edit)

**Comment by Ciandelle** [comment]
We ran this as a cross government content consultation, which concluded W/E: 21/04/2023
