### ISSUE TITLE
Host Design System Day 2023

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#2564]
## What
Plan and deliver Design System Day 2023.

## Why
- boosts product advocacy
- builds the team's reputation
- increases adoption of the service
- communicates benefits in using the service
- encourages community to contribute
- increases relevance and usage
- better representation of our users and community
- reaches users we usually are not able to via traditional engagement channels
- provides opportunity for upskilling, knowledge sharing and collaboration amongst DDaT professionals

## Epic lead
Imran

## Who needs to work on this
Planning group (Kelly, Steve, Imran, Katrina, Ciandelle, Calvin, Nora, Bee, Antoni, Dinesh, Michael, Tallulah)

```[tasklist]
## Discovery
- [ ] https://github.com/alphagov/govuk-design-system/issues/2575
- [ ] https://github.com/alphagov/govuk-design-system/issues/2829
- [ ] https://github.com/alphagov/govuk-design-system/issues/2828
```

```[tasklist]
## Planning the event
- [ ] https://github.com/alphagov/govuk-design-system/issues/2989
- [ ] https://github.com/alphagov/govuk-design-system/issues/3137
- [ ] https://github.com/alphagov/design-system-team-internal/issues/681
- [ ] https://github.com/alphagov/design-system-team-internal/issues/682
- [ ] https://github.com/alphagov/design-system-team-internal/issues/689
- [ ] https://github.com/alphagov/design-system-team-internal/issues/687
- [ ] https://github.com/alphagov/govuk-design-system/issues/3015
- [ ] https://github.com/alphagov/govuk-design-system/issues/3004
- [ ] https://github.com/alphagov/design-system-team-internal/issues/691
- [ ] https://github.com/alphagov/govuk-design-system/issues/2985
- [ ] https://github.com/alphagov/govuk-design-system/issues/2984
- [ ] https://github.com/alphagov/govuk-design-system/issues/2983
- [ ] https://github.com/alphagov/design-system-team-internal/issues/703
- [ ] https://github.com/alphagov/design-system-team-internal/issues/712
- [ ] https://github.com/alphagov/design-system-team-internal/issues/744
```
```[tasklist]
### After the event
- [ ] https://github.com/alphagov/govuk-design-system/issues/3201
```
