### ISSUE TITLE
Design System Day 2023 discovery

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#2575]
## What
Investigate options for Design System Day 2023 and make decisions.

## Why
So we have an initial outline of the event.

## Who needs to work on this
The DSDay23 planning group

## Who needs to review this
The GOV.UK Design System team

## Done when
- [x] Created a decision log
- [x] Formed a planning group
- [x] Held a kick off meeting (including a recap of what we did last year)
- [x] Set up weekly check ins

**Group decisions to be made and actions to take**
- [x] Decide format of the event (online, in-person or both)
- [x] Selected date(s)
- [x] Agreed venue
- [x] Considered catering options
- [x] Considered charging for the event
- [x] Agreed ticketing platform
- [x] Agreed video conferencing platform
- [x] Considered hiring external events specialist
- [x] Spoken with GDS comms and events team and shared comms plan for early sign off
- [x] Estimated total cost of the event
- [x] Secured Director approval
- [x] Secured budget sign off

```[tasklist]
## Paired investigations
- [ ] https://github.com/alphagov/govuk-design-system/issues/2626
- [ ] https://github.com/alphagov/govuk-design-system/issues/2622
- [ ] https://github.com/alphagov/govuk-design-system/issues/2627
- [ ] https://github.com/alphagov/design-system-team-internal/issues/666
- [ ] https://github.com/alphagov/design-system-team-internal/issues/675
- [ ] https://github.com/alphagov/govuk-design-system/issues/2628
- [ ] https://github.com/alphagov/design-system-team-internal/issues/678
```

```[tasklist]
## Done when
- [x] https://github.com/alphagov/govuk-design-system/issues/2828
```
