### ISSUE TITLE
Publish a pattern to help users to exit a page quickly

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#2603]
## What
A pattern to support a standardised approach to help users exit a page quickly and safely using the Exit this Page component, and how Interruption and Safety Content pages should be used.

## Who needs to work on this
Ciandelle, Calvin

## Who needs to review this
Katrina, David, Owen, Beeps

## Done when
**First draft**
```[tasklist]
- [x] Drafted pattern
- [x] Reviewed pattern with team
- [x] [Reviewed as part of community consultation](https://github.com/alphagov/govuk-design-system/issues/2679)
```
**Final iterations for mvp**
```[tasklist]
- [x] Add information about how the component is published as experimental, which aspects are not tested, and where teams will need to do research
- [ ] https://github.com/alphagov/govuk-design-system/issues/2631
- [ ] https://github.com/alphagov/govuk-design-system/issues/2633
```
