### ISSUE TITLE
Run community 'WCAG 2.2 inspection' workshops

### ISSUE THREAD

**Issue by dav-idc** [alphagov/govuk-design-system#2852]
## What
We're planning to run 4 public workshops, focussed on upcoming WCAG 2.2 criteria.

Planned workshops:
1. Inspecting WCAG 2.2: focus not obscured
2. Inspecting WCAG 2.2: target size
3. Inspecting WCAG 2.2: focus appearance
4. WCAG 2.2 detective skills

Audience(s) ranked by priority:
1. Service teams using GOV.UK Frontend
2. Other service teams in the UK government
3. Accessibility specialists within the UK government
4. Other design systems
5. Accessibility specialists anywhere
6. The general public anywhere

The workshops will strike a balance between:
- aspects where we give people stuff
- aspects where they give us work and effort back in return

## Why
We want to: 
- teach service teams how to approach WCAG 2.2 for their services
- promote the upcoming version of GOV.UK Frontend which will meet WCAG 2.2
- prepare teams for the fact that they'll need to do work for WCAG 2.2
- get help performing some element inspections for 3 of the more technical WCAG 2.2 criteria

## Who needs to work on this
Kelly (epic lead), David

## Who needs to support this
Imran (workshop 1), Chris (workshop 1), Charlotte (workshop 2)

```[tasklist]
### Focus not obscured (June 2023)
- [x] Organise, run and publish the first WCAG 2.2 inspection workshop (Focus not obscured)
```
```[tasklist]
### Target size (July 2023)
- [ ] https://github.com/alphagov/design-system-team-internal/issues/720
- [ ] https://github.com/alphagov/design-system-team-internal/issues/696
```
```[tasklist]
### Detective skills (WCAG 2.2 release - August 2023)
- [ ] https://github.com/alphagov/govuk-design-system/issues/3068
```
```[tasklist]
### Accessible authentication (September 2023)
- [ ] https://github.com/alphagov/govuk-design-system/issues/3003
- [ ] https://github.com/alphagov/govuk-design-system/issues/3066
- [ ] https://github.com/alphagov/govuk-design-system/issues/3067
```
