### ISSUE TITLE
Secure facilitators for Design System Day 2023 workshops, breakouts and show & tells

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#3004]
## What
Attract facilitators for workshops, breakout discussions and show & tells on Day 2 of Design System Day.

## Why
So we have a broad range of topics and speakers.

## Who needs to work on this
TBC

```[tasklist]
## Done when
- [ ] https://github.com/alphagov/design-system-team-internal/issues/737
- [x] Publish agenda, including a way for ticket holders to express interest in particular sessions to help us identify potential popular sessions we might want to repeat
- [ ] https://github.com/alphagov/design-system-team-internal/issues/752
- [ ] https://github.com/alphagov/design-system-team-internal/issues/778
- [ ] https://github.com/alphagov/design-system-team-internal/issues/771
- [ ] https://github.com/alphagov/govuk-design-system/issues/3125
```
