### ISSUE TITLE
Finalise and upload "first 15" WCAG 2.2 edits

### ISSUE THREAD

**Issue by calvin-lau-sig7** [alphagov/govuk-design-system#3063]
Finalise the 'first batch of 15' draft edits on Design System guidance [identified for WCAG 2.2 updates](https://docs.google.com/document/d/1nIxIKgVUheC8zvVdqWIcqtVPCl7oTN4hv11R9rDwdvM/edit?usp=sharing).

## What
These are an initial 15 edits, considered the most straightforward and easiest.
Task is to finalise these edits between content and accessibility specialist, and add them to a draft PR

## Why
- Give us insight on how to format the rest of the content updates
- Help us figure out publishing strategy
- Understand what content might need to go into dedicated WCAG 2.2 guidance pages

## Who needs to work on this
Content designer, Technical writer, Interaction designer, Accessibility specialist

## Who needs to review this
Accessibility specialist, designer, wider team

```[tasklist]
### Tasks
- [x] Phase banner || Focus not obscured (Minimum)
- [x] Confirmation pages || Focus appearance
- [x] Tag || Focus appearance
- [x] Confirm a phone number || Consistent help
- [x] Footer || Consistent help
- [x] Header || Consistent help
- [x] There is a problem with the service pages || Consistent help
- [x] File upload || Dragging movements
- [x] Select || Dragging movements
- [x] Cookie banner || Target size (Minimum)
- [x] Payment card details || Target size (Minimum)
- [x] Back link || Target size (Minimum)
- [x] Task list pages || Redundant entry
- [x] Email addresses || Redundant entry
- [x] Confirmation pages || Redundant entry
- [x] Upload all to new pull request
```
