### ISSUE TITLE
Update guidance as a result of WCAG 2.2 development work

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#3065]
## What
Following updates to Design System elements which were identified in desk research, we have uncovered further updates to guidance required to meet WCAG 2.2.

## Why
These changes will align our elements with new criteria in WCAG 2.2.

## Epic lead
TBC

## Who needs to work on this
Content Designer, Developer

## Who needs to review this
Developer, Accessibility Specialist

```[tasklist]
## Done when
- [ ] https://github.com/alphagov/govuk-design-system/issues/2664
- [ ] https://github.com/alphagov/govuk-design-system/issues/3008
- [ ] https://github.com/alphagov/govuk-design-system/issues/2866
- [ ] https://github.com/alphagov/govuk-design-system/issues/2867
- [ ] https://github.com/alphagov/govuk-design-system/issues/2868
```

**Comment by kellylee-gds** [comment]
Speaking with @CharlotteDowns and @calvin-lau-sig7 we've merged this epic with https://github.com/alphagov/govuk-design-system/issues/2729. I'll close this epic.
