### ISSUE TITLE
Upload schedule and session information for Day 2

### ISSUE THREAD

**Issue by calvin-lau-sig7** [alphagov/govuk-design-system#3125]
## What
Setup Hopin and upload all sessions into the schedule, including:
- platform tutorial, keynote, energiser, closing sessions (x4)
- session and workshop titles and descriptions (x30)
- speaker bios 
- image assets (30+)

[Based on Day 2 session grid](https://docs.google.com/spreadsheets/d/1S7qGg2tzzZRlTG2JN18A9V33kMjneBy5c3s-lCmKdtI/edit?usp=sharing)

## Why
Attendees can see what sessions are running and get a good experience

## Who needs to work on this
DSDay platform group, speaker planning group, comms, design

## Who needs to review this
DSDay organising group
```[tasklist]
### Tasks
- [x] Dependency: finalise sessions, workshops and speakers
- [x] Ensure session grid contains info, including: session/workshop titles, descriptions, speakers, bios
- [x] Image assets (session banner images) created
- [x] Schedule uploaded into Hopin, as per session grid
- [x] Session info uploaded into Hopin
- [x] Image assets uploaded into Hopin
```

**Comment by kellylee-gds** [comment]
Found this lurking in the backlog @calvin-lau-sig7 !

**Comment by calvin-lau-sig7** [comment]
Ahh thanks! Closing now as this is done now, except for last-minute updates, etc.
