### ISSUE TITLE
Collaborate with the design system community to publish a Task List component

### ISSUE THREAD

**Issue by owenatgov** [alphagov/govuk-design-system#3148]
## What
Publish a componentised version of the [Task List pattern](https://design-system.service.gov.uk/patterns/task-list-pages/). This includes a redesign of the tag component.

## Why
This is a community collaboration to provide teams in government with a reliable, reusable task list. Our pattern links to [the prototype kit plugin](https://github.com/alphagov/govuk-prototype-kit-task-list) but the need for it is frequent enough that it would be simpler to publish it via GOV.UK frontend for common use.

## Key artefacts
- [Task List component pull request](https://github.com/alphagov/govuk-frontend/pull/2261)
- [Task List guidance pull request](https://github.com/alphagov/govuk-design-system/pull/1994)
- [Tag component pull request](https://github.com/alphagov/govuk-frontend/pull/3502)
- [Tag guidance pull request](https://github.com/alphagov/govuk-design-system/pull/2733)
- [Prototype kit Task List plugin](https://github.com/alphagov/govuk-prototype-kit-task-list)
- [Task List pattern community backlog issue (contains discussions on the component)
](https://github.com/alphagov/govuk-design-system-backlog/issues/72)

## Epic Lead
???

## Done when

```[tasklist]
### Tasks
- [ ] https://github.com/alphagov/govuk-design-system/issues/3149
- [ ] https://github.com/alphagov/govuk-design-system/issues/3150
- [ ] https://github.com/alphagov/govuk-design-system/pull/1994
- [ ] https://github.com/alphagov/govuk-design-system/pull/2733
- [ ] https://github.com/alphagov/govuk-design-system/issues/3404
```

**Comment by stevenjmesser** [comment]
Suggested to Frankie that we title the pattern page based on the use case, so it’s clearer to people how it helps, rather than just calling it the ‘Task list page’. See https://github.com/alphagov/govuk-design-system/pull/1994#discussion_r1348474186
