### ISSUE TITLE
Task List component guidance

### ISSUE THREAD

**Issue by owenatgov** [alphagov/govuk-design-system#3149]
## What/Why
Write guidance for the new task list component. This issue also includes updating guidance for the tag component and deciding what to do with the existing Task List pattern guidance.

## Who needs to work on this
Community members

## Who needs to review this
Content designers

## Done when

- [x] Write Task List component guidance
- [x] Update Tag component guidance
- [x] Decide what to do with existing Task List pattern

**Comment by owenatgov** [comment]
Task list guidance PR: https://github.com/alphagov/govuk-design-system/pull/1994

Tag guidance PR: https://github.com/alphagov/govuk-design-system/pull/2733

**Comment by colinrotherham** [comment]
Closed by https://github.com/alphagov/govuk-design-system/pull/1994 🙌
