### ISSUE TITLE
Decide what to do with the Prototype Kit Task List plugin

### ISSUE THREAD

**Issue by owenatgov** [alphagov/govuk-design-system#3150]
## What
With the new Task List component going out in 5.0, we should decide if we want to continue supporting the [prototype kit task list plugin](https://github.com/alphagov/govuk-design-system/issues/3148).

## Why
This plugin predates the Task List component and is currently the primary method for reusing a Task List for government teams. However it's been noted that this plugin is currently difficult to support and behind on versions of the Task List being used in government presently, including [the version that will be going into 5.0
](https://github.com/alphagov/govuk-frontend/pull/2261).

## Who needs to work on this
TBD

## Who needs to review this
TBD

## Done when

- [ ] Decide if we should keep the plugin or not
- [ ] Document decision and reasoning
- [ ] Outline next steps with the prototype kit team

**Comment by frankieroberto** [comment]
I think there’s probably 2 options for this:

1) update [the template in the task-list-plugin](https://github.com/alphagov/govuk-prototype-kit-task-list/blob/main/templates/task-list.html) to use the new component, and also add a (peer?) dependency on `govuk-frontend` being v5+
2) retire the task-list-plugin and add a new task list pattern template to [govuk-prototype-kit-common-templates](https://github.com/alphagov/govuk-prototype-kit-common-templates/tree/main/templates) instead, alongside the templates for check-answers, etc

Any thoughts @nataliecarey?

**Comment by nataliecarey** [comment]
The current plugin that's owned by the Prototype Kit team isn't the latest implementation and we're not really the right people to be bringing it up-to-date.  If there's a need for it still to exist I'd advocate for us to pass the project over to the person/people/team who are in the best position to do the update.

**Comment by frankieroberto** [comment]
I'd be happy to help bring it up to date (it wouldn't take long at all), but do you think it'd be better to update the existing stand-alone plugin or move it to the common-templates one?

(once v5 has been released there will be no need for any custom CSS at all any more, it'll just be a simple template using components from govuk-frontend)

**Comment by colinrotherham** [comment]
Just linking commit https://github.com/alphagov/govuk-prototype-kit/pull/2327/commits/17321cbd1c32f19c9b422e587be4ae38631d0e0a

Shows Task List (and other files) still using `$legacy` parameters which might be helpful

**Comment by frankieroberto** [comment]
Having considered this a bit, I think it'd be better to add the Task List pattern (using the new component) to the existing [`common-templates` plugin](https://github.com/alphagov/govuk-prototype-kit-common-templates/tree/main/templates) and then deprecate the current task list plugin.

@nataliecarey @colinrotherham would you agree with that?

**Comment by frankieroberto** [comment]
Ok I've opened draft PRs:

* [Add the task list template to the common-templates plugin](https://github.com/alphagov/govuk-prototype-kit-common-templates/pull/26)
* [Deprecate the task list plugin](https://github.com/alphagov/govuk-prototype-kit-task-list/pull/10)

**Comment by frankieroberto** [comment]
@colinrotherham:

> As we [currently link to](https://github.com/alphagov/govuk-design-system/blob/e09c1384c7475fef9a2c26a8742cbf6926ec4024/src/patterns/task-list-pages/index.md?plain=1#L23-L26) the Task list plugin repo that we suggest is deprecated on: https://design-system.service.gov.uk/patterns/task-list-pages/
>
> Just adding this here so we remember to swap the link with common-templates

In the [proposed new guidance for the task list pattern](https://deploy-preview-1994--govuk-design-system-preview.netlify.app/components/task-list/) I've already removed the link to the prototype kit plugin altogether.

I'm not sure it’s worth linking to common-templates instead, as the HTML and Nunjucks code for the pattern is already on the page, so people can copy-and-paste it instead? 

We could link to the common-templates plugin as well - but we don't currently do that for other patterns which have a template in common-templates, like the [check your answers page](https://design-system.service.gov.uk/patterns/check-answers/)?

**Comment by stevenjmesser** [comment]
@frankieroberto's PR has deprecated the Task List plugin, so I think we can archive the [repo](https://github.com/alphagov/govuk-prototype-kit-task-list) now. I'll write a separate issue for that.
