### ISSUE TITLE
"October edits" 11 content pieces drafted, reviewed and added to PR

### ISSUE THREAD

**Issue by calvin-lau-sig7** [alphagov/govuk-design-system#3276]
Draft, finalise and upload to PR the 'October edits' of 11 pieces of draft edits on Design System guidance [identified for WCAG 2.2 updates](https://docs.google.com/document/d/1nIxIKgVUheC8zvVdqWIcqtVPCl7oTN4hv11R9rDwdvM/edit?usp=sharing).

## What
These are 11 additional edits that have been identified in desk research and testing for WCAG 2.2. Draft (using other existing edits where possible, review and upload content edits from the [content updates doc](https://docs.google.com/document/d/1nIxIKgVUheC8zvVdqWIcqtVPCl7oTN4hv11R9rDwdvM/edit?usp=sharing).

## Why
These are other changes identified through additional processes, mentioned in [previous set of 44 edits](https://github.com/alphagov/govuk-design-system/issues/2729).

## Who needs to work on this
Content designer, Technical writer, Interaction designer, Accessibility specialist

## Who needs to review this
Accessibility specialist, designer, frontend developer, wider team

```[tasklist]
### Tasks
- [ ] https://github.com/alphagov/govuk-design-system/issues/3256
- [ ] https://github.com/alphagov/govuk-design-system/issues/2869
- [ ] https://github.com/alphagov/govuk-design-system/issues/2874
- [ ] https://github.com/alphagov/govuk-design-system/issues/2870
- [ ] https://github.com/alphagov/govuk-design-system/issues/2868
- [ ] https://github.com/alphagov/govuk-design-system/issues/2881
- [ ] https://github.com/alphagov/govuk-design-system/issues/2664
- [ ] https://github.com/alphagov/govuk-design-system/issues/2872
- [ ] https://github.com/alphagov/govuk-design-system/issues/2875
- [ ] https://github.com/alphagov/govuk-design-system/issues/2867
```
