### ISSUE TITLE
Revisit the community strategy, create OKRs and build into a roadmap

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#3290]
## What
Revisit the community strategy to:
- identify key metrics
- understand how we will measure community engagement
- build activities into a roadmap

## Why
The community strategy should:
- encourage the team to be transparent about our processes, decision-making and ability to take on feedback
- actively encouraging users to get involved in our work and decision-making
- hand over decision-making power and create a sense of autonomy across gov
- upskill & build capability across government

## Who needs to work on this
Imran, Kelly, Steve

## Who needs to review this
GOV.UK Design System team

## Done when
- [x] identified areas of development
- [x] understood what metrics we should use
- [x] understood what success looks like
- [x] we have a roadmap of activities

**Comment by stevenjmesser** [comment]
*Objective: Cultivate an active and engaged community that’s open and inviting, establishes feedback loops, and highlights experts in the community*
Key result 1: Start the community call up again, and increase attendance numbers by 10%
Key result 2: Establish a working group of design systems in government and hold the first meeting
Key result 3: Increase engagement in our cross-gov Slack channel by 20%, to test the hypothesis that the community can support each other
Key result 4: Increase the number of unique posters or commenters in our cross-gov Slack, to test the hypothesis that the community can support each other

[High-level roadmap (internal use only)](https://app.mural.co/t/gaap0347/m/gaap0347/1701351837595/4fd62a198b5c603ef090b102f8ce100af37089c6).

**Comment by stevenjmesser** [comment]
Next steps: Imran will plan out a list of tasks and activities to achieve the key results and consider what help he needs from others on those (if any) so that we can plan for that capacity.

**Comment by kellylee-gds** [comment]
I think this can probably be closed.
