### ISSUE TITLE
Get the password input component and guidance into a publishable state

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-design-system#3454]
## Brief

By the end of the cycle, ensure that the password component meets our [contribution criteria for developing a component or pattern](https://design-system.service.gov.uk/community/contribution-criteria/#developing-a-component-or-pattern) and is ready to be published, taking into account any feedback received from the working group review.

This includes ensuring that:

- the guidance has been reviewed and is in a mergeable state
- the code for the component (including tests) has been reviewed and merged into the main branch ready to be released

## Epic lead
beeps

## Driving role(s)
Designer, developers, accessibility specialist

## Supporting role(s)
Community designer, delivery manager, **content (for final review)**

```[tasklist]
## Development
- [ ] https://github.com/alphagov/govuk-design-system/issues/3482
- [ ] https://github.com/alphagov/govuk-design-system/issues/3479
- [ ] https://github.com/alphagov/govuk-design-system/issues/3480
- [x] Rebase pattern edits with WCAG 2.2 update
- [ ] https://github.com/alphagov/govuk-design-system/issues/3551
- [x] Continue work to structure constituent components (optional, depending on 'common input' decision)
- [x] Write automated tests
- [x] Write Nunjucks documentation
```

```[tasklist]
## Guidance
- [ ] https://github.com/alphagov/govuk-design-system/issues/3484
- [ ] https://github.com/alphagov/govuk-design-system/issues/3535
- [ ] https://github.com/alphagov/govuk-design-system/issues/3485
- [ ] https://github.com/alphagov/govuk-design-system/issues/3653
```

```[tasklist]
## Testing
- [ ] https://github.com/alphagov/govuk-design-system/issues/3552
- [x] Accessibilty testing
- [x] Extended browser testing
```

```[tasklist]
## Community
- [x] Send out brief for working group review
- [x] Gather comments from working group
- [x] Organise and host call with working group
- [ ] https://github.com/alphagov/govuk-design-system/issues/3536
```

**Comment by 36degrees** [comment]
I've linked #3353 – it may already have been done or no longer relevant, in which case please close it.

**Comment by calvin-lau-sig7** [comment]
Hi Mike, we've attached a deadline of 15 March 2024 for this issue. 

Apologies if it's not entirely publicly visible, but under 'Project' there's a 'Deadline' field which should match up with our cycle goals and when they end. We're still working out a new way of working and Github configuration to match.

**Comment by kellylee-gds** [comment]
Shipped today in v5.3
