### ISSUE TITLE
Gather evidence on how navigation is currently being used in services

### ISSUE THREAD

**Issue by christopherthomasdesign** [alphagov/govuk-design-system#3457]
## Brief

By the end of the cycle, gather evidence on how navigation is currently being used in services, so we understand the different variations and use cases. Play back your findings to the team (and if you choose to, the community).

Aligns with [step 1 of the contribution model](https://docs.google.com/spreadsheets/d/1jSGZWy2IO0cZvyggyaa5pz2-6L5bPg7FXXxbJZbTDjA/edit#gid=0). In the next cycle we will consolidate the designs and scope it to something deliverable. *Don't do any scoping in this cycle*, but if you feel like consolidating the designs as a stretch goal, that's OK.

## Epic lead
Charlotte

## Driving role(s)
Designers, developers

## Supporting role(s)
Designer

## Further detail

- Think about how to involve the community, and what we would need to start steps 2 & 3 of the contribution model in the next cycle.
- This theme got the most responses in our survey in 2022 – some of the respondents have given permission to contact them, that might be a useful avenue
- Some community members have shared designs and insights here: https://github.com/alphagov/govuk-design-system/discussions/2376
- There is further discussion here: https://github.com/alphagov/govuk-design-system-backlog/issues/76
- One Login is an important dependency – they have created a [header](https://github.com/govuk-one-login/service-header) for services with logins to use, we need to bear in mind that more and more services will use One Login if they have account-based features
```[tasklist]
### Desk research
- [ ] https://github.com/alphagov/govuk-design-system/issues/3522
- [ ] https://github.com/alphagov/govuk-design-system/issues/3526
- [ ] https://github.com/alphagov/govuk-design-system/issues/3490
- [ ] https://github.com/alphagov/govuk-design-system/issues/3549
- [ ] https://github.com/alphagov/govuk-design-system/issues/3476
- [ ] https://github.com/alphagov/govuk-design-system/issues/3478
- [ ] https://github.com/alphagov/govuk-design-system/issues/3531
```
```[tasklist]
### Other internal tasks
- [x] Ensure navigation related conversations with users are recorded in the discussion space
- [ ] https://github.com/alphagov/govuk-design-system/issues/3474
- [ ] https://github.com/alphagov/govuk-design-system/issues/3475
- [ ] https://github.com/alphagov/govuk-design-system/issues/3530
- [x] Prepare something to collect examples and share between the squad (mural, google slides, figma etc.)
- [ ] https://github.com/alphagov/govuk-design-system/issues/3494
- [ ] https://github.com/alphagov/govuk-design-system/issues/3557
```
```[tasklist]
### Community engagement
- [x] Prepare what we will need to ask users
- [x] Review messaging to community from user researcher
- [ ] Contact users directly who gave permission in backlog prioritisation survey 2022
- [x] Contact users openly on slack
- [ ] https://github.com/alphagov/govuk-design-system/issues/3540
- [ ] Run an open session on sharing examples with the community
- [ ] Who are we going to share this with?
```
```[tasklist]
### Decisions
- [x] We have gathered evidence to decide: What type of service Navigation supports? (Will come out later)
- [x] We have gathered evidence to decide: What type of navigation? What do people use to navigate a GOV.UK page?
```

**Comment by CharlotteDowns** [comment]
## Conclusions

We will continue to find answers to the following questions in the next cycle, [Consolidate designs and form a steering group for a navigation contribution #3567](https://github.com/alphagov/govuk-design-system/issues/3567):

- What is the impact of the number of items within a single navigation element? 
- How does accessibility intersect with navigation?
- What are the technical concepts related to navigation?

We parked some of the community engagement tasks at this stage because it feels like engaging with users is going to be more useful once we've made a shortlist of options. We want these interactions to help us narrow our scope rather than expand it, hence this will be a main focus of the next cycle.

Our [slides from End-of-cycle demo](https://docs.google.com/presentation/d/1PlRMf2EEe2whV4RSiUJqtcwz41WYX6gzdz4bTyOmb2o/edit#slide=id.g2b6846b4178_0_76)
