### ISSUE TITLE
Establish feedback loops with other design system teams and contacts

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#3459]
## Brief
Establish feedback loops with other design system teams and contacts

Put in place some feedback loops that allow us to collect and share information with other design system teams, and that make it easier for them to raise things with us. These could take any form, whether that’s a regular meeting, a Slack channel, or something else. Or a combination of these options.

The other teams working on the GOV.UK ecosystem should be prioritised first, including:
- MOJ
- DfE
- DWP
- HMRC

## Epic lead
Imran

## Driving role
Community designer

## Supporting role
Associate delivery manager

## Needs awareness
Senior Product Manager, Senior Delivery Manager, wider GOV.UK Design System team

```[tasklist]
### Tasks
- [ ] https://github.com/alphagov/govuk-design-system/issues/3487
- [ ] https://github.com/alphagov/govuk-design-system/issues/3495
- [ ] https://github.com/alphagov/govuk-design-system/issues/3496
- [ ] https://github.com/alphagov/govuk-design-system/issues/3499
- [ ] https://github.com/alphagov/govuk-design-system/issues/3500
- [ ] https://github.com/alphagov/govuk-design-system/issues/3501
- [ ] https://github.com/alphagov/govuk-design-system/issues/3502
```

**Comment by ImranH-GDS** [comment]
CmD & ADM to catch up later today to go through tasks and write up cards.

**Comment by Kam-Nijjar** [comment]
meeting set for 30/01/24 - to write up cards

**Comment by Kam-Nijjar** [comment]
Draft of first card
[
](https://github.com/alphagov/govuk-design-system/issues/3487)
