### ISSUE TITLE
Add and refine Password component and pattern guidance

### ISSUE THREAD

**Issue by calvin-lau-sig7** [alphagov/govuk-design-system#3484]
Make a 2nd write-through from the initial draft of Password guidance.

## What

Write the guidance for the Password component and edit Password pattern.

## Why

To accompany the new Password input component and update our guidance, including accessibility

## Who needs to work on this

Password input squad – content designer, designer, accessibility specialist

## Who needs to review this

Developers

## Done when

- [x] Refine first draft, editing and filling in details
- [x] Review structure and flow between pattern and component
- [x] Accessibility review of our approach
- [x] Accessibility considerations added to guidance
- [x] Changes made based on working group feedback
- [x] New version of guidance commited into pull request #3355 
- [x] Review amongst the squad
- [x] Add content based on conclusions from #3535 
- [x] Add content based on conclusions from #3552
- [x] Finalise guidance in PR
- [ ] Ready to publish

**Comment by calvin-lau-sig7** [comment]
Moving to needs review – my suggestion is to get a review from:
- accessibility expert
- wider squad and team

I've also added comments in the PR in appropriate places to add finalised content based on conclusions from #3535 and #3552

**Comment by calvin-lau-sig7** [comment]
Question for the team re: suggesting 'reset codes' to reset passwords as an alternative to reset password links.

How common / recommended are using codes for password resets?

I'm wondering if we can remove this suggestion, at least in the main guidance, to stay keep the guidance more focussed. Otherwise, there's a need for us to outline a mini-pattern on how to send and get users to input the code.

I looked into linking this to the 'Confirm a phone number' pattern, but it's a fairly different thing (in use case and implementation as it can also be via email address).

**Comment by calvin-lau-sig7** [comment]
> Question for the team re: suggesting 'reset codes' to reset passwords as an alternative to reset password links.
> 
> Anika's found this in the existing 'Passwords' pattern – how common / recommended are using codes for password resets?
> 
> I'm wondering if we can remove this suggestion, at least in the main guidance, to stay keep the guidance more focussed. Otherwise, there's a need for us to outline a mini-pattern on how to send and get users to input the code.
> 
> I looked into linking this to the 'Confirm a phone number' pattern, but it's a fairly different thing (in use case and implementation as it can also be via email address).

This is resolved – we'll need guidance on this as-is.
