### ISSUE TITLE
Think about who would be a good fit to go into the group

### ISSUE THREAD

**Issue by Kam-Nijjar** [alphagov/govuk-design-system#3487]
## What
Before we can establish feedback loops with other design system teams- the first step would be to decide who to contact

## Why
Put in place some feedback loops that allow us to collect and share information with other design system teams, and that make it easier for them to raise things with us.

## Who needs to work on this
Community Designer
Associate Delivery Manager

## Review by 
PM

## Done when

```[tasklist]
### Tasks
- [x] Reserach potential contacts
- [x] Discuss who should go in
- [x] Agree with PM
- [x] Get contact details
```

**Comment by Kam-Nijjar** [comment]
List in shared drive [
](https://docs.google.com/spreadsheets/d/1NHVwFxBFLOqtPDDSQHEj9aiXkePcRwYC9Xepo4InjeA/edit?pli=1#gid=0)

**Comment by Kam-Nijjar** [comment]
tracking for potential candidates[
](https://docs.google.com/spreadsheets/d/1UX4lPHPeWJujYTiQ_jEooPQCNZudineHhaxPSZ_53w4/edit#gid=0

**Comment by Kam-Nijjar** [comment]
questionnaire to be added to tracker 
update tracker with responses

**Comment by Kam-Nijjar** [comment]
Initial email sent to community contacts

**Comment by Kam-Nijjar** [comment]
Design System Forum (name tbc)  booked for 
05/03/24 2 pm to 3 pm
to be set quarterly

**Comment by Kam-Nijjar** [comment]
confirmation of attendance received so far:-
ScotGov
NHS
MoJ 
HMRC
LocalGov Drupal

**Comment by Kam-Nijjar** [comment]
Brain dump for the event
https://docs.google.com/document/d/1JeZx0v9259VCK2h8yFBdrwOL4dzfyOvAht-9NL6gTgs/edit#heading=h.920qntb4sa7m
