### ISSUE TITLE
Decide format of regular xgov DS group meetup 

### ISSUE THREAD

**Issue by Kam-Nijjar** [alphagov/govuk-design-system#3495]
## What
Decide the format of the sessions that will work to create effective feedback loops with other Design Systems

## Why
So that we can effectively and efficiently improve our product

## Who needs to work on this
Community Manager
Associate delivery manager

## Who needs to review this
PM & DM

## Done when

```[tasklist]
### Tasks
- [ ] Find out team feedback needs
- [ ] Design session structures to collate the information
- [ ] Agree with PM & DM
- [ ] Organise a system for collecting feedback and interating the session
```
] Thing to do

**Comment by Kam-Nijjar** [comment]
[](https://design-system.service.gov.uk/community/
Currently able to give feedback via slack and or Github

**Comment by Kam-Nijjar** [comment]
Design System Forum (name tbc) booked for
05/03/24 2 pm to 3 pm
to be set quarterly

**Comment by Kam-Nijjar** [comment]
Agenda for 05/03/24
Create a mission statement & short-term goals
Delve into context and recent work

**Comment by Kam-Nijjar** [comment]
After 1st session where the mission statement for dept has become clearer we will use that to plan future sessions
