### ISSUE TITLE
Arrange a method for collating feedback requests from the team

### ISSUE THREAD

**Issue by Kam-Nijjar** [alphagov/govuk-design-system#3500]
## What
Decide and set up how we will collate feedback requests from the team - what questions 

## Why
We want to be asking the forum relevant questions. This will help make the forum more useful.

## Who needs to work on this
Community Manager
Associate Delivery Manager

## Who needs to review this
SPM & SDM
## Done when

- [ ] Thing to do

```[tasklist]
### Tasks
- [ ] Agree method for tracking feedback
- [ ] Set up tracker for feedback
```

**Comment by Kam-Nijjar** [comment]
Info gathered from Design Sstem monthly chat Jan 24
[](https://docs.google.com/document/d/1edH4WilkB74Qr_jw8uNEjVicVenM1sx3IAELhxtem4E/edit#heading=h.yobaeyodo3f1

**Comment by Kam-Nijjar** [comment]
Need to work with Katrina on this (so we don't duplicate efforts)
