### ISSUE TITLE
Liaise with User Researcher to align feedback loops

### ISSUE THREAD

**Issue by Kam-Nijjar** [alphagov/govuk-design-system#3501]
## What
Collaborate with the User Researcher to align feedback loops

## Why
Agree on one process/best practice for feedback from the community

## Who needs to work on this
Community Manager
Associate Delivery Manager
User Researcher

## Who needs to review this
Senior Delivery Manager & Senior Product Manager

## Done when

- [ ] Thing to do

```[tasklist]
### Tasks
- [ ] Arrange meet up with the User researcher
- [ ] Agree and align feedback loop that suits the community
```

**Comment by Kam-Nijjar** [comment]
Feedback to the team quarterly. Will discuss this with the User Researcher and add to feedback from users
