### ISSUE TITLE
Feed process ideas back to the team and agree changes

### ISSUE THREAD

**Issue by Kam-Nijjar** [alphagov/govuk-design-system#3502]
## What
Update the team, with the proposed feedback process, and agree to changes

## Why
The wider team needs to be made aware of the upcoming changes to the feedback process, so they can respond to queries

## Who needs to work on this
Community Manager
Associate Delivery Manager

## Who needs to review this
DSM & SPM

## Done when

- [ ] Thing to do

```[tasklist]
### Tasks
- [ ] Prepare a presentation to communicate the changes
- [ ] Arrange a meeting with the team to present changes
- [ ] Share changes with the team
```

**Comment by Kam-Nijjar** [comment]
Feedback to the team quarterly. Will discuss this with the User Researcher and add to feedback from users
