### ISSUE TITLE
Consolidate designs and form a steering group for a navigation contribution

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-design-system#3567]
### By the end of the cycle

- consolidate navigation options we want to pursue 
- share the options and our thinking with the community to get feedback
- and plan a steering group within the GOVUK Design System community.

The focus here is on community engagement as a priority. As we established in step 1, our community is well placed to help us in narrowing our scope, we can present them a shortlist of examples from our evidence phase.

Aligns with [step 2 of the contribution model](https://docs.google.com/spreadsheets/d/1jSGZWy2IO0cZvyggyaa5pz2-6L5bPg7FXXxbJZbTDjA/edit#gid=0).

### In the next cycle 
In the next cycle we will scope it to something deliverable, but it may become a stretch goal depending on progress.

- Resolve differences in existing design approaches
- Generate ideas of how to solve remaining design problems
- Work out what the possible variants and extra features are

Step 1 of the contribution model was completed in the previous cycle, Gather evidence on how navigation is currently being used in services [#3457](https://github.com/alphagov/govuk-design-system/issues/3457)

## Epic lead
Charlotte

## [Driving role(s) as referenced in the team playbook](https://govuk-design-system-team-docs.netlify.app/how-we-work/contribution-model/#consolidate-designs)
Designers, developers

## [Supporting role(s) as referenced in the team playbook](https://govuk-design-system-team-docs.netlify.app/how-we-work/contribution-model/#consolidate-designs)
Designer

## Further detail

- Think about how to involve the community, and what we need to start step 3 of the contribution model in the next cycle.
- We collected [evidence in step 1 in a mega doc](https://docs.google.com/document/d/1WMMgbnxriRekaDPfrudXDOyyCMgFBky6ymbK_vsNn7c/edit#heading=h.3asoabjyxfef) that we have also used to populate a website for easier comparison and organisation.
- There is further discussion here: https://github.com/alphagov/govuk-design-system-backlog/issues/76

## Tasks

```[tasklist]
### Consolidate navigation options
- [ ] https://github.com/alphagov/govuk-design-system/issues/3478
- [ ] https://github.com/alphagov/govuk-design-system/issues/3603
- [ ] https://github.com/alphagov/govuk-design-system/issues/3609
- [ ] https://github.com/alphagov/govuk-design-system/issues/3610
- [ ] https://github.com/alphagov/govuk-design-system/issues/3611
- [ ] https://github.com/alphagov/govuk-design-system/issues/3613
```
```[tasklist]
### Share options with community
- [ ] https://github.com/alphagov/govuk-design-system/issues/3601
- [ ] https://github.com/alphagov/govuk-design-system/issues/3602
- [ ] https://github.com/alphagov/govuk-design-system/issues/3608
- [ ] https://github.com/alphagov/govuk-design-system/issues/3612
```
```[tasklist]
### Plan steering group
- [ ] https://github.com/alphagov/govuk-design-system/issues/3636
```

**Comment by CharlotteDowns** [comment]
There is a final thing to track, messages to attendees with links and materials on either Friday or Monday morning.

**Comment by CharlotteDowns** [comment]
Parking: 

> Collect feedback from workshop and other channels 

as we won't be able to collect this until we have run the event on the 18 March 2024
