### ISSUE TITLE
Agree the format of Design System Day 2024 and submit budget estimate 

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#3570]
## Brief
By the end of the cycle we will have agreed how we will run Design System Day 2024 so we can:
- inform the team of our plan (not the community until more details are confirmed)
- set up an invoicing process with GDS BizOps
- Send budget request for sign off to SMT
- begin planning the event

## Epic lead
Imran

## Driving role(s)
Community designer, senior product manager, senior delivery manager

## Supporting role(s)
Associate delivery manager

## Further details
We should use the [retro feedback](https://govukdesignsystem.padlet.org/ImHuYorks/dsday-23-retros-wrap-up-o8rhgmuh7nffsdtn) from last year to help guide our decision making.

We can also use last year's GitHub main epic as a guide [the previous year's event](https://github.com/alphagov/govuk-design-system/issues/2564).

```[tasklist]
### Tasks
- [ ] https://github.com/alphagov/govuk-design-system/issues/3575
- [ ] https://github.com/alphagov/govuk-design-system/issues/3576
- [ ] https://github.com/alphagov/govuk-design-system/issues/3577
- [ ] https://github.com/alphagov/govuk-design-system/issues/3590
- [ ] https://github.com/alphagov/govuk-design-system/issues/3589
- [ ] https://github.com/alphagov/govuk-design-system/issues/3588
- [ ] https://github.com/alphagov/govuk-design-system/issues/3587
- [ ] https://github.com/alphagov/govuk-design-system/issues/3586
- [ ] https://github.com/alphagov/govuk-design-system/issues/3583
- [ ] https://github.com/alphagov/govuk-design-system/issues/3581
- [ ] https://github.com/alphagov/govuk-design-system/issues/3578
```

**Comment by Kam-Nijjar** [comment]
https://app.mural.co/t/gaap0347/m/gaap0347/1708943176763/32168bfb44098f10a37ae4460cedd08140bcaa32?sender=ucbed44ffda703226e8ab0951

**Comment by Kam-Nijjar** [comment]
Decision log for Design System Day 2024[
](https://docs.google.com/spreadsheets/d/1N4koNsGskJPJYKwszE09NsxJel3NJqyQEjnyeKzpc4A/edit#gid=0)

**Comment by Kam-Nijjar** [comment]
DSday24 decision workshop booked for 12th March 2024

**Comment by Kam-Nijjar** [comment]
https://docs.google.com/presentation/d/1X4-MHPg8FEIu6YQQoh-Htn489PZM6mc_nPCgoiWjcLE/edit#slide=id.g29ba0b80028_0_0
Early DSDay 2024 decisions
