### ISSUE TITLE
Build a repeatable framework to collect examples of how the Design System is being used in services

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#3571]
## Brief
We want to collect examples of how the Design System is being used, starting with the [top 75 services on GOV.UK](https://cddo.blog.gov.uk/2024/02/16/making-great-services-what-is-the-top75/#:~:text=Introducing%20the%20Top%2075&text=This%20blog%20marks%20the%20start,citizens%20use%20throughout%20their%20lives). 

This is so we can:
- understand how they're using our components and patterns
- help us understand which are the most used components and patterns
- understand where teams are not using the Design System / our services
- where our components and patterns are being iterated (to help with future prioritisation)
- any common components and patterns missing from the Design System
- we build a repository of services for looking an examples of how things are being used
- tracking crown updates (stretch)

For this first cycle we will focus on building a repeatable framework that can be used by the team to collect and analyse examples on an ongoing basis.

## Epic lead
Ciandelle

## Driving role(s)
Designer, Technical Writer

## Supporting role(s)
Senior Delivery Manager, Lead Frontend Developer

```[tasklist]
### Build a repeatable framework
- [x] https://github.com/alphagov/govuk-design-system/issues/3592
- [ ] https://github.com/alphagov/govuk-design-system/issues/3591
- [ ] https://github.com/alphagov/govuk-design-system/issues/3595
- [ ] https://github.com/alphagov/govuk-design-system/issues/3631
- [ ] https://github.com/alphagov/govuk-design-system/issues/3632
- [ ] https://github.com/alphagov/govuk-design-system/issues/3647
- [ ] https://github.com/alphagov/govuk-design-system/issues/3594
- [ ] https://github.com/alphagov/govuk-design-system/issues/3596
- [ ] https://github.com/alphagov/govuk-design-system/issues/3597
```

**Comment by kellylee-gds** [comment]
There may be collaboration with folks external to the team, eg Jonathan in IA team.

**Comment by kellylee-gds** [comment]
Preferable to buy a tool that can do this rather than build it ourselves (this would be an additional cycle, with more developers in the squad).

**Comment by kellylee-gds** [comment]
This is based on the assumption that collecting this data is valuable to the team, therefore has value in being repeatable framework.

**Comment by kellylee-gds** [comment]
**Questions from mid-cycle demo:**
- Should we speak to Uzma Razaq (GDS ResearchOps manager) may have budget for tools we could use for this. 
- Have we considered a wiki? 
- Could Wappalyzer help us find further services?
- Should we cross-reference our services list with the list of services GOV.UK are using to track crown updates
