### ISSUE TITLE
Small stories for Cycle 2

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-design-system#3574]
## Brief

This is a collection of 'small stories' that we plan to work on in Cycle 2. We do not need to complete them all.

**The other epics take priority over these issues**, but feel free to pick these up if for example you are temporarily blocked on something.

```[tasklist]
### Tasks
- [ ] https://github.com/alphagov/govuk-design-system/issues/3171
- [ ] https://github.com/alphagov/govuk-design-system/issues/1073
- [ ] https://github.com/alphagov/govuk-design-system/issues/1233
- [ ] https://github.com/alphagov/govuk-design-system/issues/1974
- [ ] https://github.com/alphagov/govuk-design-system/issues/2080
- [ ] https://github.com/alphagov/govuk-frontend/issues/4709
- [ ] https://github.com/alphagov/govuk-frontend/issues/4669
- [ ] https://github.com/alphagov/govuk-frontend/issues/4708
- [ ] https://github.com/alphagov/govuk-frontend/issues/4517
- [ ] https://github.com/alphagov/govuk-frontend/issues/3864
- [ ] https://github.com/alphagov/govuk-frontend/issues/1635
- [ ] https://github.com/alphagov/govuk-frontend/issues/4238
- [ ] https://github.com/alphagov/govuk-prototype-kit/issues/2393
- [ ] https://github.com/alphagov/govuk-prototype-kit/issues/2397
```
