### ISSUE TITLE
Scope Navigation to something deliverable and create a rough proposal

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-design-system#3662]
### By the end of the cycle

We have just recruited members of the wider Design System community to aid us in our work on Navigation.

Here are some of the tasks that we should aim to do with our newly formed steering group:
- steering group kick off meeting (week 1)
- run spikes to help make decisions (early cycle)
- design crits
- make prototypes and mockups (late cycle)
- write an outline of what the guidance should include (just bullet points) (late cycle)

Here are some tasks we can probably do as a team:
- decide what we're going to do (and not going to do) for v1 (early cycle)
- prepare the 1st working group review document (late cycle)

Aligns with [step 3 and 4 of the contribution model](https://docs.google.com/spreadsheets/d/1jSGZWy2IO0cZvyggyaa5pz2-6L5bPg7FXXxbJZbTDjA/edit#gid=0):

- Scope to something deliverable
- Create a rough proposal

### In the next cycle 

We will send the proposal we create to the Design System working group for review. We need to make sure the contribution is [useful and unique](https://design-system.service.gov.uk/community/contribution-criteria/)

Step 2 of the contribution model was completed in the previous cycle, Consolidate designs and form a steering group for a navigation contribution #3567 (https://github.com/alphagov/govuk-design-system/issues/3567)

## Epic lead
Charlotte

## [Driving role(s) as referenced in the team playbook](https://govuk-design-system-team-docs.netlify.app/how-we-work/contribution-model)
Trang, Kelly, Mia, Brett, beeps

## [Supporting role(s) as referenced in the team playbook](https://govuk-design-system-team-docs.netlify.app/how-we-work/contribution-model)
Calvin, Anika

## Further detail
- We have a squad slack group #ds-navigation, we use the canvas for tracking documents we create
- [Folks have signed up to the steering group](https://app.smartsurvey.co.uk/c/surveys/1486598/results) but we have not yet decided its make up or communicated that to folks who signed up
- We have [a slide deck from our community workshop](https://docs.google.com/presentation/d/1TOUJjzZjJ8x56Nn32RsVezOkggnGYbfZ1FQtBUhgMoA/edit#slide=id.g2c1ba67c7e7_1_154) which documents where we are so far
- We have [a website of examples that we have collected in cycle 1](https://design-system-navigation-research.netlify.app/) (password: NavigateTheNavigation)
- We have [a Padlet board of examples that were shared with us by the community](https://govukdesignsystem.padlet.org/charlottedowns1/navigation-workshop-exercise-2-ggbs8y3c9z48xdij)
- We have [a document with answers to what our community thought of our approach](https://docs.google.com/document/d/1Xd6As0d2M6Yw6f0ssolJmKUPd4phxeoUJtP8nN3E1Vc/edit)

## Tasks
```[tasklist]
### Epic lead tasks
- [x] Help folks know what their roles are within the squad
- [x] Welcome and support new folks to the squad
```
```[tasklist]
### Workshop follow up (Done week 1)
- [ ] https://github.com/alphagov/govuk-design-system/issues/3681
- [ ] https://github.com/alphagov/govuk-design-system/issues/3696
- [ ] https://github.com/alphagov/govuk-design-system/issues/3683
```
```[tasklist]
### Steering group and crit
- [ ] https://github.com/alphagov/govuk-design-system/issues/3684
- [x] Recruit a Frontend Developer from GOV.UK One Login team to join steering group (content, design)
- [ ] https://github.com/alphagov/govuk-design-system/issues/3686
- [ ] https://github.com/alphagov/govuk-design-system/issues/3712
- [x] Create a discussion space for steering group members (design)
- [ ] https://github.com/alphagov/govuk-design-system/issues/3710
- [x] Draft discussion points for steering group crit (content)
- [x] Check that the spikes / prototypes don't have any obvious accessibility issues (accessibility, developer)
- [ ] https://github.com/alphagov/govuk-design-system/issues/3678
- [ ] https://github.com/alphagov/govuk-design-system/issues/3714
- [ ] https://github.com/alphagov/govuk-design-system/issues/3715
- [ ] https://github.com/alphagov/govuk-design-system/issues/3716
```

```[tasklist]
### Working group review
- [ ] https://github.com/alphagov/govuk-design-system/issues/3680
- [ ] https://github.com/alphagov/govuk-design-system/issues/3679
```

```[tasklist]
### Decision making
- [ ] https://github.com/alphagov/govuk-design-system/issues/3711
```

**Comment by trang-erskine** [comment]
Risk 
- not sure how responsive the steering group will be
- discrepancy between steering group and team scope

How we work
- try and have parallel work going, in the past it was quite linear
- standup everyday
- kickoff on first monday of cycle.

**Comment by CharlotteDowns** [comment]
End of cycle aim: review feedback from crit, have something ready for a working group review (trial a one week review)

**Comment by querkmachine** [comment]
Methinks we forgot to close this one when cleaning up.
Feel free to reopen if it should be.
