### ISSUE TITLE
Work out our approach to embedded web views in apps

### ISSUE THREAD

**Issue by christopherthomasdesign** [alphagov/govuk-design-system#3663]
## Brief
Understand how the Design System will be affected by in-app web views that are part of the One Login journey, and document what our position is.

## Epic lead
Romaric

## Driving role(s)
Developer

## Supporting role(s)
Delivery Manager, Lead Developer, Lead Designer 

## Needs awareness
Accessibility Specialist

## Further information
The One Login and GOV.UK programmes are currently looking at how web views of GOV.UK might be embedded in the app. A few main topics have come up, there may be more than this:

* how dark mode applies across a web and app context – we want to avoid journeys where pages switch between light and dark mode
* how type scaling works across an app and an embedded website
* more generally, how styling should work – to what degree should it try match or inherit what the app does (this is possibly a stretch goal, feel free to de-scope)

We should think about how this might affect the Design System, and help create an approach for the Design System, web-based services and apps to all work together.

There's a cross-GDS working group looking at apps, led by Helena Trippe on the One Login programme. It meets every two weeks on Thursday at 11am – maybe we should plan to lead one of the sessions if we need to gather information or get feedback?

```[tasklist]
### Tasks
- [ ] https://github.com/alphagov/govuk-frontend/issues/4900
- [ ] https://github.com/alphagov/govuk-frontend/issues/4903
- [ ] https://github.com/alphagov/govuk-frontend/issues/4901
- [ ] https://github.com/alphagov/govuk-frontend/issues/4904
- [ ] https://github.com/alphagov/govuk-frontend/issues/4902
- [ ] https://github.com/alphagov/govuk-design-system/issues/3709
- [ ] https://github.com/alphagov/govuk-frontend/issues/4907
- [ ] https://github.com/alphagov/govuk-frontend/issues/4920
- [ ] https://github.com/alphagov/govuk-frontend/issues/4925
```
