### ISSUE TITLE
Shape the first event of Design System Day 2024

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#3664]
## Brief
By the end of the cycle we will have:
- secured speakers for the first event
- agreed on the topic for the team showcase and recruited speakers
- designed the branding for the event
- drafted announcement comms
- submitted an options paper to DSP SMT for budget sign off

We should be ready to announce the first event on Monday 15 April.

## Epic lead
Imran

## Driving role(s)
Community Manager, Senior Product Manager, Senior Delivery Manager, Associate Delivery Manager

## Supporting role(s)
Senior Graphic Designer

## Further information
(Access restricted to GOV.UK Design System team) [Design System Day 2024 planning spreadsheet](https://docs.google.com/spreadsheets/d/1N4koNsGskJPJYKwszE09NsxJel3NJqyQEjnyeKzpc4A/edit?pli=1#gid=2123418599)

```[tasklist]
### Tasks
- [ ] https://github.com/alphagov/design-system-team-internal/issues/869
- [ ] https://github.com/alphagov/govuk-design-system/issues/3688
- [ ] https://github.com/alphagov/govuk-design-system/issues/3689
- [ ] https://github.com/alphagov/govuk-design-system/issues/3690
- [ ] https://github.com/alphagov/govuk-design-system/issues/3691
- [ ] https://github.com/alphagov/govuk-design-system/issues/3693
- [ ] https://github.com/alphagov/govuk-design-system/issues/3694
- [ ] https://github.com/alphagov/govuk-design-system/issues/3695
- [ ] https://github.com/alphagov/govuk-design-system/issues/3767
- [ ] https://github.com/alphagov/govuk-design-system/issues/3669
- [ ] https://github.com/alphagov/govuk-design-system/issues/3668
```

**Comment by Kam-Nijjar** [comment]
emails sent to unsuccessful venues

**Comment by Kam-Nijjar** [comment]
team volunteers for 21/05/24[
](https://docs.google.com/spreadsheets/d/1HYPqbX13KYqFRcbiRkV4XFqYButmb7xdYY_s_QWcb9Q/edit#gid=0)
