### ISSUE TITLE
Make the guidance around form design and validation easier to find

### ISSUE THREAD

**Issue by trang-erskine** [alphagov/govuk-design-system#3665]
## Brief

Guidance on form design (form elements) and validation are spread across different parts of the Design System website. Users sometime struggle to find this information and the information doesn't feel structured. We want to make it easier for users to find and use.

We know about this issue through support queries, passing conversation with users and community members.

## Epic Lead
Claire

## Driving role
Designer

## Supporting role
n/a

## Further information

The scope of this brief is a bit vague. The team should review and discuss with leads as they refine the scope and decide what to do early in the cycle. These are some things they should also consider

Considerations: 
- Are there small incremental improvements that could be shipped within the cycle?
- Are there bigger changes that could be recommended for the backlog?
- Are there smaller changes that could be added as small stories for later cycles?
- Are there other changes that are more valuable to do in this cycle?

```[tasklist]
### Tasks
- [ ] https://github.com/alphagov/govuk-design-system/issues/3700
- [ ] https://github.com/alphagov/govuk-design-system/issues/3701
- [ ] https://github.com/alphagov/govuk-design-system/issues/3702
- [ ] https://github.com/alphagov/govuk-design-system/issues/3713
- [ ] https://github.com/alphagov/govuk-design-system/issues/3729
```

**Comment by claireashworth** [comment]
[Meeting notes](https://docs.google.com/document/d/1D8fxl7XRLgrN8yyZaph0c4rYTkNZ7phzFk0UJ-tdwc8/edit?usp=sharing)

**Comment by claireashworth** [comment]
[Question page analysis](https://docs.google.com/document/d/1HY9P9KQL-nV8o9DTAoSSV4nw6c0zXw_CPNcOqDE7z5k/edit?usp=sharing)

**Comment by claireashworth** [comment]
[Desk research](https://docs.google.com/document/d/1lXnRWbsi4y4nG45UIo36-8rQGM1oHv40wOdxNpc9TgY/edit?usp=sharing)

**Comment by claireashworth** [comment]
With the analysis doc and the desk research, Ciandelle and I will discuss the options, add more detail to our chosen options and write a proposal for discussion by the team.

**Comment by claireashworth** [comment]
[Proposal document](https://docs.google.com/document/d/1PawGrFVJpRoVuBz2Rj_deP-PYM2Eq6HiNDo0MyAP2Gs/edit?usp=sharing)

**Comment by claireashworth** [comment]
The proposal document has been shared with the team with a request for feedback.

**Comment by claireashworth** [comment]
Feedback received and Ciandelle is creating a mock-up.

**Comment by claireashworth** [comment]
Initial mock up complete. [this is the preview](https://deploy-preview-3736--govuk-design-system-preview.netlify.app/setting-up-your-service/) (while it's still available)
