### ISSUE TITLE
Internal milestones for steering group crit

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-design-system#3710]
Weds 3 April PM 

- [x] squad sign off/feedback session sync/async in advance of 3 April date
- [x] check things we are taking to the crit / decide what are criting
- [x] confirming format for crit
- [x] can steering group engage?

(side note: DSDay assets ready for 12 April)
