### ISSUE TITLE
Build a working version of Navigation

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-design-system#3738]
### By the end of the cycle

We have just sent out [our proposal for a Navigation component to the Working Group](https://docs.google.com/spreadsheets/d/1mij6EXq2MDvvLDzBJjkpVO_s_uiVaZjCLSQbFqQQx9M/edit?usp=sharing)

Here are some tasks we can probably do as a team:
- decide whether we need to do any of our own research – assess the risk
- address issues raised by the working group
- get something working in Frontend (not just prototypes or sketches)
- have a more detailed version of the guidance

Here are some of the tasks that the steering group can support us with:
- deciding how we act on the working group feedback 
- help write code in Frontend
- assist with accessibility and browser testing
- help write more detailed guidance

Aligns with [step 5 of the contribution model](https://docs.google.com/spreadsheets/d/1jSGZWy2IO0cZvyggyaa5pz2-6L5bPg7FXXxbJZbTDjA/edit#gid=0):

- Build a working version of the thing

### In the next cycle 

We may wish to do more user research.

Steps 3 and 4 of the contribution model was completed in the previous cycle, Scope Navigation to something deliverable and create a rough proposal #3662
 (https://github.com/alphagov/govuk-design-system/issues/3662)

## Epic lead
Charlotte

## [Driving role(s) as referenced in the team playbook](https://govuk-design-system-team-docs.netlify.app/how-we-work/contribution-model)
Ciandelle, beeps, Patrick, Anika

## [Supporting role(s) as referenced in the team playbook](https://govuk-design-system-team-docs.netlify.app/how-we-work/contribution-model)
Calvin, Katrina (scoping whether we need more research for next step of Contribuition Model [Step 6: Do more user research (only if needed)](https://docs.google.com/spreadsheets/d/1jSGZWy2IO0cZvyggyaa5pz2-6L5bPg7FXXxbJZbTDjA/edit#gid=0))

## Further detail
- We have a squad slack group #ds-navigation, we use the canvas for tracking documents we create

## Tasks

```[tasklist]
### Team and planning
- [ ] https://github.com/alphagov/govuk-design-system/issues/3778
- [ ] https://github.com/alphagov/govuk-design-system/issues/3747
- [x] Team review of Navigation Decision Log (pre working group review)
```

```[tasklist]
### Assess working group feedback, decide on actions
- [x] Prepare for working group review
- [ ] https://github.com/alphagov/govuk-design-system/issues/3761
- [ ] https://github.com/alphagov/govuk-design-system/issues/3772
- [ ] https://github.com/alphagov/govuk-design-system/issues/3781
```

```[tasklist]
### Get something working in Frontend
- [x] Research accessibility and build issues raised in decision log and accessibility specialist review
- [x] Make needed decisions in [decision log](https://docs.google.com/spreadsheets/d/1zduTR-kZc5j28PFMi98-KNoP8W8S-8iJtisf9nLAbIM/edit?usp=sharing) to continue dev work (themes: customisation, element structure, design decisions, responsive views) (pre and post working group review)
- [ ] https://github.com/alphagov/govuk-design-system/issues/3748
- [ ] https://github.com/alphagov/govuk-design-system/issues/3777
- [x] Conduct Accessibility testing
```

```[tasklist]
### Content
- [ ] https://github.com/alphagov/govuk-design-system/issues/3775
- [ ] Gather input from working+steering groups on 'best practice' guidance - stretch goal for reflection week
```
