### ISSUE TITLE
Structure draft guidance into multiple pages

### ISSUE THREAD

**Issue by calvin-lau-sig7** [alphagov/govuk-design-system#3775]
Explore and decide how to structure how Navigation and Header, and guidance, are presented on the Design System website.

[Draft guidance](https://docs.google.com/document/d/1lpnrD3Dv2PUHqxPx6bBZDGSWosjlUeBuU1Go90gAHSk/edit?usp=sharing)

[Padlet – card sort exploration of guidance structure](https://govukdesignsystem.padlet.org/calvinlau1/header-navigation-guidance-structure-v9zebvew6pv4g1al)

## What

As we decide on the structure of the Navigation and Header codebase, we also need to decide how we want to provide implementation and other guidance on this topic.

## Why

#3738 is likely to be published as multiple "pieces" of code and guidance, we need to decide how we present them to the user so we can give relevant advice at the right time.

## Who needs to be involved

Content designer, interaction designer

## Who needs to review

Navigation squad

## Done When

```[tasklist]
### Tasks
- [ ] Dependency: Code structure of Header and Navigation
- [x] Gather review and input from team and steering group [Padlet board created](https://govukdesignsystem.padlet.org/calvinlau1/header-navigation-guidance-structure-v9zebvew6pv4g1al)
- [x] Check proposed structure with recommendations from decision log and reviews
- [x] Decide on approach – E.g. 2 components and 1 pattern
- [x] New structure ready to go for revising [draft guidance](https://docs.google.com/document/d/1lpnrD3Dv2PUHqxPx6bBZDGSWosjlUeBuU1Go90gAHSk/edit?usp=sharing)
```
