### ISSUE TITLE
Onboarding new team members to Navigation squad

### ISSUE THREAD

**Issue by calvin-lau-sig7** [alphagov/govuk-design-system#3778]
## What

This issue is a rough onboarding space and list of resources for team members joining the Navigation squad.

## Why

Navigation work has gone through a few iterations with squad members changing.

## Who needs to be involved

Epic lead, content designer

## Who needs to review

All

## Done when (for new team members)

```[tasklist]
### Tasks
- [ ] Join [#ds-navigation](https://gds.slack.com/archives/C06G1NCE44B) channel on Slack
- [ ] Get invites to stand-ups and team ceremonies (epic lead or delivery manager)
- [ ] See slides and watch show and tells of Navigation work – Stored in folders for [Cycle 2 to 3 in Q4 23/24](https://drive.google.com/drive/folders/1Si1Ktat0VNV4IJ_KR7q50sX8ZaqKjrfC?usp=drive_link) and [Cycle 4 and after in Q1 24/25](https://drive.google.com/drive/folders/19XCVUSv621hKDK_QrjGdtAsFR5FRQS6d?usp=drive_link)
- [ ] Read most recent summary to the Steering group (also good to get an overview context) in [Google Doc](https://docs.google.com/document/d/1bH_aqcgI_C1aTXaLVOGOopXMPXwvKDc1T1REp007Udg/edit?usp=sharing)
- [ ] Familiarise issues and themes in the [decision log](https://gds.slack.com/canvas/C06G1NCE44B)
- [ ] See detailed cycle history of work and list of important documents [Slack canvas](https://gds.slack.com/canvas/C06G1NCE44B)
- [ ] See draft guidance structure and notes in [Padlet](https://govukdesignsystem.padlet.org/calvinlau1/header-navigation-guidance-structure-v9zebvew6pv4g1al) and [draft content](https://docs.google.com/document/d/1lpnrD3Dv2PUHqxPx6bBZDGSWosjlUeBuU1Go90gAHSk/edit?usp=sharing) (needs to be updated as of 1/5)
```

**Comment by 36degrees** [comment]
I think this issue has served it's purpose so I'm going to close it – feel free to reopen it if I've got that wrong!
