### ISSUE TITLE
Review a working version of Navigation

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-design-system#3795]
### By the end of the cycle

We want to have a working version of Navigation in review. It would be good to involve the wider community in an activity as well as conducting a second working group review.

The second working group will make sure the Navigation contribution is [usable, consistent and versatile](https://design-system.service.gov.uk/community/contribution-criteria/).

Here are some tasks we can probably do as a team:
- have a more detailed version of the guidance
- bring in resolutions from accessibility and design work in the previous cycle

Here are some of the tasks that the steering group can support us with:
- help us in naming the components and pattern.
- assist with accessibility and browser testing
- help write more detailed guidance
- determine a convention to service name linking and associated styles

Aligns with [step 5 of the contribution model](https://docs.google.com/spreadsheets/d/1jSGZWy2IO0cZvyggyaa5pz2-6L5bPg7FXXxbJZbTDjA/edit#gid=0):

- Build a working version of the thing

### In the next cycle 

We want to build a robust version of Navigation.

We also worked on step 5 in the previous cycle, Build a working version of Navigation #3738
 (https://github.com/alphagov/govuk-design-system/issues/3738)

## Epic lead
Charlotte

## [Driving role(s) as referenced in the team playbook](https://govuk-design-system-team-docs.netlify.app/how-we-work/contribution-model)
beeps, Patrick

## [Supporting role(s) as referenced in the team playbook](https://govuk-design-system-team-docs.netlify.app/how-we-work/contribution-model)
Calvin

## Further detail
- We have a squad slack group #ds-navigation, we use the canvas for tracking documents we create

## Tasks

```[tasklist]
### Team and planning
- [ ] https://github.com/alphagov/govuk-design-system/issues/3778
- [ ] Review of [Navigation Decision Log](https://docs.google.com/spreadsheets/d/1zduTR-kZc5j28PFMi98-KNoP8W8S-8iJtisf9nLAbIM/edit#gid=1037439525), ensure it's up-to-date
- [ ] https://github.com/alphagov/govuk-design-system/issues/3808
```

```[tasklist]
### Make needed decisions to resolve blockers, update code where possible, also involving steering group where possible
- [ ] https://github.com/alphagov/govuk-design-system/issues/3824
- [ ] https://github.com/alphagov/govuk-design-system/issues/3809
- [x] Decide on naming of the components and patterns, summary line and search alias
- [ ] https://github.com/alphagov/govuk-design-system/issues/3811
- [ ] https://github.com/alphagov/govuk-design-system/issues/3816
```

```[tasklist]
### Revise content into 3-page structure
- [ ] https://github.com/alphagov/govuk-design-system/issues/3810
- [ ] Gather input from working+steering groups on 'best practice' guidance
- [ ] Check the relationship of the new component with existing components in the Design System
```

```[tasklist]
### Build preview branch of GOV.UK Frontend and preview page
- [ ] https://github.com/alphagov/govuk-design-system/issues/3823
- [x] Add links and screenshots of variants for Google Doc
- [x] Make needed changes to working branch to get screenshots and links (to include in Google Doc)
- [x] Get Google Doc ready for working group review
```

**Comment by calvin-lau-sig7** [comment]
From @querkmachine: main outstanding decisions needed:
- naming of components and parts (e.g. service header)
- styling of service name link
- response to accessibility issues (e.g. placement of links on desktop)
