### ISSUE TITLE
Prepare for an accessibility audit of the Design System website and a re-test of GOV.UK Frontend

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#3825]
## Brief
GOV.UK Frontend was last audited in May 2023. In order for it to be re-tested we need to update the review app to include examples of new components we have added to Frontend. We also need to ensure our audit supplier is happy with the brief to audit the Design System website, and arrange in-person attendance of the audit for the team.

As part of this brief we could also update the website to fully use the new typographic scale so it is included in the audit.

## Epic lead
Kelly

## Leading roles
Owen, beeps

## Supporting role
Anika

## Further info
- Previous PR  https://github.com/alphagov/govuk-frontend/pull/3503/files
- Frontend audit results and latest https://docs.google.com/spreadsheets/d/1qiWCRwH7QofQgJ9iDLRSsfETLKlZCyrv7z04qjZurhM/edit#gid=0

```[tasklist]
### Tasks
- [ ] https://github.com/alphagov/govuk-frontend/issues/5085
- [ ] https://github.com/alphagov/govuk-design-system/issues/3860
- [ ] https://github.com/alphagov/govuk-design-system/issues/3861
- [ ] https://github.com/alphagov/govuk-design-system/issues/3862
```
