### ISSUE TITLE
Build a robust version of Navigation

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-design-system#3835]
### By the end of the cycle

We want to address issues raised by working group and get the guidance and code ready to publish. We want to establish with developers from One Login how we adopt their component into the proposed GOV.UK header component.

Here are some tasks we can probably do as a team:
- host a post-review session with the working group (sometime w/c 1 July 2024)
- review the code and guidance (2i)

Here are some of the tasks that the steering group can support us with:
- in-depth browser testing
- in-depth accessibility testing
- detailed design tweaks

Aligns with [step 5 of the contribution model](https://docs.google.com/spreadsheets/d/1jSGZWy2IO0cZvyggyaa5pz2-6L5bPg7FXXxbJZbTDjA/edit#gid=0):

- Build a robust version of the thing

### In the next cycle 

We want to publish Navigation 🏁.

We worked on step 5 in the previous cycle, [Review a working version of Navigation #3795](https://github.com/alphagov/govuk-design-system/issues/3795#top)

## Epic lead
Charlotte

## [Driving role(s) as referenced in the team playbook](https://govuk-design-system-team-docs.netlify.app/how-we-work/contribution-model)
beeps, Calvin, Brett, Ciandelle

## [Supporting role(s) as referenced in the team playbook](https://govuk-design-system-team-docs.netlify.app/how-we-work/contribution-model)
Anika, Izabela

## Further detail
- Here is the [Navigation proposal sent to the working group](https://docs.google.com/spreadsheets/d/1mij6EXq2MDvvLDzBJjkpVO_s_uiVaZjCLSQbFqQQx9M/edit?gid=2138860767#gid=2138860767)
- We have a squad slack group #ds-navigation, we use the canvas for tracking documents we create

## Tasks

```[tasklist]
### Team and planning
- [ ] https://github.com/alphagov/govuk-design-system/issues/3778
- [ ] Review of [Navigation Decision Log](https://docs.google.com/spreadsheets/d/1zduTR-kZc5j28PFMi98-KNoP8W8S-8iJtisf9nLAbIM/edit#gid=1037439525), ensure it's up-to-date
```

```[tasklist]
### Guidance
- [ ] https://github.com/alphagov/govuk-design-system/issues/3833
```

```[tasklist]
### Development
- [ ] tbd
```

```[tasklist]
### Accessibility
- [ ] tbd
```

```[tasklist]
### Design
- [ ] tbd
```
