### ISSUE TITLE
Confirm we have all guidance that supports development (week 2 / 3)

### ISSUE THREAD

**Issue by calvin-lau-sig7** [alphagov/govuk-design-system#3871]
This issue is to gather code-related guidance needed in the GOV.UK header and Service header navigation components as they're identified as part of development work.

## What

We have draft component guidance being reviewed, but will need to add more as dev work is finalised.

## Why

It's important to gather these guidance needs as they come up in team conversations, however decisions and work might still need to be finalised before content work can start.

## Who needs to work on this
Content designer, developer

## Who needs to review this
Navigation squad

```[tasklist]
### Tasks
- [ ] Explain how the 'slots' work
- [ ] Warn services about risks with using slots
- [ ] Implementation of One Login (TBC with One Login team)
- [ ] Explain how service teams can 'unlink' current page so users better understand where they are – including both examples
```

**Comment by calvin-lau-sig7** [comment]
Re: Slots from @querkmachine:

> Service Header has:
start, which is injected at the start of the govuk-width-container but outside of the component's inner container (by default, this would be above the service name and navigation)
end, which is injected at the end of the govuk-width-container (below the service name and navigation)
navigationStart, which is injected before the first list item within the navigation
navigationEnd, which is injected after the last list item within the navigation

**Comment by CharlotteDowns** [comment]
These are being tracked by new cards in [Plan and determine how to release Navigation](https://github.com/alphagov/govuk-design-system/issues/3888#top)
