### ISSUE TITLE
Plan and determine how to release Navigation

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-design-system#3888]
### By the end of the cycle

We want to address issues raised by working group and get the guidance and code ready to publish. We want to determine how we will publish the component. Will Navigation be part of a major release and how can we communicate when it will be released to the community so they can prepare for changes.

Here are some tasks we can probably do as a team:
- decide on what we can commit to change in order to gain confidence of the working group
- gather evidence to support our position

Here are some of the tasks that the steering group can support us with:
- providing examples to the working group
- help us collect end user research
- resolve issues raised by the working group

Aligns with [step 6 of the contribution model](https://docs.google.com/spreadsheets/d/1jSGZWy2IO0cZvyggyaa5pz2-6L5bPg7FXXxbJZbTDjA/edit#gid=0):

- Build a robust version of the thing

### In the next cycle 

We want to publish Navigation 🏁.

We worked on step 6 in the previous cycle, [Build a robust version of Navigation #3835](https://github.com/alphagov/govuk-design-system/issues/3835#top)

## Epic lead
Charlotte

## [Driving role(s) as referenced in the team playbook](https://govuk-design-system-team-docs.netlify.app/how-we-work/contribution-model)
beeps, Calvin

## [Supporting role(s) as referenced in the team playbook](https://govuk-design-system-team-docs.netlify.app/how-we-work/contribution-model)
Anika, Izabela

## Further detail
- Here is the [Navigation proposal sent to the working group](https://docs.google.com/spreadsheets/d/1mij6EXq2MDvvLDzBJjkpVO_s_uiVaZjCLSQbFqQQx9M/edit?gid=2138860767#gid=2138860767)
- We have a squad slack group #ds-navigation, we use the canvas for tracking documents we create

## General tasks and planning
```[tasklist]
### Epic lead and delivery
- [ ] https://github.com/alphagov/govuk-design-system/issues/3778
- [x] Review [Navigation Decision Log](https://docs.google.com/spreadsheets/d/1zduTR-kZc5j28PFMi98-KNoP8W8S-8iJtisf9nLAbIM/edit#gid=1037439525), ensure it's up-to-date
- [ ] https://github.com/alphagov/govuk-design-system/issues/3919
- [x] Ask working group to re-review our proposal based on the commitments (what we will do) in this brief
- [ ] https://github.com/alphagov/govuk-design-system/issues/3946
```

### Navigation should...
- Advise ‘When to use’ in relation to other navigation components at the top of the page, for example, breadcrumbs, back link, localisation, search and phase banner
- Work consistently with the GOVUK one login header
- Be a component that supports main sections of the site
- Consider line height, width and spacing of other components on a page
- Aim to not break services with existing header navigation

```[tasklist]
### All squad
```

```[tasklist]
### Guidance
- [x] Remove "5 pages or fewer" instruction and the no-service-name variant
- [x] Explain why services would have different navigation than GOV.UK pages
- [ ] https://github.com/alphagov/govuk-design-system/issues/3918
- [x] Change advice on where to place Phase banner
- [ ] https://github.com/alphagov/govuk-design-system/issues/3916
- [ ] Acknowledge One Login's header
- [ ] Review guidance with team and create new pull request, based 'more agile' release
```

```[tasklist]
### Accessibility and Development
- [x] Understand conclusions of APCA colour calculator [APCA Contrast Calculator ](https://www.myndex.com/APCA/?BG=f3f2f1&TXT=1d70b8&DEV=G4g&BUF=A22)
- [x] Test increased font weight in other colour modes (for example, high contrast)
- [ ] Document conclusions and thoughts on the investigation into making the links be more legible
```

```[tasklist]
### Design
- [ ] https://github.com/alphagov/govuk-design-system/issues/3945
- [ ] https://github.com/alphagov/govuk-design-system/issues/3964
- [ ] https://github.com/alphagov/govuk-design-system/issues/3955
- [ ] Decouple visual examples of both components in the guidance so they look like distinct components and add combined example to pattern
```

### Navigation could...
- Give guidance on where to put things that help your service be identified
- Consider providing suggested content for common Navigation items
- Deliver a component that supports level 3 type of navigation
- Provide advice on information architecture
- Support services with account functionality that may not use One Login account verification
- Be more than one component and/or pattern

```[tasklist]
### Guidance
- [ ] https://github.com/alphagov/govuk-design-system/issues/3909
- [ ] Provide a space to channel feedback on the pattern to
- [ ] Sentences to explain the journey between [GOV.UK](http://gov.uk/) and services on GOV.UK
- [ ] Remove header terminology from Service 'bar' name
```

```[tasklist]
### Design
- [ ] https://github.com/alphagov/govuk-design-system/issues/3973
- [ ] https://github.com/alphagov/govuk-design-system/issues/3930
- [ ] STRETCH: Diagrams to explain the journey between [GOV.UK](http://gov.uk/) and services on GOV.UK
- [x] Revisit what's in the GOV.UK header (black bar), for example, moving the Service name back
```

### Navigation should not...
- Investigate a search component, filterable lists or finders but should be flexible enough to work with a future search component
- Look at how it could be implemented in apps
- Provide a solution for lots of content and information, e.g. [www.gov.uk](http://www.gov.uk/). The teams in the GOV.UK directorate know most about this
