### ISSUE TITLE
Decide and communicate upcoming changes for services and what support we can offer [updated]

### ISSUE THREAD

**Issue by calvin-lau-sig7** [alphagov/govuk-design-system#3914]
## What

We need to tell services:
- updates we're making to the design of header and navigation
- the changes they'll need to make
- when they need to do it
- support we can offer

## Why

With our 'more agile' release, we're introducing some gradual changes that affect where services should show their navigation menu, and later on, their service name.

We need to make services aware of what they need to do.

## Who needs to be involved

Content designer, developer, squad lead

## Who needs to review

Delivery manager, product, wider team (for support queries)

## Tasks
- [x] Decide and map out changes and timings
- [x] Decide on support we can offer
- [x] Write needed changes to guidance
- [x] Prepare comms doc with messages

Next: Create any support resources

**Comment by Izabela-16** [comment]
@CharlotteDowns I had a chat about it today with Calving at the stand up. Just let me know what is needed and I will make sure that we have block time and relevant people in one place. I think we might need some jam session to get the consensus and align everything.
