### ISSUE TITLE
Analyse results of an accessibility audit of the Design System website

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#3915]
## Brief
Once the report has been received from DAC, analyse and record the results of the audit. Investigate the issues raised and estimate timeframes to fix them.

## Epic lead
Kelly

## Driving role(s)
Senior accessibility specialist, designer, developer

## Supporting roles
Senior delivery manager

## Needs awareness
Team leads

```[tasklist]
### Tasks
- [ ] https://github.com/alphagov/govuk-design-system/issues/3936
- [ ] https://github.com/alphagov/govuk-design-system/issues/3937
- [ ] https://github.com/alphagov/govuk-design-system/issues/3938
```
