### ISSUE TITLE
Prepare for Design System Day

### ISSUE THREAD

**Issue by trang-erskine** [alphagov/govuk-design-system#3920]
## Brief

**Cycle ends 3.5 weeks before the event. Cycle dates: 15th July - 9 August**

The priorities for this brief are as follows:

### Decide and confirm all speakers and agree on agenda
Call to speakers have gone out last cycle and deadline is 28 July. We need to evaluate suggestions against our criteria (theme, variety, diversity etc.) and secure speakers for the Day. We need to agree on the agenda and announce headlines from the agenda w/c 5 August.

Agree on timings and speaker slot of speakers.

### Release tickets stage 1

Release stage 1 tickets, including joining instructions by w/c August. Prep for releasing stage 2 tickets. 

### Event branding and merchandise
Decide what merchandise is needed and quantity for event goers, volunteers and speakers. 
Decide what banners, posters are needed to signpost event at the venue after scouting visit.

Merchandise tends to have a lead time. We need to get these ordered this cycle. 

We don't need 3 quotes, however do a rough check on pricing. Much sure we're within [budget](https://docs.google.com/spreadsheets/d/1PYD7z-7w2pDA4HGMV29AeJeypNvQpYd63NphNjD8O_8/edit?gid=303594083#gid=303594083)

### Procure suppliers

We need to procure suppliers for:
- venue
- catering
- AV
- Photography / Videography

We need quotes from at least 3 suppliers and to follow the [procurement policy](https://docs.google.com/document/d/1Ulzm8-O90CMiUggXss-AklmEAOG373zeP9xNWdyeliE/edit?pli=1#heading=h.njcowdawp4gf) when awarding the contract to the supplier.

## Epic lead
Imran

## Leading role
Kam, Kelly, Mia, Nora, Ciandelle, Patrick

```[tasklist]
### Tasks for this Cycle
- [ ] https://github.com/alphagov/govuk-design-system/issues/3839
- [ ] https://github.com/alphagov/govuk-design-system/issues/3921
- [ ] https://github.com/alphagov/govuk-design-system/issues/3842
- [ ] https://github.com/alphagov/govuk-design-system/issues/3922
- [ ] https://github.com/alphagov/govuk-design-system/issues/3934
- [ ] https://github.com/alphagov/govuk-design-system/issues/3923
- [ ] https://github.com/alphagov/govuk-design-system/issues/3924
- [ ] https://github.com/alphagov/govuk-design-system/issues/3925
- [ ] https://github.com/alphagov/govuk-design-system/issues/3926
- [ ] https://github.com/alphagov/govuk-design-system/issues/3927
- [ ] https://github.com/alphagov/govuk-design-system/issues/3928
- [ ] https://github.com/alphagov/govuk-design-system/issues/3929
- [ ] https://github.com/alphagov/govuk-design-system/issues/3931
- [ ] https://github.com/alphagov/govuk-design-system/issues/3935
```
```[tasklist]
### Tasks for next Cycle ends with DS Day
- [ ] https://github.com/alphagov/govuk-design-system/issues/3986
- [ ] https://github.com/alphagov/govuk-design-system/issues/3987
- [ ] https://github.com/alphagov/govuk-design-system/issues/3988
- [ ] https://github.com/alphagov/govuk-design-system/issues/3989
- [ ] https://github.com/alphagov/govuk-design-system/issues/3990
- [ ] https://github.com/alphagov/govuk-design-system/issues/3991
- [ ] https://github.com/alphagov/govuk-design-system/issues/3992
- [ ] https://github.com/alphagov/govuk-design-system/issues/3993
- [ ] https://github.com/alphagov/govuk-design-system/issues/3995
- [ ] https://github.com/alphagov/govuk-design-system/issues/3994
- [ ] https://github.com/alphagov/govuk-design-system/issues/3996
- [ ] https://github.com/alphagov/govuk-design-system/issues/3997
- [ ] https://github.com/alphagov/govuk-design-system/issues/3983
- [ ] https://github.com/alphagov/govuk-design-system/issues/3984
- [ ] https://github.com/alphagov/govuk-design-system/issues/3998
- [ ] https://github.com/alphagov/govuk-design-system/issues/4000
- [ ] https://github.com/alphagov/govuk-design-system/issues/4001
- [ ] https://github.com/alphagov/govuk-design-system/issues/3932
- [ ] https://github.com/alphagov/govuk-design-system/issues/4035
```

```[tasklist]
### Tasks after the event
- [ ] https://github.com/alphagov/govuk-design-system/issues/4091
```
