### ISSUE TITLE
Schedule release ticket Stage 2 (optional)

### ISSUE THREAD

**Issue by Kam-Nijjar** [alphagov/govuk-design-system#3925]
## What
Release the second batch of tickets for Design System Day 2024 in Liverpool 

## Why
So that we can have attendees at the event

## Who needs to work on this
@Ciandelle 

## Who needs to review this
@NoraGDS 

## Done when

- [x] Tickets are set up on Eventbrite
- [x] Tickets have a go live date
- [x] Ticket numbers have been agreed
- [x] Tickets have order confirmation form alongside them with dietary requirements and accessibility information
- [ ] Tickets have joining information attached

```[tasklist]
### Tasks
- [x] Agree who will post comms and on which channels
- [x] Publish tickets
```
