### ISSUE TITLE
Address issues raised in WCAG 2.2 accessibility audits

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#3967]
## Brief
In this brief we will investigate the issues raised in the WCAG 2.2 audit of the Design System website, and put fixes in place if deemed necessary.

We will also revisit the decisions made following the WCAG 2.2 audit of govuk-frontend in 2023 to see if our opinion has shifted on addressing usability issues raised in that report. We retested govuk-frontend in July 2024 and no issues were raised, however it's worth revisiting the things we decided to not fix to see if we feel the same way a year later.

## Epic lead
Owen

## Driving role(s)
Anika, Hazal

## Supporting roles
Kelly, Charlotte, beeps

## Further detail
[Website audit issues](https://docs.google.com/spreadsheets/d/1EZms4ZAwyOOu6oksPKVZR3Ln5P4u40rBdDobQ_BmxrU/edit?gid=0#gid=0)

[Frontend audit issues (from 2023)](https://docs.google.com/spreadsheets/d/1qiWCRwH7QofQgJ9iDLRSsfETLKlZCyrv7z04qjZurhM/edit?gid=0#gid=0)

```[tasklist]
### Issues to be investigated
- [ ] https://github.com/alphagov/govuk-design-system/issues/4003
- [ ] https://github.com/alphagov/govuk-design-system/issues/4004
- [ ] https://github.com/alphagov/govuk-design-system/issues/4005
- [ ] https://github.com/alphagov/govuk-design-system/issues/4006
- [ ] https://github.com/alphagov/govuk-design-system/issues/4007
- [ ] https://github.com/alphagov/govuk-design-system/issues/4015
- [ ] https://github.com/alphagov/govuk-design-system/issues/4016
- [ ] https://github.com/alphagov/govuk-design-system/issues/4025
- [ ] https://github.com/alphagov/govuk-design-system/issues/4026
```
```[tasklist]
### Additional tasks
- [x] Set priorities of non-A issues
- [x] Discuss content issues with Calvin and agree approach
- [ ] https://github.com/alphagov/govuk-design-system/issues/4008
- [ ] https://github.com/alphagov/govuk-design-system/issues/3939
- [ ] https://github.com/alphagov/design-system-team-internal/issues/908
- [ ] https://github.com/alphagov/govuk-design-system/issues/3941
- [ ] https://github.com/alphagov/govuk-design-system/issues/3940
```

**Comment by kellylee-gds** [comment]
Closed as cycle finished. Issues moved to [next brief ](https://github.com/alphagov/design-system-team-internal/issues/912)
