### ISSUE TITLE
Release an 'agile' version of Navigation

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-design-system#4002]
### By the end of the cycle

We want to release an 'agile' version of Navigation, here is [the card where we captured what we have defined agile as](https://github.com/alphagov/govuk-design-system/issues/3946).

Here are some tasks we can probably do as a team:
- Final code changes
- Final browser testing
- Final accessibility testing
- Prepare preview pages and examples 
- Design review
- Engagement with stakeholders

Aligns with [step 7 of the contribution model](https://docs.google.com/spreadsheets/d/1jSGZWy2IO0cZvyggyaa5pz2-6L5bPg7FXXxbJZbTDjA/edit#gid=0):

- Publish

We worked on step 6 in the previous cycle, [Plan and determine how to release Navigation #3888](https://github.com/alphagov/govuk-design-system/issues/3888#top)

## Epic lead
Charlotte

## [Driving role(s) as referenced in the team playbook](https://govuk-design-system-team-docs.netlify.app/how-we-work/contribution-model)
beeps, Calvin

## [Supporting role(s) as referenced in the team playbook](https://govuk-design-system-team-docs.netlify.app/how-we-work/contribution-model)
Anika, Izabela, whole team (?) 

## Further detail
- Here is the [mural board we were working on to define the agile release](https://app.mural.co/t/gaap0347/m/gaap0347/1721217826897/13a748188d345a51e436b3eaa9fc3645cdda5c71?fromVisitorModal=true&sender=u14668c1046a9bc3bfe281918)
- Here is [the retro board with the suggestions on how we can improve this cycle](https://trello.com/b/kAqsN3h5/design-system-retrospective-06082024)
- We have a squad slack group #ds-navigation, we use the canvas for tracking documents we create

## General tasks and planning
```[tasklist]
### Epic lead and delivery
- [ ] https://github.com/alphagov/govuk-design-system/issues/3778
- [x] Review [Navigation Decision Log](https://docs.google.com/spreadsheets/d/1zduTR-kZc5j28PFMi98-KNoP8W8S-8iJtisf9nLAbIM/edit#gid=1037439525), ensure it's up-to-date
- [x] Put together our plan for unsure decisions (from retro)
- [x] Identify blockers at start of cycle, prioritise work to unblock them (from retro)
- [ ] https://github.com/alphagov/govuk-design-system/issues/3914
- [ ] https://github.com/alphagov/govuk-frontend/issues/5271
- [ ] https://github.com/alphagov/govuk-design-system/issues/4076
```

```[tasklist]
### All squad
- [x] review oustanding guidance changes from previous cycle
- [ ] https://github.com/alphagov/govuk-design-system/issues/4038
- [x] Decide whether to change guidance in 'Phase banner' re: where to place
```

```[tasklist]
### Accessibility and Development
- [x] Final accessibility testing (may need to defer due to team leave)
- [x] Implement a more legible version of the navigation items
- [x] Two variations of the blue bar that sit beneath the black header bar, known as 10px border-bottom on the govuk-header__container
- [x] Refactor active state styles
- [x] Explore accessibility considerations (landmark announcement)
- [x] Create a preview release link for guidance examples
```

```[tasklist]
### Guidance
- [ ] https://github.com/alphagov/govuk-design-system/issues/4036
- [ ] https://github.com/alphagov/govuk-design-system/issues/4039
- [ ] https://github.com/alphagov/govuk-design-system/issues/4040
- [ ] https://github.com/alphagov/govuk-design-system/issues/4041
- [ ] https://github.com/alphagov/govuk-design-system/issues/4042
- [x] Update phase banner guidance (small)
- [x] add guidance into preview pages
```

```[tasklist]
### Design
- [x] Double check focus state of refactored active navigation items
- [ ] https://github.com/alphagov/govuk-design-system/issues/4065
- [ ] https://github.com/alphagov/govuk-design-system/issues/4052
- [x] Check that stakeholders know we are releasing an 'agile' release
```

**Comment by CharlotteDowns** [comment]
Navigation is published 29 August 2024 🎉
