### ISSUE TITLE
Assess guidance needed for the 'agile' release

### ISSUE THREAD

**Issue by calvin-lau-sig7** [alphagov/govuk-design-system#4036]
## What

Assess content updates needed to meet the 'more agile' release and updated decisions. 
Decide, write and review new guidance needed.

## Why

'More agile' release has changed guidance needed

## Who needs to be involved

Content designer, interactions designer

## Who needs to review

All squad

```[tasklist]
### Tasks
- [x] Assess existing guidance – decide on what to keep/remove/change
- [x] Create updated outline with notes for new guidance
- [x] write new issues needed to draft new guidance
```
