### ISSUE TITLE
Update draft for GOV.UK Header, as an unchanged component

### ISSUE THREAD

**Issue by calvin-lau-sig7** [alphagov/govuk-design-system#4039]
## What 

Write an updated draft for the GOV.Uk Header.

## Why

'More agile' release will keep GOV.UK Header as an unchanged component. However, we want to include new advice for services and promote use of the Service navigation component.

## Who needs to be involved

Content designer

## Who needs to review

All squad

```[tasklist]
### Tasks
- [x] Add in square brackets for [example services]
- [x] Remove 5 page suggestion
- [x] Add guidance for services to avoid 'product name' variant
- [x] Add guidance about not needing to look like the GOV.UK menu bar
- [x] Suggest services use the Service navigation component for service name and navigation (emphasise our confidence towards it
- [x] remove slots from ‘GOV.UK Header’
```

**Comment by calvin-lau-sig7** [comment]
The guidance doc is still messy, but I've made an updated draft of this page:
https://docs.google.com/document/d/1lpnrD3Dv2PUHqxPx6bBZDGSWosjlUeBuU1Go90gAHSk/edit#bookmark=id.my15o5teak43
