### ISSUE TITLE
Update draft for Service navigation, with new decisions

### ISSUE THREAD

**Issue by calvin-lau-sig7** [alphagov/govuk-design-system#4040]
## What 

Write an updated draft for the Service Navigation.

## Why

'More agile' release includes some new decisions for the new Service navigation component., with instructions we've changed into recommendations with requests for feedback.

Related issue: Draft ‘Research on this component’ sections

## Who needs to be involved

Content designer

## Who needs to review

All squad

```[tasklist]
### Tasks
- [x] rename all instances of ‘Service header navigation’ to ‘service navigation’
- [x] introduce option to place service name in service navigation as a recommendation we eventually want to implement
- [x] ask services for testing / feedback (also link from update “### Previous versions of the headers”
- [x] Under ‘Slots’, add note to change landmark if needed
- [x] include instructions for blue bar
```

**Comment by Izabela-16** [comment]
@Izabela-16 to block some time on Tue (on Friday looks like Charlotte is on all day branding workshop) for @calvin-lau-sig7 @CharlotteDowns to review documentation.
