### ISSUE TITLE
Draft ‘Research on this component’ sections

### ISSUE THREAD

**Issue by calvin-lau-sig7** [alphagov/govuk-design-system#4042]
## What 

Explain important decisions in navigation work, particularly ones we're still not confident on.

## Why

So we can provide rationale and evidence we currently have, and ask service teams to help us with their own.

## Who needs to be involved

Content designer

## Who needs to review

All squad

```[tasklist]
### Tasks (still to complete)
- [x] indicate active page (but not section) in navigation links
- [x] ask service for testing / feedback of service name
- [x] contrast of blue text on grey background (we opted for 10% darker)
```

**Comment by calvin-lau-sig7** [comment]
Closing this issue, as this content will be handled by backlog posts in #4052
