### ISSUE TITLE
Wrap up face to face Design System Day

### ISSUE THREAD

**Issue by trang-erskine** [alphagov/govuk-design-system#4096]
## Brief

Design System Day in person conference happened on the 5 September. This brief should include all the after event activities. Some things to include in this brief

- completing procurement and paying suppliers
- thank you to volunteers
- thank you to speakers
- thank you to organisers
- retrospectives
- any blogs, show & tells about the event
- stats on attendees, diversity

## Epic lead
Imran

## Leading role
Kam
```[tasklist]
### Tasks
- [ ] https://github.com/alphagov/govuk-design-system/issues/4097
- [ ] https://github.com/alphagov/govuk-design-system/issues/4099
- [ ] https://github.com/alphagov/govuk-design-system/issues/4100
- [ ] https://github.com/alphagov/govuk-design-system/issues/4101
- [ ] https://github.com/alphagov/govuk-design-system/issues/4102
- [ ] https://github.com/alphagov/govuk-design-system/issues/4103
- [ ] https://github.com/alphagov/govuk-design-system/issues/4104
- [ ] https://github.com/alphagov/govuk-design-system/issues/4105
- [ ] https://github.com/alphagov/govuk-design-system/issues/4106
- [ ] https://github.com/alphagov/govuk-design-system/issues/4091
- [ ] https://github.com/alphagov/govuk-design-system/issues/4124
```

**Comment by 36degrees** [comment]
Looks like this is done.
