### ISSUE TITLE
Understand what changes we will make to our processes to ship things we're unsure of

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#4165]
## Brief
Identify and agree priority iterations we will make to our design, build and shipping processes to more confidently ship things we're unsure of.

## Driving role(s)
Kelly, Romaric, Calvin, Charlotte

## Further
Exploratory work and pain points identified [here](https://docs.google.com/document/d/1VHLalnPY6_ReQHXqjlgBAsCAOHUTPwwxcg2A_lSP3a4/edit#heading=h.w3feyqux0zc2).

```[tasklist]
### Tasks
- [x] Run pain points and ideation workshop
- [x] Group ideas generated
- [x] Share with team for comment
- [ ] https://github.com/alphagov/govuk-design-system/issues/4221
```
