### ISSUE TITLE
Improve the accessibility of the GOV.UK Design System website following DAC audit

### ISSUE THREAD

**Issue by owenatgov** [alphagov/govuk-design-system#4167]
## Brief
Publish improvements to the design system website following work to address the DAC audit of the website. We've addressed the major issues and to tackle most of the remaining tripple A and usability issues, we will be:

- carrying out the accessible content audit planned as part of https://github.com/alphagov/design-system-team-internal/issues/919, with the intent to resolve as many of the content issues listed below as possible
- iterating the site search, with the intent to provide a more cohesive solution to https://github.com/alphagov/govuk-design-system/issues/4006

## Epic lead
@owenatgov 

## Driving role(s)
@selfthinker @calvin-lau-sig7 @hazalarpalikli @querkmachine @Izabela-16 

## Further detail
This brief follows 2 previous cycles of work following the DAC audit of the website:

- https://github.com/alphagov/govuk-design-system/issues/3967 where we addressed single A issues and some of the tripple A and usability issues raised by DAC
- https://github.com/alphagov/design-system-team-internal/issues/912 where we started planning an accessible content audit to address DAC guidance issues and investigated 3 open issues from the DAC audit of govuk-frontend in 2023

As a result, there are a number of things we want to also finish off from those cycles:

- Wash up the 3 investigations started in the previous cycle
- Progress engagement with vendors
- Try to finish any issues raised that we think are worth doing but haven't gotten around to yet

We will additionally be using this cycle to run through all remaining issues from this most recent DAC audit and make deicisions about if we want to keep them open with the intent to tackle them now or later, or close them with the intent to not do. The only remaining issues are usability and tripple A so if we have good reason to not do them, we can make that call.

```[tasklist]
### Tasks
- [ ] https://github.com/alphagov/design-system-team-internal/issues/919
- [ ] https://github.com/alphagov/govuk-frontend/issues/5309
- [ ] https://github.com/alphagov/govuk-design-system/issues/4015
- [ ] https://github.com/alphagov/govuk-design-system/issues/4026
- [ ] https://github.com/alphagov/govuk-design-system/issues/4012
```

**Comment by owenatgov** [comment]
The cycle is over and this work has been superceded by https://github.com/alphagov/govuk-design-system/issues/4237
