### ISSUE TITLE
Implement accessibility improvements to the website

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#4237]
## Brief
By the end of this brief, we should achieved the following:
- ship improvements to search results to improve the experience of screen reader users
- fix or adjust link text issues identified in the content audit
- update our accessibility strategy to include information on how we deal with bugs in 3rd party software

We should also consider publicly documenting our decision making rationale regarding these changes on the [community backlog](https://github.com/orgs/alphagov/projects/43/views/2) or [GitHub discussions](https://github.com/alphagov/govuk-design-system/discussions).

## Epic lead
Owen

## Driving role(s)
Hazal, Calvin, Anika

## Supporting roles
Kelly

```[tasklist]
### Tasks
- [ ] https://github.com/alphagov/govuk-design-system/issues/4195
- [ ] https://github.com/alphagov/govuk-design-system/issues/4194
- [ ] https://github.com/alphagov/govuk-design-system/issues/4267
- [ ] https://github.com/alphagov/design-system-team-internal/issues/918
- [ ] https://github.com/alphagov/govuk-design-system/issues/4269
- [x] For post-cycle: feed remaining audit issues to the leads (thread in slack about this on hover states)
```

```[tasklist]
### Stretch goals
- [ ] https://github.com/alphagov/govuk-design-system/issues/4268
- [ ] https://github.com/alphagov/govuk-design-system/issues/4270
- [ ] https://github.com/alphagov/govuk-frontend/issues/5448
- [ ] https://github.com/alphagov/govuk-design-system/issues/4271
```

**Comment by kellylee-gds** [comment]
Closing this brief.
