### ISSUE TITLE
Design and run a Design System "Hack" Day

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#4240]
## Brief
By the end of the cycle we should have:
- understood how we will facilitate the day
- organised with GDS reception how registration will work
- understood how we will serve food and drink to attendees
- recruited and prepared any external speakers
- sent joining instructions to attendees
- created any materials and / or slide decks to be used on the day
- have a process in place to handle queries about the event

## Epic lead
Imran

## Driving role(s)
Kam (delivery)
Mia (graphics)

## Supporting roles
The whole team, to help run the event.

## Needs awareness
DSP comms team

```[tasklist]
### Hackathon
- [ ] https://github.com/alphagov/govuk-design-system/issues/4178
- [ ] https://github.com/alphagov/govuk-design-system/issues/4254
- [ ] https://github.com/alphagov/govuk-design-system/issues/4255
- [ ] https://github.com/alphagov/govuk-design-system/issues/4256
- [ ] https://github.com/alphagov/govuk-design-system/issues/4257
- [ ] https://github.com/alphagov/govuk-design-system/issues/4258
- [ ] https://github.com/alphagov/govuk-design-system/issues/4259
- [ ] https://github.com/alphagov/govuk-design-system/issues/4260
- [ ] https://github.com/alphagov/govuk-design-system/issues/4264
- [ ] https://github.com/alphagov/govuk-design-system/issues/4265
- [ ] https://github.com/alphagov/govuk-design-system/issues/4279
```
```[tasklist]
### Wrap up DS Day Live
- [ ] https://github.com/alphagov/govuk-design-system/issues/4098
- [ ] https://github.com/alphagov/govuk-design-system/issues/4101
```

**Comment by trang-erskine** [comment]
Volunteers from the team?

**Comment by kellylee-gds** [comment]
@trang-erskine Imran is currently defining the volunteer roles needed. We can then decide whether to fill those roles from the team, or recruit external volunteers
