### ISSUE TITLE
Hold initial conversations with selected Top 75 services and assess potential for testimonial content

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#4251]
## Brief
By the end of this brief we should held an initial conversation with all prioritised services and assessed whether we can work with them on a testimonial.

## Epic lead
Katrina

## Supporting roles
Kelly, Trang

## Needs awareness
The entire team

```[tasklist]
### Tasks
- [ ] https://github.com/alphagov/govuk-design-system/issues/4217
- [ ] https://github.com/alphagov/govuk-design-system/issues/4299
- [x] Recruit members of the team to join initial chat
- [x] Decide on most appropriate method for collecting information on things we want to learn about
```

**Comment by kellylee-gds** [comment]
This brief is complete.
