### ISSUE TITLE
Get data from Github on who is using the Design System

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#4284]
## Brief

By the end of the cycle we should have a first iteration of team metrics available in one place. 
More specifically, a list of who is using GOV.UK Frontend, by service name / github repo and organisation. 

**MUST**
- total number of github repo dependent on GOV.UK frontend - monthly, ie https://github.com/alphagov/govuk-frontend/network/dependents
- list of github repos that uses GOV.UK frontend, including via ports
- a way to assign organisation name to the repo list
- a way to collect the github repo data automatically and regularly (quarterly?)
- combine the github list with other sources, e.g x-gov, manual checks like the top 100, top 75 etc so that we have a comprehensive list of who and which organisation are using the Design System

**SHOULD**
- one place to display and find team metric
- include npm data into the same location, updated automatically and regularly (monthly)

**COULD**
- include mailchimp, total subscribers per month, into the same location, updated automatically and regularly (monthly)
- include zendesk data, total number of tickets per month, into the same location, updated automatically and regularly (monthly)
- build a dashboard

**WON'T**
- report on availability metric

## Epic lead
Trang

## Driving role(s)
Brett, Owen

```[tasklist]
### Repo housekeeping
- [x] Use DS auth token [using GitHub Actions' token]
- [x] Add basic linting to repo https://github.com/alphagov/design-system-github-stats/pull/6
- [x] Remove raw-deps.json from ignore list https://github.com/alphagov/design-system-github-stats/pull/5
- [x] Set branch protection rules
```
```[tasklist]
### Data gathering
- [x] Review filter/validation lists
- [x] Investigate retrieving data from indirect dependencies (including looking into how different tools consume govuk-frontend)
```

```[tasklist]
### Automation
- [ ] Automate running of the script
- [x] Save to dated google sheet, with a separate sheet per view?
```

```[tasklist]
### \[Stretch] Dashboard
- [ ] https://github.com/alphagov/govuk-design-system/issues/4392
- [x] Add basic tests to repo
- [x] Add history for results
- [ ] Add reporting: on regressions, on script failures
- [ ] Decide where to host Dashboard
- [ ] Add NPM data
- [ ] Add mailchimp data
- [ ] Add Zendesk data
```

**Comment by trang-erskine** [comment]
SMT want some kind of availability that's common across the products. 

- Pay is using payment acceptance rates, probably something on here https://payments.statuspage.io/#. 

- Notify provide uptime and 100% of messages sent within 10 seconds. 

We could share availability for Netlify (GOV.UK Design System website) and npm (GOV.UK Frontend).

**Comment by trang-erskine** [comment]
Value metrics 
- npm download
- number of services using the Design System 
- number organisation using the Design System
- community membership (total subscribers to mailchimp) 

Nice to have? 
- % of services using which major version of Frontend. e.g V4, V5

**Comment by trang-erskine** [comment]
Support / operational metrics, @kellylee-gds do you think we should zendesk? or is there anything else you can think of?

**Comment by kellylee-gds** [comment]
@trang-erskine I think Zendesk is a better metric than GitHub or Slack (at least until we begin proper backlog moderation)

**Comment by domoscargin** [comment]
We created an MVP implementation to deliver before the end of the cycle: https://github.com/alphagov/design-system-github-stats/pull/4

We have further improved the repo (https://github.com/alphagov/design-system-github-stats/pull/20, https://github.com/alphagov/design-system-github-stats/pull/27) and plan to create small stories to finish up the work.
