### ISSUE TITLE
Tracking and measuring community objective 

### ISSUE THREAD

**Issue by trang-erskine** [alphagov/govuk-design-system#4314]
## What

The team has recently agreed on community objectives. We need a way to measure how well we are working towards our key results. 

## Why

Find out where we're not doing so well and make improvements

## Who needs to work on this
Trang, Imran, Kam

```[tasklist]
### Tasks
- [ ] Collect historical data on community membership (i.e. mailchimp subscription)
- [ ] Work out % increase in community membership quarter to quarter
- [ ] Work out how to track and measure contribution
- [ ] Work out how to track repeat attendees
- [ ] Work out how to measure percentage of core vs peripheral members
- [ ] Work out how to track team involvement in community activities 
- [ ] Work out how to track team involvement in GDS communications
- [ ] Work out how to track contribution
- [ ] Work out how to track new contributors
- [ ] Work out how to measure new community membership retention
- [ ] Review community objective key results
```
