### ISSUE TITLE
Build a roadmap of community activities for 2025

### ISSUE THREAD

**Issue by trang-erskine** [alphagov/govuk-design-system#4315]
## What

Pull together a rough outline of community activities planned for 2025.

## Why

So we can plan and budget for it

## Who needs to work on this
Imran, Kam

## Who needs to review this
Kelly, Trang

```[tasklist]
## Task
- [ ] https://github.com/alphagov/govuk-design-system/issues/4361
- [ ] https://github.com/alphagov/govuk-design-system/issues/4362
- [ ] https://github.com/alphagov/govuk-design-system/issues/4363
- [ ] https://github.com/alphagov/govuk-design-system/issues/4364
- [ ] https://github.com/alphagov/design-system-team-internal/issues/930
- [ ] https://github.com/alphagov/govuk-design-system/issues/4365
```

**Comment by kellylee-gds** [comment]
[WIP doc](https://docs.google.com/spreadsheets/d/1pyPwh4bbN2ZT9qDeV32bvvVhdQGvp7lPhTd8YLzuHIQ/edit?gid=0#gid=0) [restricted document]
