### ISSUE TITLE
Publish 2024/25 UX and Frontend survey

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#4316]
## Brief
Survey publication date: **20 December 2024.**

Create a joint UX and Frontend survey for 2024/25. Using a decision tree format, user should be able to navigate to survey most applicable for their role.

To design the survey, you'll need to review previous UX and Frontend surveys and decide which questions to keep, remove or add.

You'll need to decide on the most appropriate tool to use for the survey, and agree a comms plan for promoting it.

## Epic lead
Brett

## Driving role(s)
Katrina, Claire

## Supporting roles
Romaric, Izabela, Trang

## Further detail
```[tasklist]
### Platform
- [ ] https://github.com/alphagov/govuk-design-system/issues/4347
- [ ] https://github.com/alphagov/govuk-design-system/issues/4348
```
```[tasklist]
### Survey Design
- [ ] https://github.com/alphagov/govuk-design-system/issues/4346
- [ ] https://github.com/alphagov/govuk-design-system/issues/4350
- [ ] https://github.com/alphagov/govuk-design-system/issues/4351
- [ ] https://github.com/alphagov/govuk-design-system/issues/4349
- [ ] https://github.com/alphagov/govuk-design-system/issues/4352
```

```[tasklist]
### Comms
- [ ] https://github.com/alphagov/govuk-design-system/issues/4353
```

**Comment by domoscargin** [comment]
Closing this issue in favour of https://github.com/alphagov/govuk-design-system/issues/4402

I've moved the open issues there.
