### ISSUE TITLE
Publish 5 high priority components and patterns (18/19 Q4)

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#678]
## What

Publish at least 3 more components or patterns this quarter, focussing on small, low-level components that allow us to build bigger things.

## Why

In order to be ready to go live by March 2020 we need to have published the most useful components and patterns, so that teams can build the majority of their service using the Design System.

## Done when...

We've published these things:

- [x] [Accordion](https://github.com/alphagov/govuk-design-system-backlog/issues/1)
- [x] [Summary list](https://github.com/alphagov/govuk-design-system-backlog/issues/182)
- [x] Advanced grid
- [x] [Check answers](https://github.com/alphagov/govuk-design-system-backlog/issues/36) (update examples)

We COULD also publish these things:

- [x] [Smaller radios and checkboxes](https://github.com/alphagov/govuk-design-system/issues/711)
[Cookie banner](https://github.com/alphagov/govuk-design-system-backlog/issues/12)
[Modal dialogue](https://github.com/alphagov/govuk-design-system-backlog/issues/30)

**Comment by kellylee-gds** [comment]
Closed as epic completed
