### ISSUE TITLE
Improve support ticket triage, logging and analysis

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#679]
## What

Improve support ticket triage, logging and analysis.

## Why

This will enable us to work more efficiently and identify improvements we can make to our products.

## Done when...

We've done these things:

- [x]  [Run a support ticket analysis](https://github.com/alphagov/design-system-team-internal/issues/15)
- [x] Improve the triage process to make it more efficient
- [x] Put measures in place to respond to new issues and pull requests
- [x] Reduce the backlog of open issues and pull requests

We SHOULD do these things:

- [x] Simplify the labelling taxonomy
- [x] Prioritise the most common issues from the analysis

We COULD also do these things:

- [x] Explore use of Probot reminders

**Comment by kellylee-gds** [comment]
Closed as epic completed
