### ISSUE TITLE
Make it easier for people to make contributions

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#680]
## What

Lower the barrier to entry for contributions, by making it easier to make smaller contributions, documenting more of the process and encouraging contributions from underrepresented groups.

## Why

If we get more contributions from a more representative range of contributors then we will be able to improve our products at a faster rate, and the improvements are more like to meet our users needs. 

## Done when...

We've done these things:

- [x] [Develop our Q4 contribution strategy](https://github.com/alphagov/govuk-design-system/issues/701)
- [x] [Plan and run Learn GitHub for content designers training session](https://github.com/alphagov/govuk-design-system/issues/725)
- [x] [Decide on and document our approach to smaller external contributions](https://github.com/alphagov/govuk-design-system/issues/690)

We SHOULD do these things too:

- [x] [Document our approach to developing and assuring components and pattern in-house](https://github.com/alphagov/govuk-design-system/issues/691)
- [ ] [Decide on and document how we acknowledge contributions](https://github.com/alphagov/govuk-design-system/issues/689)
- [ ] [Agree changes to the contribution process based on feedback from the accordion contribution](https://github.com/alphagov/govuk-design-system/issues/700)
- Improve the code of conduct so it's more actionable
- Improve the code of conduct so it helps less experienced contributors
- Involve the community more in big architectural decisions
- Ask departments to support their staff spending time on contribution

We COULD also do these things:

- Run a first timer day with the BAME network
- Put together a first-timer issues step-by-step guide
- Approach government networks and ask us to promote contribution to our members

**Comment by timpaul** [comment]
Closing this now. Related work in Q2 2019 is represented in the 'Pilot a more sustainable contribution model' epic: #108
