### ISSUE TITLE
Improve how we triage issues and pull requests in GitHub

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#693]
## What

Improve the speed at which we respond to issues and (especially) pull requests raised by people outside of the team.

## Why

Delivering a positive experience for external contributors is a priority, because a negative experience makes them less likely to contribute again in the future.

### Must

- [ ] Respond to all new issues/pull requests on daily support
- [ ] Ensure that new issues/pull requests move from support to triage smoothly

### Could

- [ ] Have better visibility over old issues that need a response
- [ ] Explore options for a template for users raising pull requests/issues

### Should

- [ ] Make it an action to clear or triage everything that comes in when on support
- [ ] Make it explicit in support playbook that the daily support role includes responding to new pull requests/issues
- [ ] Get more people from the community to review pull requests
- [ ] Explore use of Probot reminders

**Comment by timpaul** [comment]
Closing as this is now merged into #679
