### ISSUE TITLE
Make it easier to be notified about updates to our products

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#729]
## What
Create ways for users to easily find out when:
- new components or patterns are published
- existing components or patterns are updated
- we're planning to publish a specific component or pattern
- new product features are released
- there are issues with our products

## Why
Users need to know these things so that they can take advantage of improvements to our products, plan their work around ours and be informed if things go wrong.

## Possible stories

- [x] Publish our live roadmap
- [x] Prioritise the community backlog
- [x] [Explore mailing lists as a way of notifying users about updates to our products](https://github.com/alphagov/design-system-team-internal/issues/11)
- [ ] Set up Google mailing list for our products
- [x] Pilot a process for publishing product updates to the mailing list
- [x] Promote the mailing list once we're happy that our process works

**Comment by trang-erskine** [comment]
This is done. Used mail chimp instead.
