### ISSUE TITLE
Publish priority components or patterns (19/20 Q1)

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#845]
## What
Publish at least 3 priority components or patterns this in Q1 2019/20

## Why
In order to be ready to go live by March 2020 we need to have published the most useful components and patterns, so that teams can build the majority of their service using the Design System.

## Done when

- [x] [Smaller checkboxes and radio buttons](https://github.com/alphagov/govuk-design-system-backlog/issues/162)
- [x] [Alternative button styles](https://github.com/alphagov/govuk-design-system-backlog/issues/154)
- [x] [Asking for ethnicity](https://github.com/alphagov/govuk-design-system-backlog/issues/83)

**Comment by kellylee-gds** [comment]
Closed issue as all three contributions published in the Design System
