### ISSUE TITLE
Identify barriers to participation in the Design System community

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#846]
## Stories
- [x] Plan and run a session to kick of diversity and inclusion work for Q1. #78
- [x] Diversity and inclusion work #87
- [x] Review diversity and inclusion survey at 1 week point [#105](https://github.com/alphagov/design-system-team-internal/issues/105)
- [x] Analyse results of diversity and inclusion survey [#99](https://github.com/alphagov/design-system-team-internal/issues/99)
- [x] Run ideation session using diversity and inclusion survey analysis
- [x] Prioritise ideas from ideation session
- [x] Run follow up interviews [#118](https://github.com/alphagov/design-system-team-internal/issues/118)

**Comment by kellylee-gds** [comment]
Closed as moved to done
