### ISSUE TITLE
Launch the GOV.UK Prototype Kit extensions feature

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#850]
## What
We have been working with HMRC to build and trial an extension feature that will allow teams working in departments to easily use components and styles that are widely used in those departments but are not in GOV.UK Frontend. We'd now like to roll out this feature to a wider audience.

## Why
To enable people to use components, patterns and styles that are not in GOV.UK Frontend. 

This means

 - It's less likely for people to make a different version of the Prototype Kit in order to do this
 - Components and patterns are easier to test and possibly then contribute to GOV.UK Frontend.
 - It's easier for people to use the Prototype Kit who can't use GOV.UK Frontend branding

## Done when

- [x] discover from HMRC whether any changes are needed
- [x] recruit 2 more partners to test
- [ ] [get some user research for authors and end users](https://github.com/alphagov/govuk-prototype-kit/issues/751)
- [ ] [add documentation about making and installing extensions](https://github.com/alphagov/govuk-prototype-kit/issues/739)
- [ ] [add a 'currently installed extensions' list](https://github.com/alphagov/govuk-prototype-kit/issues/740)
- [ ] fix potential namespace clashing in components (alphagov/govuk-frontend#1218, alphagov/govuk-frontend#870) - important to do partly because people will copy what Frontend does
- [ ] [provide a way to import all components](https://github.com/alphagov/govuk-prototype-kit/issues/727)
- [ ] Investigate the issue of updating the Prototype Kit and losing custom node modules

## Raised by users

- [ ] [Extensions - Is logging possible if the extension fails?](https://github.com/alphagov/govuk-prototype-kit/issues/730)
- [ ] [Extensions - loading assets doesn't work with just config](https://github.com/alphagov/govuk-prototype-kit/issues/732)

**Comment by trang-erskine** [comment]
Not relevant for this repo, the Prototype Kit is making progress on this - see https://github.com/alphagov/govuk-prototype-kit/issues
