### ISSUE TITLE
Design System website improvements

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#884]
## What

Various small improvements to the Design System website

## Stories

- [x] #798 - Example page templates are too wide
- [ ] #385 - Better align custom tab logic with tab component
- [ ] #425 - Make it easy to link to sections of a page
- [ ] Make copy button more consistent with the design system
