### ISSUE TITLE
Release Frontend 3.0

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#885]
## What
When the results of the accessibility audit have been received, we will need to release version 3 of GOV.UK Frontend with updated focus styles and any other remedial fixes.

## Why
To ensure our products meet WCAG 2.1 AA standard.

## Further detail
[Make sure that the Design System meets WCAG 2.1 ](https://github.com/alphagov/govuk-design-system/issues/677)

## GOV.UK Design System

- [x] [Update 3.0 design styles for GOV.UK Design System](https://github.com/alphagov/design-system-team-internal/issues/106)
- [x] [Write guide on new focus styles](https://github.com/alphagov/govuk-design-system/issues/876)
- [x] [Review "Updating your code" guidance for accuracy](https://github.com/alphagov/govuk-design-system/issues/890)
- [x] [Provide guidance on how to migrate to Frontend from legacy products](https://github.com/alphagov/govuk-design-system/issues/892)
- [x] [Update panel component guidance for 3.0 release](https://github.com/alphagov/govuk-design-system/issues/891)
- [x] [Update accessibility page to explain how Design System meets WCAG 2.1](https://github.com/alphagov/govuk-design-system/issues/840)
- [x] [Update to the Design System to use Frontend 3.0](https://github.com/alphagov/govuk-design-system/issues/962)

Nice to have:
[Split palette on Design System into primary/secondary](https://github.com/alphagov/govuk-design-system/issues/877)
[Review main-wrapper guidance based on simplifications](https://github.com/alphagov/govuk-design-system/issues/887)

## GOV.UK Frontend

- [x] [Create an internal pre-release to test v3 of Frontend](https://github.com/alphagov/govuk-frontend/issues/1363)
- [x] [Add version 2 of the font](https://github.com/alphagov/govuk-frontend/issues/1012)
- [x] [Conditionally include legacy scripts in review app](https://github.com/alphagov/govuk-frontend/issues/1360)
- [x] [Header component script is not compatible with govuk_template](https://github.com/alphagov/govuk-frontend/issues/1270)
- [x] [Namespacing [data module] to avoid conflicts](https://github.com/alphagov/govuk-frontend/issues/1218)
- [x] [Namespacing Nunjucks macros and source code](https://github.com/alphagov/govuk-frontend/issues/870)
- [x] [Remove deprecated $class parameter and logic from govuk-grid-column mixin](https://github.com/alphagov/govuk-frontend/issues/1093)
- [x] [Make it easy to generate the error summary with correct href values](https://github.com/alphagov/govuk-frontend/issues/929)
- [x] [Document colour palette sass variable settings](https://github.com/alphagov/govuk-frontend/issues/1432)
- [x] [Update tabs and accordions to use simpler focus style](https://github.com/alphagov/govuk-frontend/issues/1424)
- [x] [Create a pre-release for testing with selected partners](https://github.com/alphagov/govuk-frontend/issues/1349)
- [x] [Usability testing of new focus states](https://github.com/alphagov/govuk-frontend/issues/1427)
- [x] [Use the revised version of the new font](https://github.com/alphagov/govuk-frontend/issues/1486) 
- [x] [Tabs focus state cropped in IE11](https://github.com/alphagov/govuk-frontend/issues/1472)
- [x] [Text alignment issue on Windows](https://github.com/alphagov/govuk-frontend/issues/1469)
- [x] ['Automatic' main-wrapper margin may be applied incorrectly in some situations](https://github.com/alphagov/govuk-frontend/issues/1479)
- [x] [Update the prototype kit config to use new govuk namespacing](https://github.com/alphagov/govuk-frontend/issues/1484)
- [x] [Ensure Frontend release notes are clear for users to migrate to 3.0](https://github.com/alphagov/govuk-frontend/issues/1348)
- [x] [Release GOV.UK Frontend 3.0 🚀](https://github.com/alphagov/govuk-frontend/issues/1485)

Nice to have:
Write guidance on how to use old colour palette if required
[Document known validator errors/warnings](https://github.com/alphagov/govuk-frontend/issues/1280)

## GOV.UK Prototype Kit

- [ ] [Update step-by-step pattern to use new focus styles](https://github.com/alphagov/govuk-prototype-kit/issues/755)
- [x] [Update task list to use new focus styles](https://github.com/alphagov/govuk-prototype-kit/issues/756)
- [x] [Release Prototype Kit v9.0](https://github.com/alphagov/govuk-prototype-kit/issues/767)

## Comms

- [x] [Review what content is needed for the release](https://github.com/alphagov/design-system-team-internal/issues/103)
- [x] [Update deprecation notices on GOV.UK Elements, GOV.UK Frontend Toolkit and GOV.UK Template](https://github.com/alphagov/design-system-team-internal/issues/100)
- [x] [Circulate link to accessibility page on the Design System more widely](https://github.com/alphagov/design-system-team-internal/issues/101)
- [x] [Colour palette blog](https://github.com/alphagov/design-system-team-internal/issues/97)
- [x] [Ensuring the Design System meets WCAG 2.1 blog](https://github.com/alphagov/design-system-team-internal/issues/98)

Nice to have:
[Publish an accessibility statement](https://github.com/alphagov/govuk-design-system/issues/824)
Publish accessibility audit results
