### ISSUE TITLE
Publish at least 3 priority components or patterns in Q2 2019

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#910]
## What
Publish at least 3 priority components or patterns in Q2 2019

## Why
We need to continue to publish the most needed components and patterns so that teams can use the Design System to build the majority of their services.

## Done when

- [ ] [Search box](https://github.com/alphagov/govuk-design-system-backlog/issues/132)
- [ ] [Pagination](https://github.com/alphagov/govuk-design-system-backlog/issues/77)
- [ ] [Search filter](https://github.com/alphagov/govuk-design-system-backlog/issues/133)

We COULD also publish:

- [ ] [Search results page](https://github.com/alphagov/govuk-design-system-backlog/issues/189)
- [ ] [Cookie banner](https://github.com/alphagov/govuk-design-system-backlog/issues/12)
- [ ] [Cookie page](https://github.com/alphagov/govuk-design-system-backlog/issues/13)

**Comment by timpaul** [comment]
Closing this as this work will be incorporated into [this epic](https://github.com/alphagov/design-system-team-internal/issues/108)
