### ISSUE TITLE
Make sure the Design System website meets WCAG 2.1

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-design-system#965]
## Design System
- [x] Search button disappearing can be confusing for some users #937
- [x] Beta banner is confusing when placed in between menu button and menu items #939
- [x] Navigating to search via the tab key in JAWS results in unexpected behaviour #938
- [x] Searches without relevant results can return results #940
- [x] Investigate native video player screen reader compatibility in Edge #911
- [x] Active state within sub navigation is unclear when colours are overridden #982
- [x] Colours in code blocks do not meet colour contrast #1032
- [x] "Aria-labelledby" on mobile navigation has incorrect ID reference #1033
- [x] Undertake a retest with DAC [#147](https://github.com/alphagov/design-system-team-internal/issues/147)

## Related issues in the accessible autocomplete

There is a milestone that is tracking all related issues in the accessible autocomplete:
https://github.com/alphagov/accessible-autocomplete/milestone/3
